import V7ProductionSnapshotObserverR30ProductionClosure

/-! Consolidated audit of the literal callback-to-terminal closure. -/
#print axioms V7ProductionCallbacksR30DecoderCanonical.successful_scanner_zero_canonical
#print axioms V7ProductionCallbacksR30PackedDecoderCanonical.successful_packed_decoder_canonical
#print axioms V7ProductionCallbacksR30PackedGammaCanonical.successful_packed_gamma_canonical
#print axioms V7ProductionCallbacksR30NormalizedFoldCanonical.successful_normalized_polynomial_refs_canonical
#print axioms V7ProductionCallbacksR30QueryValuesCanonical.successful_production_observer_query_fold_values_canonical
#print axioms AspisV7ProductionSnapshotObserverR30RunningCanonical.accepted_current_fold_tail_running_canonical
#print axioms AspisV7ProductionSnapshotObserverR30TerminalClosure.accepted_current_fold_tail_terminal_corresponds
#print axioms AspisV7ProductionSnapshotObserverR30ProductionClosure.production_snapshot_observer_acceptance_reaches_terminal_closure
