import V7RegistryOperatorSourceBridge

open V7RegistryOperatorGenerated

#print axioms translated_operator_rejection_is_exact_rollback
#print axioms translated_operator_success_is_exact_apply
#print axioms translated_operator_preserves_unrelated_pool_state
#print axioms translated_frozen_registry_rejects_authority_gate
#print axioms translated_generation_mismatch_rejects_authority_gate
#print axioms translated_compatible_replacement_success_binds_exact_relation
#print axioms translated_selected_verifier_success_has_exact_guarantee
#print axioms current_v1_selection_is_independent_of_programdata_code_hash_and_authority
#print axioms translated_combined_root_keeps_operator_and_selection_separate
