[package]
name = "aspis-xtask"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
aspis-core = { path = "../crates/aspis-core" }
aspis-prover = { path = "../crates/aspis-prover", features = ["v5-mask"] }
aspis-statement = { path = "../crates/aspis-statement" }
aspis-verifier = { path = "../programs/aspis-verifier", default-features = false, features = ["no-entrypoint", "v5-cu-probe", "v6-cu-probe"] }
anyhow.workspace = true
base64.workspace = true
bincode.workspace = true
borsh.workspace = true
chrono.workspace = true
getrandom.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
solana-sdk.workspace = true
