[package]
name = "aspis-registry"
edition.workspace = true
license.workspace = true
version.workspace = true
description = "Governed Pool V1 verifier-registry mutation program"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
no-entrypoint = []

[dependencies]
aspis-statement = { workspace = true, features = ["pool-v1-kernel"] }
bincode.workspace = true
solana-loader-v3-interface.workspace = true
solana-program.workspace = true
solana-sdk-ids = "2.2.1"
