-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aspis_verifier]: type definitions
import Aeneas
import V7Tag73CurrentNormalizationFocus.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace V7Tag73CurrentNormalizationFocus

/-- [aspis_core::field::M31]
    Source: 'crates/aspis-core/src/field.rs', lines 20:0-20:14
    Name pattern: [aspis_core::field::M31]
    Visibility: public -/
@[reducible, rust_type "aspis_core::field::M31"]
def aspis_core.field.M31 := Std.U32

/-- [aspis_core::field::CM31]
    Source: 'crates/aspis-core/src/field.rs', lines 191:0-191:15
    Name pattern: [aspis_core::field::CM31]
    Visibility: public -/
@[rust_type "aspis_core::field::CM31"]
structure aspis_core.field.CM31 where
  a : aspis_core.field.M31
  b : aspis_core.field.M31

/-- [aspis_core::field::QM31]
    Source: 'crates/aspis-core/src/field.rs', lines 360:0-360:15
    Name pattern: [aspis_core::field::QM31]
    Visibility: public -/
@[rust_type "aspis_core::field::QM31"]
structure aspis_core.field.QM31 where
  c0 : aspis_core.field.CM31
  c1 : aspis_core.field.CM31

/-- [aspis_core::field::qm31_from_karatsuba_channel_sums::closure]
    Source: 'crates/aspis-core/src/field.rs', lines 410:22-410:42
    Name pattern: [aspis_core::field::qm31_from_karatsuba_channel_sums::closure] -/
@[reducible, rust_type
  "aspis_core::field::qm31_from_karatsuba_channel_sums::closure"]
def aspis_core.field.qm31_from_karatsuba_channel_sums.closure := Unit

/-- [aspis_core::sumcheck::WeightComponent]
    Source: 'crates/aspis-core/src/sumcheck.rs', lines 26:0-26:20
    Name pattern: [aspis_core::sumcheck::WeightComponent] -/
@[discriminant isize, rust_type "aspis_core::sumcheck::WeightComponent"]
inductive aspis_core.sumcheck.WeightComponent where
| Geometric :
  aspis_core.field.QM31 →
  aspis_core.field.QM31 →
  aspis_core.sumcheck.WeightComponent
| Multilinear :
  aspis_core.field.QM31 →
  alloc.vec.Vec aspis_core.field.QM31 →
  aspis_core.sumcheck.WeightComponent
| Tensor :
  aspis_core.field.QM31 →
  alloc.vec.Vec aspis_core.field.QM31 →
  aspis_core.sumcheck.WeightComponent
| LineM31Tensor :
  aspis_core.field.QM31 →
  aspis_core.field.M31 →
  aspis_core.sumcheck.WeightComponent
| LineM31Batch :
  alloc.vec.Vec aspis_core.field.QM31 →
  alloc.vec.Vec aspis_core.field.M31 →
  Std.U8 →
  aspis_core.sumcheck.WeightComponent
| Product :
  aspis_core.field.QM31 →
  alloc.vec.Vec (Array aspis_core.field.QM31 2#usize) →
  aspis_core.sumcheck.WeightComponent
| Dense :
  alloc.vec.Vec aspis_core.field.QM31 →
  aspis_core.sumcheck.WeightComponent
| Grouped64x16 :
  alloc.vec.Vec Std.U8 →
  alloc.vec.Vec aspis_core.field.QM31 →
  Std.U8 →
  aspis_core.sumcheck.WeightComponent
| Grouped64x16BinaryDeferred :
  alloc.vec.Vec Std.U8 →
  alloc.vec.Vec Std.U16 →
  Option aspis_core.field.QM31 →
  alloc.vec.Vec aspis_core.field.QM31 →
  aspis_core.sumcheck.WeightComponent
| Grouped128x16 :
  alloc.vec.Vec Std.U8 →
  alloc.vec.Vec aspis_core.field.QM31 →
  Std.U8 →
  aspis_core.sumcheck.WeightComponent

/-- [aspis_core::sumcheck::fold_grouped_rows_twice::closure]
    Source: 'crates/aspis-core/src/sumcheck.rs', lines 314:49-314:55
    Name pattern: [aspis_core::sumcheck::fold_grouped_rows_twice::closure] -/
@[rust_type "aspis_core::sumcheck::fold_grouped_rows_twice::closure"]
def aspis_core.sumcheck.fold_grouped_rows_twice.closure :=
  Array aspis_core.field.QM31 4#usize × Array aspis_core.field.QM31 4#usize

/-- [aspis_core::sumcheck::WeightAccumulator]
    Source: 'crates/aspis-core/src/sumcheck.rs', lines 399:0-399:28
    Name pattern: [aspis_core::sumcheck::WeightAccumulator]
    Visibility: public -/
@[rust_type "aspis_core::sumcheck::WeightAccumulator"]
structure aspis_core.sumcheck.WeightAccumulator where
  log_len : Std.U32
  components : alloc.vec.Vec aspis_core.sumcheck.WeightComponent

/-- [aspis_core::sumcheck::{aspis_core::sumcheck::WeightAccumulator}::dot::closure#1]
    Source: 'crates/aspis-core/src/sumcheck.rs', lines 1853:29-1853:46
    Name pattern: [aspis_core::sumcheck::{aspis_core::sumcheck::WeightAccumulator}::dot::closure#1] -/
@[reducible, rust_type
  "aspis_core::sumcheck::{aspis_core::sumcheck::WeightAccumulator}::dot::closure#1"]
def aspis_core.sumcheck.WeightAccumulator.dot.closure_1 := Unit

/-- [aspis_core::sumcheck::{aspis_core::sumcheck::WeightAccumulator}::dot::closure]
    Source: 'crates/aspis-core/src/sumcheck.rs', lines 1798:28-1798:39
    Name pattern: [aspis_core::sumcheck::{aspis_core::sumcheck::WeightAccumulator}::dot::closure] -/
@[reducible, rust_type
  "aspis_core::sumcheck::{aspis_core::sumcheck::WeightAccumulator}::dot::closure"]
def aspis_core.sumcheck.WeightAccumulator.dot.closure := Unit

end V7Tag73CurrentNormalizationFocus
