[package]
name = "whir-m31-verifier"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
no-entrypoint = []
instrumentation = []
custom-heap = []
custom-panic = []

[dependencies]
borsh.workspace = true
solana-program.workspace = true
whir-m31-core = { path = "../../crates/whir-m31-core", default-features = false }
