import AspisFormal.V6CompactFrontierTailCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 22
Cells 42 through 42;
recurrence workload 141. -/

theorem certificate_16_4_46 :
    frontierCoeff 16 4 46 = 74 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 3 46,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 3 (46 - leftFrontier)) = 10 := by
    have live0 : supportedSplitFrontiers 15 1 3 46 = {6, 7, 8, 9, 10, 11, 12, 13, 14, 15} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_3]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
          frontierCoeff 15 1 leftFrontier *
            frontierCoeff 15 3 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
            if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else if leftFrontier = 11 then 0 else if leftFrontier = 12 then 0 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 0 else if leftFrontier = 15 then 10 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_1_10, certificate_15_1_11, certificate_15_1_12, certificate_15_1_13, certificate_15_1_14, certificate_15_1_15,
            certificate_15_1_6, certificate_15_1_7, certificate_15_1_8, certificate_15_1_9, certificate_15_3_31, certificate_15_3_32,
            certificate_15_3_33, certificate_15_3_34, certificate_15_3_35, certificate_15_3_36, certificate_15_3_37, certificate_15_3_38,
            certificate_15_3_39, certificate_15_3_40] <;> simp
      _ = 10 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 2 46,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 2 (46 - leftFrontier)) = 11 := by
    have live1 : supportedSplitFrontiers 15 2 2 46 = {18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28},
          frontierCoeff 15 2 leftFrontier *
            frontierCoeff 15 2 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28},
            if leftFrontier = 18 then 1 else if leftFrontier = 19 then 1 else if leftFrontier = 20 then 1 else if leftFrontier = 21 then 1 else if leftFrontier = 22 then 1 else if leftFrontier = 23 then 1 else if leftFrontier = 24 then 1 else if leftFrontier = 25 then 1 else if leftFrontier = 26 then 1 else if leftFrontier = 27 then 1 else if leftFrontier = 28 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_2_18, certificate_15_2_19, certificate_15_2_20, certificate_15_2_21, certificate_15_2_22, certificate_15_2_23,
            certificate_15_2_24, certificate_15_2_25, certificate_15_2_26, certificate_15_2_27, certificate_15_2_28] <;> simp
      _ = 11 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 1 46,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 1 (46 - leftFrontier)) = 10 := by
    have live2 : supportedSplitFrontiers 15 3 1 46 = {31, 32, 33, 34, 35, 36, 37, 38, 39, 40} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {31, 32, 33, 34, 35, 36, 37, 38, 39, 40},
          frontierCoeff 15 3 leftFrontier *
            frontierCoeff 15 1 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {31, 32, 33, 34, 35, 36, 37, 38, 39, 40},
            if leftFrontier = 31 then 10 else if leftFrontier = 32 then 0 else if leftFrontier = 33 then 0 else if leftFrontier = 34 then 0 else if leftFrontier = 35 then 0 else if leftFrontier = 36 then 0 else if leftFrontier = 37 then 0 else if leftFrontier = 38 then 0 else if leftFrontier = 39 then 0 else if leftFrontier = 40 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_1_10, certificate_15_1_11, certificate_15_1_12, certificate_15_1_13, certificate_15_1_14, certificate_15_1_15,
            certificate_15_1_6, certificate_15_1_7, certificate_15_1_8, certificate_15_1_9, certificate_15_3_31, certificate_15_3_32,
            certificate_15_3_33, certificate_15_3_34, certificate_15_3_35, certificate_15_3_36, certificate_15_3_37, certificate_15_3_38,
            certificate_15_3_39, certificate_15_3_40] <;> simp
      _ = 10 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (4 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (4 - (offset + 1)) 46,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (4 - (offset + 1))
              (46 - leftFrontier)) = 31 := by
    have offsets : Finset.range (4 - 1) = {0, 1, 2} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (4 - (offset + 1)) 46,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (4 - (offset + 1))
                (46 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2},
            if offset = 0 then 10 else if offset = 1 then 11 else if offset = 2 then 10 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2] <;> simp
      _ = 31 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_15_4_45] <;> simp

end AspisV6CompactFrontierTailCertificate
