import AspisFormal.V6CompactFrontierTailCertificate.Depth09

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence

/-! ## Depth 10, chunk 0
Cells 0 through 22;
recurrence workload 89. -/

theorem certificate_10_1_0 :
    frontierCoeff 10 1 0 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_1 :
    frontierCoeff 10 1 1 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_2 :
    frontierCoeff 10 1 2 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_3 :
    frontierCoeff 10 1 3 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_4 :
    frontierCoeff 10 1 4 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_5 :
    frontierCoeff 10 1 5 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_6 :
    frontierCoeff 10 1 6 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_7 :
    frontierCoeff 10 1 7 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_8 :
    frontierCoeff 10 1 8 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_9 :
    frontierCoeff 10 1 9 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_1_10 :
    frontierCoeff 10 1 10 = 1 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_0 :
    frontierCoeff 10 2 0 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_1 :
    frontierCoeff 10 2 1 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_2 :
    frontierCoeff 10 2 2 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_3 :
    frontierCoeff 10 2 3 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_4 :
    frontierCoeff 10 2 4 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_5 :
    frontierCoeff 10 2 5 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_6 :
    frontierCoeff 10 2 6 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_7 :
    frontierCoeff 10 2 7 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_8 :
    frontierCoeff 10 2 8 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_9 :
    frontierCoeff 10 2 9 = 1 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_10 :
    frontierCoeff 10 2 10 = 1 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_10_2_11 :
    frontierCoeff 10 2 11 = 1 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

end AspisV6CompactFrontierTailCertificate
