import AspisFormal.V6CompactFrontierTailCertificate.Depth08

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence

/-! ## Depth 9, chunk 13
Cells 61 through 64;
recurrence workload 78. -/

theorem certificate_9_4_4 :
    frontierCoeff 9 4 4 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_9_4_5 :
    frontierCoeff 9 4 5 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_9_4_6 :
    frontierCoeff 9 4 6 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

theorem certificate_9_4_7 :
    frontierCoeff 9 4 7 = 1 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

end AspisV6CompactFrontierTailCertificate
