import AspisFormal.V6CompactFrontierTailCertificate.Depth11

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence

/-! ## Depth 12, chunk 123
Cells 186 through 186;
recurrence workload 280. -/

theorem certificate_12_6_55 :
    frontierCoeff 12 6 55 = 22 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

end AspisV6CompactFrontierTailCertificate
