import AspisFormal.V6CompactFrontierTailCertificate.Depth14

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence

/-! ## Depth 15, chunk 379
Cells 446 through 446;
recurrence workload 1332. -/

theorem certificate_15_10_147 :
    frontierCoeff 15 10 147 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

end AspisV6CompactFrontierTailCertificate
