import AspisFormal.V6CompactFrontierTailCertificate.Depth11
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 12, chunk 13
Cells 36 through 36;
recurrence workload 123. -/

theorem certificate_12_4_40 :
    frontierCoeff 12 4 40 = 1 := by
  have zero_11_4_39 :
      frontierCoeff 11 4 39 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 3 40,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 3 (40 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 3 40 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1, support_11_3]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 2 2 40,
        frontierCoeff 11 2 leftFrontier *
          frontierCoeff 11 2 (40 - leftFrontier)) = 1 := by
    have live1 : supportedSplitFrontiers 11 2 2 40 = {20} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {20},
          frontierCoeff 11 2 leftFrontier *
            frontierCoeff 11 2 (40 - leftFrontier)) =
          ∑ leftFrontier ∈ {20},
            if leftFrontier = 20 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_11_2_20] <;> simp
      _ = 1 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 3 1 40,
        frontierCoeff 11 3 leftFrontier *
          frontierCoeff 11 1 (40 - leftFrontier)) = 0 := by
    have live2 : supportedSplitFrontiers 11 3 1 40 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1, support_11_3]
      ext value
      simp <;> omega
    rw [live2]
    simp
  have outer :
      (∑ offset ∈ Finset.range (4 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (4 - (offset + 1)) 40,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (4 - (offset + 1))
              (40 - leftFrontier)) = 1 := by
    have offsets : Finset.range (4 - 1) = {0, 1, 2} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (4 - (offset + 1)) 40,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (4 - (offset + 1))
                (40 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2},
            if offset = 0 then 0 else if offset = 1 then 1 else if offset = 2 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2] <;> simp
      _ = 1 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_11_4_39] <;> simp

end AspisV6CompactFrontierTailCertificate
