import AspisFormal.V6CompactFrontierTailCertificate.Depth17
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 18, chunk 14
Cells 14 through 14;
recurrence workload 3375. -/

theorem certificate_18_16_224 :
    frontierCoeff 18 16 224 = 1 := by
  have zero_17_16_223 :
      frontierCoeff 17 16 223 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 1 15 224,
        frontierCoeff 17 1 leftFrontier *
          frontierCoeff 17 15 (224 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 17 1 15 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_1, support_17_15]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 2 14 224,
        frontierCoeff 17 2 leftFrontier *
          frontierCoeff 17 14 (224 - leftFrontier)) = 0 := by
    have live1 : supportedSplitFrontiers 17 2 14 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_14, support_17_2]
      ext value
      simp <;> omega
    rw [live1]
    simp
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 3 13 224,
        frontierCoeff 17 3 leftFrontier *
          frontierCoeff 17 13 (224 - leftFrontier)) = 0 := by
    have live2 : supportedSplitFrontiers 17 3 13 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_13, support_17_3]
      ext value
      simp <;> omega
    rw [live2]
    simp
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 4 12 224,
        frontierCoeff 17 4 leftFrontier *
          frontierCoeff 17 12 (224 - leftFrontier)) = 0 := by
    have live3 : supportedSplitFrontiers 17 4 12 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_12, support_17_4]
      ext value
      simp <;> omega
    rw [live3]
    simp
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 5 11 224,
        frontierCoeff 17 5 leftFrontier *
          frontierCoeff 17 11 (224 - leftFrontier)) = 0 := by
    have live4 : supportedSplitFrontiers 17 5 11 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_11, support_17_5]
      ext value
      simp <;> omega
    rw [live4]
    simp
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 6 10 224,
        frontierCoeff 17 6 leftFrontier *
          frontierCoeff 17 10 (224 - leftFrontier)) = 0 := by
    have live5 : supportedSplitFrontiers 17 6 10 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_10, support_17_6]
      ext value
      simp <;> omega
    rw [live5]
    simp
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 7 9 224,
        frontierCoeff 17 7 leftFrontier *
          frontierCoeff 17 9 (224 - leftFrontier)) = 0 := by
    have live6 : supportedSplitFrontiers 17 7 9 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_7, support_17_9]
      ext value
      simp <;> omega
    rw [live6]
    simp
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 8 8 224,
        frontierCoeff 17 8 leftFrontier *
          frontierCoeff 17 8 (224 - leftFrontier)) = 1 := by
    have live7 : supportedSplitFrontiers 17 8 8 224 = {112} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {112},
          frontierCoeff 17 8 leftFrontier *
            frontierCoeff 17 8 (224 - leftFrontier)) =
          ∑ leftFrontier ∈ {112},
            if leftFrontier = 112 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_17_8_112] <;> simp
      _ = 1 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 9 7 224,
        frontierCoeff 17 9 leftFrontier *
          frontierCoeff 17 7 (224 - leftFrontier)) = 0 := by
    have live8 : supportedSplitFrontiers 17 9 7 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_7, support_17_9]
      ext value
      simp <;> omega
    rw [live8]
    simp
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 10 6 224,
        frontierCoeff 17 10 leftFrontier *
          frontierCoeff 17 6 (224 - leftFrontier)) = 0 := by
    have live9 : supportedSplitFrontiers 17 10 6 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_10, support_17_6]
      ext value
      simp <;> omega
    rw [live9]
    simp
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 11 5 224,
        frontierCoeff 17 11 leftFrontier *
          frontierCoeff 17 5 (224 - leftFrontier)) = 0 := by
    have live10 : supportedSplitFrontiers 17 11 5 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_11, support_17_5]
      ext value
      simp <;> omega
    rw [live10]
    simp
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 12 4 224,
        frontierCoeff 17 12 leftFrontier *
          frontierCoeff 17 4 (224 - leftFrontier)) = 0 := by
    have live11 : supportedSplitFrontiers 17 12 4 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_12, support_17_4]
      ext value
      simp <;> omega
    rw [live11]
    simp
  have split12 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 13 3 224,
        frontierCoeff 17 13 leftFrontier *
          frontierCoeff 17 3 (224 - leftFrontier)) = 0 := by
    have live12 : supportedSplitFrontiers 17 13 3 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_13, support_17_3]
      ext value
      simp <;> omega
    rw [live12]
    simp
  have split13 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 14 2 224,
        frontierCoeff 17 14 leftFrontier *
          frontierCoeff 17 2 (224 - leftFrontier)) = 0 := by
    have live13 : supportedSplitFrontiers 17 14 2 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_14, support_17_2]
      ext value
      simp <;> omega
    rw [live13]
    simp
  have split14 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 15 1 224,
        frontierCoeff 17 15 leftFrontier *
          frontierCoeff 17 1 (224 - leftFrontier)) = 0 := by
    have live14 : supportedSplitFrontiers 17 15 1 224 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_1, support_17_15]
      ext value
      simp <;> omega
    rw [live14]
    simp
  have outer :
      (∑ offset ∈ Finset.range (16 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 17 (offset + 1)
            (16 - (offset + 1)) 224,
          frontierCoeff 17 (offset + 1) leftFrontier *
            frontierCoeff 17 (16 - (offset + 1))
              (224 - leftFrontier)) = 1 := by
    have offsets : Finset.range (16 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
          ∑ leftFrontier ∈ supportedSplitFrontiers 17 (offset + 1)
              (16 - (offset + 1)) 224,
            frontierCoeff 17 (offset + 1) leftFrontier *
              frontierCoeff 17 (16 - (offset + 1))
                (224 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            if offset = 0 then 0 else if offset = 1 then 0 else if offset = 2 then 0 else if offset = 3 then 0 else if offset = 4 then 0 else if offset = 5 then 0 else if offset = 6 then 0 else if offset = 7 then 1 else if offset = 8 then 0 else if offset = 9 then 0 else if offset = 10 then 0 else if offset = 11 then 0 else if offset = 12 then 0 else if offset = 13 then 0 else if offset = 14 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11,
            split12, split13, split14] <;> simp
      _ = 1 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_17_16_223] <;> simp

theorem weighted_certificate_18_16_224 :
    concreteFrontierCount 18 16 224 = 26959946667150639794667015087019630673637144422540572481103610249216 := by
  rw [concreteFrontierCount, certificate_18_16_224]
  norm_num

end AspisV6CompactFrontierTailCertificate
