import AspisFormal.V6CompactFrontierTailCertificate.Depth14
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 15, chunk 3
Cells 26 through 28;
recurrence workload 84. -/

theorem certificate_15_2_26 :
    frontierCoeff 15 2 26 = 1 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 1 26,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 1 (26 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 14 1 1 26 = {12, 13, 14} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {12, 13, 14},
          frontierCoeff 14 1 leftFrontier *
            frontierCoeff 14 1 (26 - leftFrontier)) =
          ∑ leftFrontier ∈ {12, 13, 14},
            if leftFrontier = 12 then 0 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_14_1_12, certificate_14_1_13, certificate_14_1_14] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (2 - (offset + 1)) 26,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (2 - (offset + 1))
              (26 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (2 - (offset + 1)) 26,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (2 - (offset + 1))
                (26 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_14_2_25] <;> simp

theorem certificate_15_2_27 :
    frontierCoeff 15 2 27 = 1 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 1 27,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 1 (27 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 14 1 1 27 = {13, 14} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {13, 14},
          frontierCoeff 14 1 leftFrontier *
            frontierCoeff 14 1 (27 - leftFrontier)) =
          ∑ leftFrontier ∈ {13, 14},
            if leftFrontier = 13 then 0 else if leftFrontier = 14 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_14_1_13, certificate_14_1_14] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (2 - (offset + 1)) 27,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (2 - (offset + 1))
              (27 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (2 - (offset + 1)) 27,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (2 - (offset + 1))
                (27 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_14_2_26] <;> simp

theorem certificate_15_2_28 :
    frontierCoeff 15 2 28 = 1 := by
  have zero_14_2_27 :
      frontierCoeff 14 2 27 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 1 28,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 1 (28 - leftFrontier)) = 1 := by
    have live0 : supportedSplitFrontiers 14 1 1 28 = {14} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {14},
          frontierCoeff 14 1 leftFrontier *
            frontierCoeff 14 1 (28 - leftFrontier)) =
          ∑ leftFrontier ∈ {14},
            if leftFrontier = 14 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_14_1_14] <;> simp
      _ = 1 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (2 - (offset + 1)) 28,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (2 - (offset + 1))
              (28 - leftFrontier)) = 1 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (2 - (offset + 1)) 28,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (2 - (offset + 1))
                (28 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 1 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_14_2_27] <;> simp

end AspisV6CompactFrontierTailCertificate
