import AspisFormal.V6CompactFrontierTailCertificate.Depth16
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 17, chunk 112
Cells 120 through 120;
recurrence workload 1460. -/

theorem certificate_17_11_145 :
    frontierCoeff 17 11 145 = 6392 := by
  have zero_16_11_144 :
      frontierCoeff 16 11 144 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 1 10 145,
        frontierCoeff 16 1 leftFrontier *
          frontierCoeff 16 10 (145 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 16 1 10 145 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_10]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 2 9 145,
        frontierCoeff 16 2 leftFrontier *
          frontierCoeff 16 9 (145 - leftFrontier)) = 8 := by
    have live1 : supportedSplitFrontiers 16 2 9 145 = {30} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_2, support_16_9]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {30},
          frontierCoeff 16 2 leftFrontier *
            frontierCoeff 16 9 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {30},
            if leftFrontier = 30 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_2_30, certificate_16_9_115] <;> simp
      _ = 8 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 3 8 145,
        frontierCoeff 16 3 leftFrontier *
          frontierCoeff 16 8 (145 - leftFrontier)) = 296 := by
    have live2 : supportedSplitFrontiers 16 3 8 145 = {41, 42, 43} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_3, support_16_8]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {41, 42, 43},
          frontierCoeff 16 3 leftFrontier *
            frontierCoeff 16 8 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {41, 42, 43},
            if leftFrontier = 41 then 4 else if leftFrontier = 42 then 56 else if leftFrontier = 43 then 236 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_16_3_41, certificate_16_3_42, certificate_16_3_43, certificate_16_8_102, certificate_16_8_103, certificate_16_8_104] <;> simp
      _ = 296 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 4 7 145,
        frontierCoeff 16 4 leftFrontier *
          frontierCoeff 16 7 (145 - leftFrontier)) = 1064 := by
    have live3 : supportedSplitFrontiers 16 4 7 145 = {53, 54, 55, 56} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_4, support_16_7]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {53, 54, 55, 56},
          frontierCoeff 16 4 leftFrontier *
            frontierCoeff 16 7 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {53, 54, 55, 56},
            if leftFrontier = 53 then 52 else if leftFrontier = 54 then 252 else if leftFrontier = 55 then 528 else if leftFrontier = 56 then 232 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_4_53, certificate_16_4_54, certificate_16_4_55, certificate_16_4_56, certificate_16_7_89, certificate_16_7_90,
            certificate_16_7_91, certificate_16_7_92] <;> simp
      _ = 1064 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 5 6 145,
        frontierCoeff 16 5 leftFrontier *
          frontierCoeff 16 6 (145 - leftFrontier)) = 1828 := by
    have live4 : supportedSplitFrontiers 16 5 6 145 = {65, 66, 67, 68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_5, support_16_6]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {65, 66, 67, 68},
          frontierCoeff 16 5 leftFrontier *
            frontierCoeff 16 6 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {65, 66, 67, 68},
            if leftFrontier = 65 then 228 else if leftFrontier = 66 then 616 else if leftFrontier = 67 then 560 else if leftFrontier = 68 then 424 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_5_65, certificate_16_5_66, certificate_16_5_67, certificate_16_5_68, certificate_16_6_77, certificate_16_6_78,
            certificate_16_6_79, certificate_16_6_80] <;> simp
      _ = 1828 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 6 5 145,
        frontierCoeff 16 6 leftFrontier *
          frontierCoeff 16 5 (145 - leftFrontier)) = 1828 := by
    have live5 : supportedSplitFrontiers 16 6 5 145 = {77, 78, 79, 80} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_5, support_16_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {77, 78, 79, 80},
          frontierCoeff 16 6 leftFrontier *
            frontierCoeff 16 5 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {77, 78, 79, 80},
            if leftFrontier = 77 then 424 else if leftFrontier = 78 then 560 else if leftFrontier = 79 then 616 else if leftFrontier = 80 then 228 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_5_65, certificate_16_5_66, certificate_16_5_67, certificate_16_5_68, certificate_16_6_77, certificate_16_6_78,
            certificate_16_6_79, certificate_16_6_80] <;> simp
      _ = 1828 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 7 4 145,
        frontierCoeff 16 7 leftFrontier *
          frontierCoeff 16 4 (145 - leftFrontier)) = 1064 := by
    have live6 : supportedSplitFrontiers 16 7 4 145 = {89, 90, 91, 92} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_4, support_16_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {89, 90, 91, 92},
          frontierCoeff 16 7 leftFrontier *
            frontierCoeff 16 4 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {89, 90, 91, 92},
            if leftFrontier = 89 then 232 else if leftFrontier = 90 then 528 else if leftFrontier = 91 then 252 else if leftFrontier = 92 then 52 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_4_53, certificate_16_4_54, certificate_16_4_55, certificate_16_4_56, certificate_16_7_89, certificate_16_7_90,
            certificate_16_7_91, certificate_16_7_92] <;> simp
      _ = 1064 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 8 3 145,
        frontierCoeff 16 8 leftFrontier *
          frontierCoeff 16 3 (145 - leftFrontier)) = 296 := by
    have live7 : supportedSplitFrontiers 16 8 3 145 = {102, 103, 104} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_3, support_16_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {102, 103, 104},
          frontierCoeff 16 8 leftFrontier *
            frontierCoeff 16 3 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {102, 103, 104},
            if leftFrontier = 102 then 236 else if leftFrontier = 103 then 56 else if leftFrontier = 104 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_16_3_41, certificate_16_3_42, certificate_16_3_43, certificate_16_8_102, certificate_16_8_103, certificate_16_8_104] <;> simp
      _ = 296 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 9 2 145,
        frontierCoeff 16 9 leftFrontier *
          frontierCoeff 16 2 (145 - leftFrontier)) = 8 := by
    have live8 : supportedSplitFrontiers 16 9 2 145 = {115} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_2, support_16_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {115},
          frontierCoeff 16 9 leftFrontier *
            frontierCoeff 16 2 (145 - leftFrontier)) =
          ∑ leftFrontier ∈ {115},
            if leftFrontier = 115 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_2_30, certificate_16_9_115] <;> simp
      _ = 8 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 10 1 145,
        frontierCoeff 16 10 leftFrontier *
          frontierCoeff 16 1 (145 - leftFrontier)) = 0 := by
    have live9 : supportedSplitFrontiers 16 10 1 145 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_10]
      ext value
      simp <;> omega
    rw [live9]
    simp
  have outer :
      (∑ offset ∈ Finset.range (11 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
            (11 - (offset + 1)) 145,
          frontierCoeff 16 (offset + 1) leftFrontier *
            frontierCoeff 16 (11 - (offset + 1))
              (145 - leftFrontier)) = 6392 := by
    have offsets : Finset.range (11 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
          ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
              (11 - (offset + 1)) 145,
            frontierCoeff 16 (offset + 1) leftFrontier *
              frontierCoeff 16 (11 - (offset + 1))
                (145 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
            if offset = 0 then 0 else if offset = 1 then 8 else if offset = 2 then 296 else if offset = 3 then 1064 else if offset = 4 then 1828 else if offset = 5 then 1828 else if offset = 6 then 1064 else if offset = 7 then 296 else if offset = 8 then 8 else if offset = 9 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9] <;> simp
      _ = 6392 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_16_11_144] <;> simp

end AspisV6CompactFrontierTailCertificate
