import AspisFormal.V6CompactFrontierTailCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 67
Cells 87 through 87;
recurrence workload 534. -/

theorem certificate_16_7_88 :
    frontierCoeff 16 7 88 = 448 := by
  have zero_15_7_87 :
      frontierCoeff 15 7 87 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 6 88,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 6 (88 - leftFrontier)) = 22 := by
    have live0 : supportedSplitFrontiers 15 1 6 88 = {14, 15} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_6]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {14, 15},
          frontierCoeff 15 1 leftFrontier *
            frontierCoeff 15 6 (88 - leftFrontier)) =
          ∑ leftFrontier ∈ {14, 15},
            if leftFrontier = 14 then 0 else if leftFrontier = 15 then 22 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_1_14, certificate_15_1_15, certificate_15_6_73, certificate_15_6_74] <;> simp
      _ = 22 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 5 88,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 5 (88 - leftFrontier)) = 80 := by
    have live1 : supportedSplitFrontiers 15 2 5 88 = {25, 26, 27, 28} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_5]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {25, 26, 27, 28},
          frontierCoeff 15 2 leftFrontier *
            frontierCoeff 15 5 (88 - leftFrontier)) =
          ∑ leftFrontier ∈ {25, 26, 27, 28},
            if leftFrontier = 25 then 4 else if leftFrontier = 26 then 10 else if leftFrontier = 27 then 28 else if leftFrontier = 28 then 38 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_2_25, certificate_15_2_26, certificate_15_2_27, certificate_15_2_28, certificate_15_5_60, certificate_15_5_61,
            certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 80 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 4 88,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 4 (88 - leftFrontier)) = 122 := by
    have live2 : supportedSplitFrontiers 15 3 4 88 = {36, 37, 38, 39, 40} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_4]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {36, 37, 38, 39, 40},
          frontierCoeff 15 3 leftFrontier *
            frontierCoeff 15 4 (88 - leftFrontier)) =
          ∑ leftFrontier ∈ {36, 37, 38, 39, 40},
            if leftFrontier = 36 then 6 else if leftFrontier = 37 then 24 else if leftFrontier = 38 then 28 else if leftFrontier = 39 then 26 else if leftFrontier = 40 then 38 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_3_36, certificate_15_3_37, certificate_15_3_38, certificate_15_3_39, certificate_15_3_40, certificate_15_4_48,
            certificate_15_4_49, certificate_15_4_50, certificate_15_4_51, certificate_15_4_52] <;> simp
      _ = 122 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 4 3 88,
        frontierCoeff 15 4 leftFrontier *
          frontierCoeff 15 3 (88 - leftFrontier)) = 122 := by
    have live3 : supportedSplitFrontiers 15 4 3 88 = {48, 49, 50, 51, 52} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {48, 49, 50, 51, 52},
          frontierCoeff 15 4 leftFrontier *
            frontierCoeff 15 3 (88 - leftFrontier)) =
          ∑ leftFrontier ∈ {48, 49, 50, 51, 52},
            if leftFrontier = 48 then 38 else if leftFrontier = 49 then 26 else if leftFrontier = 50 then 28 else if leftFrontier = 51 then 24 else if leftFrontier = 52 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_3_36, certificate_15_3_37, certificate_15_3_38, certificate_15_3_39, certificate_15_3_40, certificate_15_4_48,
            certificate_15_4_49, certificate_15_4_50, certificate_15_4_51, certificate_15_4_52] <;> simp
      _ = 122 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 5 2 88,
        frontierCoeff 15 5 leftFrontier *
          frontierCoeff 15 2 (88 - leftFrontier)) = 80 := by
    have live4 : supportedSplitFrontiers 15 5 2 88 = {60, 61, 62, 63} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {60, 61, 62, 63},
          frontierCoeff 15 5 leftFrontier *
            frontierCoeff 15 2 (88 - leftFrontier)) =
          ∑ leftFrontier ∈ {60, 61, 62, 63},
            if leftFrontier = 60 then 38 else if leftFrontier = 61 then 28 else if leftFrontier = 62 then 10 else if leftFrontier = 63 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_2_25, certificate_15_2_26, certificate_15_2_27, certificate_15_2_28, certificate_15_5_60, certificate_15_5_61,
            certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 80 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 6 1 88,
        frontierCoeff 15 6 leftFrontier *
          frontierCoeff 15 1 (88 - leftFrontier)) = 22 := by
    have live5 : supportedSplitFrontiers 15 6 1 88 = {73, 74} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {73, 74},
          frontierCoeff 15 6 leftFrontier *
            frontierCoeff 15 1 (88 - leftFrontier)) =
          ∑ leftFrontier ∈ {73, 74},
            if leftFrontier = 73 then 22 else if leftFrontier = 74 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_1_14, certificate_15_1_15, certificate_15_6_73, certificate_15_6_74] <;> simp
      _ = 22 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (7 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (7 - (offset + 1)) 88,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (7 - (offset + 1))
              (88 - leftFrontier)) = 448 := by
    have offsets : Finset.range (7 - 1) = {0, 1, 2, 3, 4, 5} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (7 - (offset + 1)) 88,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (7 - (offset + 1))
                (88 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5},
            if offset = 0 then 22 else if offset = 1 then 80 else if offset = 2 then 122 else if offset = 3 then 122 else if offset = 4 then 80 else if offset = 5 then 22 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5] <;> simp
      _ = 448 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_15_7_87] <;> simp

end AspisV6CompactFrontierTailCertificate
