import AspisFormal.V6CompactFrontierTailCertificate.Depth16

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence

/-! ## Depth 17, chunk 736
Cells 805 through 805;
recurrence workload 2814. -/

theorem certificate_17_15_200 :
    frontierCoeff 17 15 200 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

end AspisV6CompactFrontierTailCertificate
