import AspisFormal.V6CompactFrontierTailCertificate.Depth16
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 17, chunk 134
Cells 142 through 142;
recurrence workload 2064. -/

theorem certificate_17_13_171 :
    frontierCoeff 17 13 171 = 868 := by
  have zero_16_13_170 :
      frontierCoeff 16 13 170 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 1 12 171,
        frontierCoeff 16 1 leftFrontier *
          frontierCoeff 16 12 (171 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 16 1 12 171 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_12]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 2 11 171,
        frontierCoeff 16 2 leftFrontier *
          frontierCoeff 16 11 (171 - leftFrontier)) = 0 := by
    have live1 : supportedSplitFrontiers 16 2 11 171 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_2]
      ext value
      simp <;> omega
    rw [live1]
    simp
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 3 10 171,
        frontierCoeff 16 3 leftFrontier *
          frontierCoeff 16 10 (171 - leftFrontier)) = 0 := by
    have live2 : supportedSplitFrontiers 16 3 10 171 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_3]
      ext value
      simp <;> omega
    rw [live2]
    simp
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 4 9 171,
        frontierCoeff 16 4 leftFrontier *
          frontierCoeff 16 9 (171 - leftFrontier)) = 8 := by
    have live3 : supportedSplitFrontiers 16 4 9 171 = {56} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_4, support_16_9]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {56},
          frontierCoeff 16 4 leftFrontier *
            frontierCoeff 16 9 (171 - leftFrontier)) =
          ∑ leftFrontier ∈ {56},
            if leftFrontier = 56 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_4_56, certificate_16_9_115] <;> simp
      _ = 8 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 5 8 171,
        frontierCoeff 16 5 leftFrontier *
          frontierCoeff 16 8 (171 - leftFrontier)) = 122 := by
    have live4 : supportedSplitFrontiers 16 5 8 171 = {67, 68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_5, support_16_8]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {67, 68},
          frontierCoeff 16 5 leftFrontier *
            frontierCoeff 16 8 (171 - leftFrontier)) =
          ∑ leftFrontier ∈ {67, 68},
            if leftFrontier = 67 then 10 else if leftFrontier = 68 then 112 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_16_5_67, certificate_16_5_68, certificate_16_8_103, certificate_16_8_104] <;> simp
      _ = 122 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 6 7 171,
        frontierCoeff 16 6 leftFrontier *
          frontierCoeff 16 7 (171 - leftFrontier)) = 304 := by
    have live5 : supportedSplitFrontiers 16 6 7 171 = {79, 80} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_6, support_16_7]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {79, 80},
          frontierCoeff 16 6 leftFrontier *
            frontierCoeff 16 7 (171 - leftFrontier)) =
          ∑ leftFrontier ∈ {79, 80},
            if leftFrontier = 79 then 88 else if leftFrontier = 80 then 216 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_16_6_79, certificate_16_6_80, certificate_16_7_91, certificate_16_7_92] <;> simp
      _ = 304 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 7 6 171,
        frontierCoeff 16 7 leftFrontier *
          frontierCoeff 16 6 (171 - leftFrontier)) = 304 := by
    have live6 : supportedSplitFrontiers 16 7 6 171 = {91, 92} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_6, support_16_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {91, 92},
          frontierCoeff 16 7 leftFrontier *
            frontierCoeff 16 6 (171 - leftFrontier)) =
          ∑ leftFrontier ∈ {91, 92},
            if leftFrontier = 91 then 216 else if leftFrontier = 92 then 88 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_16_6_79, certificate_16_6_80, certificate_16_7_91, certificate_16_7_92] <;> simp
      _ = 304 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 8 5 171,
        frontierCoeff 16 8 leftFrontier *
          frontierCoeff 16 5 (171 - leftFrontier)) = 122 := by
    have live7 : supportedSplitFrontiers 16 8 5 171 = {103, 104} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_5, support_16_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {103, 104},
          frontierCoeff 16 8 leftFrontier *
            frontierCoeff 16 5 (171 - leftFrontier)) =
          ∑ leftFrontier ∈ {103, 104},
            if leftFrontier = 103 then 112 else if leftFrontier = 104 then 10 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_16_5_67, certificate_16_5_68, certificate_16_8_103, certificate_16_8_104] <;> simp
      _ = 122 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 9 4 171,
        frontierCoeff 16 9 leftFrontier *
          frontierCoeff 16 4 (171 - leftFrontier)) = 8 := by
    have live8 : supportedSplitFrontiers 16 9 4 171 = {115} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_4, support_16_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {115},
          frontierCoeff 16 9 leftFrontier *
            frontierCoeff 16 4 (171 - leftFrontier)) =
          ∑ leftFrontier ∈ {115},
            if leftFrontier = 115 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_4_56, certificate_16_9_115] <;> simp
      _ = 8 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 10 3 171,
        frontierCoeff 16 10 leftFrontier *
          frontierCoeff 16 3 (171 - leftFrontier)) = 0 := by
    have live9 : supportedSplitFrontiers 16 10 3 171 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_3]
      ext value
      simp <;> omega
    rw [live9]
    simp
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 11 2 171,
        frontierCoeff 16 11 leftFrontier *
          frontierCoeff 16 2 (171 - leftFrontier)) = 0 := by
    have live10 : supportedSplitFrontiers 16 11 2 171 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_2]
      ext value
      simp <;> omega
    rw [live10]
    simp
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 12 1 171,
        frontierCoeff 16 12 leftFrontier *
          frontierCoeff 16 1 (171 - leftFrontier)) = 0 := by
    have live11 : supportedSplitFrontiers 16 12 1 171 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_12]
      ext value
      simp <;> omega
    rw [live11]
    simp
  have outer :
      (∑ offset ∈ Finset.range (13 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
            (13 - (offset + 1)) 171,
          frontierCoeff 16 (offset + 1) leftFrontier *
            frontierCoeff 16 (13 - (offset + 1))
              (171 - leftFrontier)) = 868 := by
    have offsets : Finset.range (13 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
          ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
              (13 - (offset + 1)) 171,
            frontierCoeff 16 (offset + 1) leftFrontier *
              frontierCoeff 16 (13 - (offset + 1))
                (171 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
            if offset = 0 then 0 else if offset = 1 then 0 else if offset = 2 then 0 else if offset = 3 then 8 else if offset = 4 then 122 else if offset = 5 then 304 else if offset = 6 then 304 else if offset = 7 then 122 else if offset = 8 then 8 else if offset = 9 then 0 else if offset = 10 then 0 else if offset = 11 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11] <;> simp
      _ = 868 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_16_13_170] <;> simp

end AspisV6CompactFrontierTailCertificate
