import AspisFormal.V6CompactFrontierTailCertificate.Depth16
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 17, chunk 128
Cells 136 through 136;
recurrence workload 1992. -/

theorem certificate_17_13_165 :
    frontierCoeff 17 13 165 = 1024248 := by
  have zero_16_13_164 :
      frontierCoeff 16 13 164 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 1 12 165,
        frontierCoeff 16 1 leftFrontier *
          frontierCoeff 16 12 (165 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 16 1 12 165 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_12]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 2 11 165,
        frontierCoeff 16 2 leftFrontier *
          frontierCoeff 16 11 (165 - leftFrontier)) = 2480 := by
    have live1 : supportedSplitFrontiers 16 2 11 165 = {28, 29, 30} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {28, 29, 30},
          frontierCoeff 16 2 leftFrontier *
            frontierCoeff 16 11 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {28, 29, 30},
            if leftFrontier = 28 then 56 else if leftFrontier = 29 then 420 else if leftFrontier = 30 then 2004 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_16_11_135, certificate_16_11_136, certificate_16_11_137, certificate_16_2_28, certificate_16_2_29, certificate_16_2_30] <;> simp
      _ = 2480 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 3 10 165,
        frontierCoeff 16 3 leftFrontier *
          frontierCoeff 16 10 (165 - leftFrontier)) = 24856 := by
    have live2 : supportedSplitFrontiers 16 3 10 165 = {39, 40, 41, 42, 43} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {39, 40, 41, 42, 43},
          frontierCoeff 16 3 leftFrontier *
            frontierCoeff 16 10 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {39, 40, 41, 42, 43},
            if leftFrontier = 39 then 168 else if leftFrontier = 40 then 848 else if leftFrontier = 41 then 3784 else if leftFrontier = 42 then 5596 else if leftFrontier = 43 then 14460 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_10_122, certificate_16_10_123, certificate_16_10_124, certificate_16_10_125, certificate_16_10_126, certificate_16_3_39,
            certificate_16_3_40, certificate_16_3_41, certificate_16_3_42, certificate_16_3_43] <;> simp
      _ = 24856 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 4 9 165,
        frontierCoeff 16 4 leftFrontier *
          frontierCoeff 16 9 (165 - leftFrontier)) = 85046 := by
    have live3 : supportedSplitFrontiers 16 4 9 165 = {50, 51, 52, 53, 54, 55, 56} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_4, support_16_9]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {50, 51, 52, 53, 54, 55, 56},
          frontierCoeff 16 4 leftFrontier *
            frontierCoeff 16 9 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {50, 51, 52, 53, 54, 55, 56},
            if leftFrontier = 50 then 256 else if leftFrontier = 51 then 2300 else if leftFrontier = 52 then 6688 else if leftFrontier = 53 then 14248 else if leftFrontier = 54 then 17654 else if leftFrontier = 55 then 33216 else if leftFrontier = 56 then 10684 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_4_50, certificate_16_4_51, certificate_16_4_52, certificate_16_4_53, certificate_16_4_54, certificate_16_4_55,
            certificate_16_4_56, certificate_16_9_109, certificate_16_9_110, certificate_16_9_111, certificate_16_9_112, certificate_16_9_113,
            certificate_16_9_114, certificate_16_9_115] <;> simp
      _ = 85046 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 5 8 165,
        frontierCoeff 16 5 leftFrontier *
          frontierCoeff 16 8 (165 - leftFrontier)) = 168822 := by
    have live4 : supportedSplitFrontiers 16 5 8 165 = {61, 62, 63, 64, 65, 66, 67, 68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_5, support_16_8]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {61, 62, 63, 64, 65, 66, 67, 68},
          frontierCoeff 16 5 leftFrontier *
            frontierCoeff 16 8 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {61, 62, 63, 64, 65, 66, 67, 68},
            if leftFrontier = 61 then 182 else if leftFrontier = 62 then 3976 else if leftFrontier = 63 then 11328 else if leftFrontier = 64 then 23100 else if leftFrontier = 65 then 30210 else if leftFrontier = 66 then 47040 else if leftFrontier = 67 then 31070 else if leftFrontier = 68 then 21916 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_5_61, certificate_16_5_62, certificate_16_5_63, certificate_16_5_64, certificate_16_5_65, certificate_16_5_66,
            certificate_16_5_67, certificate_16_5_68, certificate_16_8_100, certificate_16_8_101, certificate_16_8_102, certificate_16_8_103,
            certificate_16_8_104, certificate_16_8_97, certificate_16_8_98, certificate_16_8_99] <;> simp
      _ = 168822 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 6 7 165,
        frontierCoeff 16 6 leftFrontier *
          frontierCoeff 16 7 (165 - leftFrontier)) = 230920 := by
    have live5 : supportedSplitFrontiers 16 6 7 165 = {73, 74, 75, 76, 77, 78, 79, 80} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_6, support_16_7]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {73, 74, 75, 76, 77, 78, 79, 80},
          frontierCoeff 16 6 leftFrontier *
            frontierCoeff 16 7 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {73, 74, 75, 76, 77, 78, 79, 80},
            if leftFrontier = 73 then 2800 else if leftFrontier = 74 then 17280 else if leftFrontier = 75 then 26752 else if leftFrontier = 76 then 47328 else if leftFrontier = 77 then 47488 else if leftFrontier = 78 then 46144 else if leftFrontier = 79 then 29832 else if leftFrontier = 80 then 13296 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_6_73, certificate_16_6_74, certificate_16_6_75, certificate_16_6_76, certificate_16_6_77, certificate_16_6_78,
            certificate_16_6_79, certificate_16_6_80, certificate_16_7_85, certificate_16_7_86, certificate_16_7_87, certificate_16_7_88,
            certificate_16_7_89, certificate_16_7_90, certificate_16_7_91, certificate_16_7_92] <;> simp
      _ = 230920 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 7 6 165,
        frontierCoeff 16 7 leftFrontier *
          frontierCoeff 16 6 (165 - leftFrontier)) = 230920 := by
    have live6 : supportedSplitFrontiers 16 7 6 165 = {85, 86, 87, 88, 89, 90, 91, 92} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_6, support_16_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {85, 86, 87, 88, 89, 90, 91, 92},
          frontierCoeff 16 7 leftFrontier *
            frontierCoeff 16 6 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {85, 86, 87, 88, 89, 90, 91, 92},
            if leftFrontier = 85 then 13296 else if leftFrontier = 86 then 29832 else if leftFrontier = 87 then 46144 else if leftFrontier = 88 then 47488 else if leftFrontier = 89 then 47328 else if leftFrontier = 90 then 26752 else if leftFrontier = 91 then 17280 else if leftFrontier = 92 then 2800 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_6_73, certificate_16_6_74, certificate_16_6_75, certificate_16_6_76, certificate_16_6_77, certificate_16_6_78,
            certificate_16_6_79, certificate_16_6_80, certificate_16_7_85, certificate_16_7_86, certificate_16_7_87, certificate_16_7_88,
            certificate_16_7_89, certificate_16_7_90, certificate_16_7_91, certificate_16_7_92] <;> simp
      _ = 230920 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 8 5 165,
        frontierCoeff 16 8 leftFrontier *
          frontierCoeff 16 5 (165 - leftFrontier)) = 168822 := by
    have live7 : supportedSplitFrontiers 16 8 5 165 = {97, 98, 99, 100, 101, 102, 103, 104} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_5, support_16_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {97, 98, 99, 100, 101, 102, 103, 104},
          frontierCoeff 16 8 leftFrontier *
            frontierCoeff 16 5 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {97, 98, 99, 100, 101, 102, 103, 104},
            if leftFrontier = 97 then 21916 else if leftFrontier = 98 then 31070 else if leftFrontier = 99 then 47040 else if leftFrontier = 100 then 30210 else if leftFrontier = 101 then 23100 else if leftFrontier = 102 then 11328 else if leftFrontier = 103 then 3976 else if leftFrontier = 104 then 182 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_5_61, certificate_16_5_62, certificate_16_5_63, certificate_16_5_64, certificate_16_5_65, certificate_16_5_66,
            certificate_16_5_67, certificate_16_5_68, certificate_16_8_100, certificate_16_8_101, certificate_16_8_102, certificate_16_8_103,
            certificate_16_8_104, certificate_16_8_97, certificate_16_8_98, certificate_16_8_99] <;> simp
      _ = 168822 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 9 4 165,
        frontierCoeff 16 9 leftFrontier *
          frontierCoeff 16 4 (165 - leftFrontier)) = 85046 := by
    have live8 : supportedSplitFrontiers 16 9 4 165 = {109, 110, 111, 112, 113, 114, 115} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_4, support_16_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {109, 110, 111, 112, 113, 114, 115},
          frontierCoeff 16 9 leftFrontier *
            frontierCoeff 16 4 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {109, 110, 111, 112, 113, 114, 115},
            if leftFrontier = 109 then 10684 else if leftFrontier = 110 then 33216 else if leftFrontier = 111 then 17654 else if leftFrontier = 112 then 14248 else if leftFrontier = 113 then 6688 else if leftFrontier = 114 then 2300 else if leftFrontier = 115 then 256 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_4_50, certificate_16_4_51, certificate_16_4_52, certificate_16_4_53, certificate_16_4_54, certificate_16_4_55,
            certificate_16_4_56, certificate_16_9_109, certificate_16_9_110, certificate_16_9_111, certificate_16_9_112, certificate_16_9_113,
            certificate_16_9_114, certificate_16_9_115] <;> simp
      _ = 85046 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 10 3 165,
        frontierCoeff 16 10 leftFrontier *
          frontierCoeff 16 3 (165 - leftFrontier)) = 24856 := by
    have live9 : supportedSplitFrontiers 16 10 3 165 = {122, 123, 124, 125, 126} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_3]
      ext value
      simp <;> omega
    rw [live9]
    calc
      (∑ leftFrontier ∈ {122, 123, 124, 125, 126},
          frontierCoeff 16 10 leftFrontier *
            frontierCoeff 16 3 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {122, 123, 124, 125, 126},
            if leftFrontier = 122 then 14460 else if leftFrontier = 123 then 5596 else if leftFrontier = 124 then 3784 else if leftFrontier = 125 then 848 else if leftFrontier = 126 then 168 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_10_122, certificate_16_10_123, certificate_16_10_124, certificate_16_10_125, certificate_16_10_126, certificate_16_3_39,
            certificate_16_3_40, certificate_16_3_41, certificate_16_3_42, certificate_16_3_43] <;> simp
      _ = 24856 := by norm_num
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 11 2 165,
        frontierCoeff 16 11 leftFrontier *
          frontierCoeff 16 2 (165 - leftFrontier)) = 2480 := by
    have live10 : supportedSplitFrontiers 16 11 2 165 = {135, 136, 137} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_2]
      ext value
      simp <;> omega
    rw [live10]
    calc
      (∑ leftFrontier ∈ {135, 136, 137},
          frontierCoeff 16 11 leftFrontier *
            frontierCoeff 16 2 (165 - leftFrontier)) =
          ∑ leftFrontier ∈ {135, 136, 137},
            if leftFrontier = 135 then 2004 else if leftFrontier = 136 then 420 else if leftFrontier = 137 then 56 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_16_11_135, certificate_16_11_136, certificate_16_11_137, certificate_16_2_28, certificate_16_2_29, certificate_16_2_30] <;> simp
      _ = 2480 := by norm_num
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 12 1 165,
        frontierCoeff 16 12 leftFrontier *
          frontierCoeff 16 1 (165 - leftFrontier)) = 0 := by
    have live11 : supportedSplitFrontiers 16 12 1 165 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_12]
      ext value
      simp <;> omega
    rw [live11]
    simp
  have outer :
      (∑ offset ∈ Finset.range (13 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
            (13 - (offset + 1)) 165,
          frontierCoeff 16 (offset + 1) leftFrontier *
            frontierCoeff 16 (13 - (offset + 1))
              (165 - leftFrontier)) = 1024248 := by
    have offsets : Finset.range (13 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
          ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
              (13 - (offset + 1)) 165,
            frontierCoeff 16 (offset + 1) leftFrontier *
              frontierCoeff 16 (13 - (offset + 1))
                (165 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
            if offset = 0 then 0 else if offset = 1 then 2480 else if offset = 2 then 24856 else if offset = 3 then 85046 else if offset = 4 then 168822 else if offset = 5 then 230920 else if offset = 6 then 230920 else if offset = 7 then 168822 else if offset = 8 then 85046 else if offset = 9 then 24856 else if offset = 10 then 2480 else if offset = 11 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11] <;> simp
      _ = 1024248 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_16_13_164] <;> simp

end AspisV6CompactFrontierTailCertificate
