import AspisFormal.V6CompactFrontierTailCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 84
Cells 104 through 104;
recurrence workload 872. -/

theorem certificate_16_9_108 :
    frontierCoeff 16 9 108 = 19568 := by
  have zero_15_9_107 :
      frontierCoeff 15 9 107 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 8 108,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 8 (108 - leftFrontier)) = 350 := by
    have live0 : supportedSplitFrontiers 15 1 8 108 = {12, 13, 14, 15} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_8]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {12, 13, 14, 15},
          frontierCoeff 15 1 leftFrontier *
            frontierCoeff 15 8 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {12, 13, 14, 15},
            if leftFrontier = 12 then 0 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 0 else if leftFrontier = 15 then 350 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_1_12, certificate_15_1_13, certificate_15_1_14, certificate_15_1_15, certificate_15_8_93, certificate_15_8_94,
            certificate_15_8_95, certificate_15_8_96] <;> simp
      _ = 350 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 7 108,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 7 (108 - leftFrontier)) = 1632 := by
    have live1 : supportedSplitFrontiers 15 2 7 108 = {23, 24, 25, 26, 27, 28} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_7]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {23, 24, 25, 26, 27, 28},
          frontierCoeff 15 2 leftFrontier *
            frontierCoeff 15 7 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {23, 24, 25, 26, 27, 28},
            if leftFrontier = 23 then 4 else if leftFrontier = 24 then 36 else if leftFrontier = 25 then 88 else if leftFrontier = 26 then 232 else if leftFrontier = 27 then 448 else if leftFrontier = 28 then 824 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_2_23, certificate_15_2_24, certificate_15_2_25, certificate_15_2_26, certificate_15_2_27, certificate_15_2_28,
            certificate_15_7_80, certificate_15_7_81, certificate_15_7_82, certificate_15_7_83, certificate_15_7_84, certificate_15_7_85] <;> simp
      _ = 1632 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 6 108,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 6 (108 - leftFrontier)) = 3324 := by
    have live2 : supportedSplitFrontiers 15 3 6 108 = {34, 35, 36, 37, 38, 39, 40} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_6]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {34, 35, 36, 37, 38, 39, 40},
          frontierCoeff 15 3 leftFrontier *
            frontierCoeff 15 6 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {34, 35, 36, 37, 38, 39, 40},
            if leftFrontier = 34 then 48 else if leftFrontier = 35 then 132 else if leftFrontier = 36 then 336 else if leftFrontier = 37 then 424 else if leftFrontier = 38 then 816 else if leftFrontier = 39 then 608 else if leftFrontier = 40 then 960 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_3_34, certificate_15_3_35, certificate_15_3_36, certificate_15_3_37, certificate_15_3_38, certificate_15_3_39,
            certificate_15_3_40, certificate_15_6_68, certificate_15_6_69, certificate_15_6_70, certificate_15_6_71, certificate_15_6_72,
            certificate_15_6_73, certificate_15_6_74] <;> simp
      _ = 3324 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 4 5 108,
        frontierCoeff 15 4 leftFrontier *
          frontierCoeff 15 5 (108 - leftFrontier)) = 4478 := by
    have live3 : supportedSplitFrontiers 15 4 5 108 = {45, 46, 47, 48, 49, 50, 51, 52} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4, support_15_5]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {45, 46, 47, 48, 49, 50, 51, 52},
          frontierCoeff 15 4 leftFrontier *
            frontierCoeff 15 5 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {45, 46, 47, 48, 49, 50, 51, 52},
            if leftFrontier = 45 then 172 else if leftFrontier = 46 then 320 else if leftFrontier = 47 then 700 else if leftFrontier = 48 then 722 else if leftFrontier = 49 then 858 else if leftFrontier = 50 then 672 else if leftFrontier = 51 then 852 else if leftFrontier = 52 then 182 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_4_45, certificate_15_4_46, certificate_15_4_47, certificate_15_4_48, certificate_15_4_49, certificate_15_4_50,
            certificate_15_4_51, certificate_15_4_52, certificate_15_5_56, certificate_15_5_57, certificate_15_5_58, certificate_15_5_59,
            certificate_15_5_60, certificate_15_5_61, certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 4478 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 5 4 108,
        frontierCoeff 15 5 leftFrontier *
          frontierCoeff 15 4 (108 - leftFrontier)) = 4478 := by
    have live4 : supportedSplitFrontiers 15 5 4 108 = {56, 57, 58, 59, 60, 61, 62, 63} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4, support_15_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {56, 57, 58, 59, 60, 61, 62, 63},
          frontierCoeff 15 5 leftFrontier *
            frontierCoeff 15 4 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {56, 57, 58, 59, 60, 61, 62, 63},
            if leftFrontier = 56 then 182 else if leftFrontier = 57 then 852 else if leftFrontier = 58 then 672 else if leftFrontier = 59 then 858 else if leftFrontier = 60 then 722 else if leftFrontier = 61 then 700 else if leftFrontier = 62 then 320 else if leftFrontier = 63 then 172 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_4_45, certificate_15_4_46, certificate_15_4_47, certificate_15_4_48, certificate_15_4_49, certificate_15_4_50,
            certificate_15_4_51, certificate_15_4_52, certificate_15_5_56, certificate_15_5_57, certificate_15_5_58, certificate_15_5_59,
            certificate_15_5_60, certificate_15_5_61, certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 4478 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 6 3 108,
        frontierCoeff 15 6 leftFrontier *
          frontierCoeff 15 3 (108 - leftFrontier)) = 3324 := by
    have live5 : supportedSplitFrontiers 15 6 3 108 = {68, 69, 70, 71, 72, 73, 74} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {68, 69, 70, 71, 72, 73, 74},
          frontierCoeff 15 6 leftFrontier *
            frontierCoeff 15 3 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {68, 69, 70, 71, 72, 73, 74},
            if leftFrontier = 68 then 960 else if leftFrontier = 69 then 608 else if leftFrontier = 70 then 816 else if leftFrontier = 71 then 424 else if leftFrontier = 72 then 336 else if leftFrontier = 73 then 132 else if leftFrontier = 74 then 48 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_3_34, certificate_15_3_35, certificate_15_3_36, certificate_15_3_37, certificate_15_3_38, certificate_15_3_39,
            certificate_15_3_40, certificate_15_6_68, certificate_15_6_69, certificate_15_6_70, certificate_15_6_71, certificate_15_6_72,
            certificate_15_6_73, certificate_15_6_74] <;> simp
      _ = 3324 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 7 2 108,
        frontierCoeff 15 7 leftFrontier *
          frontierCoeff 15 2 (108 - leftFrontier)) = 1632 := by
    have live6 : supportedSplitFrontiers 15 7 2 108 = {80, 81, 82, 83, 84, 85} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {80, 81, 82, 83, 84, 85},
          frontierCoeff 15 7 leftFrontier *
            frontierCoeff 15 2 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {80, 81, 82, 83, 84, 85},
            if leftFrontier = 80 then 824 else if leftFrontier = 81 then 448 else if leftFrontier = 82 then 232 else if leftFrontier = 83 then 88 else if leftFrontier = 84 then 36 else if leftFrontier = 85 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_2_23, certificate_15_2_24, certificate_15_2_25, certificate_15_2_26, certificate_15_2_27, certificate_15_2_28,
            certificate_15_7_80, certificate_15_7_81, certificate_15_7_82, certificate_15_7_83, certificate_15_7_84, certificate_15_7_85] <;> simp
      _ = 1632 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 8 1 108,
        frontierCoeff 15 8 leftFrontier *
          frontierCoeff 15 1 (108 - leftFrontier)) = 350 := by
    have live7 : supportedSplitFrontiers 15 8 1 108 = {93, 94, 95, 96} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {93, 94, 95, 96},
          frontierCoeff 15 8 leftFrontier *
            frontierCoeff 15 1 (108 - leftFrontier)) =
          ∑ leftFrontier ∈ {93, 94, 95, 96},
            if leftFrontier = 93 then 350 else if leftFrontier = 94 then 0 else if leftFrontier = 95 then 0 else if leftFrontier = 96 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_15_1_12, certificate_15_1_13, certificate_15_1_14, certificate_15_1_15, certificate_15_8_93, certificate_15_8_94,
            certificate_15_8_95, certificate_15_8_96] <;> simp
      _ = 350 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (9 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (9 - (offset + 1)) 108,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (9 - (offset + 1))
              (108 - leftFrontier)) = 19568 := by
    have offsets : Finset.range (9 - 1) = {0, 1, 2, 3, 4, 5, 6, 7} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (9 - (offset + 1)) 108,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (9 - (offset + 1))
                (108 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7},
            if offset = 0 then 350 else if offset = 1 then 1632 else if offset = 2 then 3324 else if offset = 3 then 4478 else if offset = 4 then 4478 else if offset = 5 then 3324 else if offset = 6 then 1632 else if offset = 7 then 350 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7] <;> simp
      _ = 19568 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_15_9_107] <;> simp

end AspisV6CompactFrontierTailCertificate
