import AspisFormal.V6CompactFrontierTailCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 97
Cells 117 through 117;
recurrence workload 1134. -/

theorem certificate_16_10_125 :
    frontierCoeff 16 10 125 = 212 := by
  have zero_15_10_124 :
      frontierCoeff 15 10 124 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 9 125,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 9 (125 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 15 1 9 125 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_9]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 8 125,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 8 (125 - leftFrontier)) = 0 := by
    have live1 : supportedSplitFrontiers 15 2 8 125 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_8]
      ext value
      simp <;> omega
    rw [live1]
    simp
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 7 125,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 7 (125 - leftFrontier)) = 8 := by
    have live2 : supportedSplitFrontiers 15 3 7 125 = {40} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_7]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {40},
          frontierCoeff 15 3 leftFrontier *
            frontierCoeff 15 7 (125 - leftFrontier)) =
          ∑ leftFrontier ∈ {40},
            if leftFrontier = 40 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_15_3_40, certificate_15_7_85] <;> simp
      _ = 8 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 4 6 125,
        frontierCoeff 15 4 leftFrontier *
          frontierCoeff 15 6 (125 - leftFrontier)) = 58 := by
    have live3 : supportedSplitFrontiers 15 4 6 125 = {51, 52} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4, support_15_6]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {51, 52},
          frontierCoeff 15 4 leftFrontier *
            frontierCoeff 15 6 (125 - leftFrontier)) =
          ∑ leftFrontier ∈ {51, 52},
            if leftFrontier = 51 then 36 else if leftFrontier = 52 then 22 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_4_51, certificate_15_4_52, certificate_15_6_73, certificate_15_6_74] <;> simp
      _ = 58 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 5 5 125,
        frontierCoeff 15 5 leftFrontier *
          frontierCoeff 15 5 (125 - leftFrontier)) = 80 := by
    have live4 : supportedSplitFrontiers 15 5 5 125 = {62, 63} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {62, 63},
          frontierCoeff 15 5 leftFrontier *
            frontierCoeff 15 5 (125 - leftFrontier)) =
          ∑ leftFrontier ∈ {62, 63},
            if leftFrontier = 62 then 40 else if leftFrontier = 63 then 40 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 80 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 6 4 125,
        frontierCoeff 15 6 leftFrontier *
          frontierCoeff 15 4 (125 - leftFrontier)) = 58 := by
    have live5 : supportedSplitFrontiers 15 6 4 125 = {73, 74} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4, support_15_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {73, 74},
          frontierCoeff 15 6 leftFrontier *
            frontierCoeff 15 4 (125 - leftFrontier)) =
          ∑ leftFrontier ∈ {73, 74},
            if leftFrontier = 73 then 22 else if leftFrontier = 74 then 36 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_4_51, certificate_15_4_52, certificate_15_6_73, certificate_15_6_74] <;> simp
      _ = 58 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 7 3 125,
        frontierCoeff 15 7 leftFrontier *
          frontierCoeff 15 3 (125 - leftFrontier)) = 8 := by
    have live6 : supportedSplitFrontiers 15 7 3 125 = {85} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {85},
          frontierCoeff 15 7 leftFrontier *
            frontierCoeff 15 3 (125 - leftFrontier)) =
          ∑ leftFrontier ∈ {85},
            if leftFrontier = 85 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_15_3_40, certificate_15_7_85] <;> simp
      _ = 8 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 8 2 125,
        frontierCoeff 15 8 leftFrontier *
          frontierCoeff 15 2 (125 - leftFrontier)) = 0 := by
    have live7 : supportedSplitFrontiers 15 8 2 125 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_8]
      ext value
      simp <;> omega
    rw [live7]
    simp
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 9 1 125,
        frontierCoeff 15 9 leftFrontier *
          frontierCoeff 15 1 (125 - leftFrontier)) = 0 := by
    have live8 : supportedSplitFrontiers 15 9 1 125 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_9]
      ext value
      simp <;> omega
    rw [live8]
    simp
  have outer :
      (∑ offset ∈ Finset.range (10 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (10 - (offset + 1)) 125,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (10 - (offset + 1))
              (125 - leftFrontier)) = 212 := by
    have offsets : Finset.range (10 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (10 - (offset + 1)) 125,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (10 - (offset + 1))
                (125 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8},
            if offset = 0 then 0 else if offset = 1 then 0 else if offset = 2 then 8 else if offset = 3 then 58 else if offset = 4 then 80 else if offset = 5 then 58 else if offset = 6 then 8 else if offset = 7 then 0 else if offset = 8 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8] <;> simp
      _ = 212 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_15_10_124] <;> simp

end AspisV6CompactFrontierTailCertificate
