import AspisFormal.V6CompactFrontierTailCertificate.Depth10
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 11, chunk 1
Cells 18 through 22;
recurrence workload 95. -/

theorem certificate_11_2_16 :
    frontierCoeff 11 2 16 = 1 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 10 1 1 16,
        frontierCoeff 10 1 leftFrontier *
          frontierCoeff 10 1 (16 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 10 1 1 16 = {6, 7, 8, 9, 10} := by
      rw [supportedSplitFrontiers_eq_Icc, support_10_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {6, 7, 8, 9, 10},
          frontierCoeff 10 1 leftFrontier *
            frontierCoeff 10 1 (16 - leftFrontier)) =
          ∑ leftFrontier ∈ {6, 7, 8, 9, 10},
            if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_10_1_10, certificate_10_1_6, certificate_10_1_7, certificate_10_1_8, certificate_10_1_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
            (2 - (offset + 1)) 16,
          frontierCoeff 10 (offset + 1) leftFrontier *
            frontierCoeff 10 (2 - (offset + 1))
              (16 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
              (2 - (offset + 1)) 16,
            frontierCoeff 10 (offset + 1) leftFrontier *
              frontierCoeff 10 (2 - (offset + 1))
                (16 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_10_2_15] <;> simp

theorem certificate_11_2_17 :
    frontierCoeff 11 2 17 = 1 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 10 1 1 17,
        frontierCoeff 10 1 leftFrontier *
          frontierCoeff 10 1 (17 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 10 1 1 17 = {7, 8, 9, 10} := by
      rw [supportedSplitFrontiers_eq_Icc, support_10_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {7, 8, 9, 10},
          frontierCoeff 10 1 leftFrontier *
            frontierCoeff 10 1 (17 - leftFrontier)) =
          ∑ leftFrontier ∈ {7, 8, 9, 10},
            if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_10_1_10, certificate_10_1_7, certificate_10_1_8, certificate_10_1_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
            (2 - (offset + 1)) 17,
          frontierCoeff 10 (offset + 1) leftFrontier *
            frontierCoeff 10 (2 - (offset + 1))
              (17 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
              (2 - (offset + 1)) 17,
            frontierCoeff 10 (offset + 1) leftFrontier *
              frontierCoeff 10 (2 - (offset + 1))
                (17 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_10_2_16] <;> simp

theorem certificate_11_2_18 :
    frontierCoeff 11 2 18 = 1 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 10 1 1 18,
        frontierCoeff 10 1 leftFrontier *
          frontierCoeff 10 1 (18 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 10 1 1 18 = {8, 9, 10} := by
      rw [supportedSplitFrontiers_eq_Icc, support_10_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {8, 9, 10},
          frontierCoeff 10 1 leftFrontier *
            frontierCoeff 10 1 (18 - leftFrontier)) =
          ∑ leftFrontier ∈ {8, 9, 10},
            if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_10_1_10, certificate_10_1_8, certificate_10_1_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
            (2 - (offset + 1)) 18,
          frontierCoeff 10 (offset + 1) leftFrontier *
            frontierCoeff 10 (2 - (offset + 1))
              (18 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
              (2 - (offset + 1)) 18,
            frontierCoeff 10 (offset + 1) leftFrontier *
              frontierCoeff 10 (2 - (offset + 1))
                (18 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_10_2_17] <;> simp

theorem certificate_11_2_19 :
    frontierCoeff 11 2 19 = 1 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 10 1 1 19,
        frontierCoeff 10 1 leftFrontier *
          frontierCoeff 10 1 (19 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 10 1 1 19 = {9, 10} := by
      rw [supportedSplitFrontiers_eq_Icc, support_10_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {9, 10},
          frontierCoeff 10 1 leftFrontier *
            frontierCoeff 10 1 (19 - leftFrontier)) =
          ∑ leftFrontier ∈ {9, 10},
            if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_10_1_10, certificate_10_1_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
            (2 - (offset + 1)) 19,
          frontierCoeff 10 (offset + 1) leftFrontier *
            frontierCoeff 10 (2 - (offset + 1))
              (19 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
              (2 - (offset + 1)) 19,
            frontierCoeff 10 (offset + 1) leftFrontier *
              frontierCoeff 10 (2 - (offset + 1))
                (19 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_10_2_18] <;> simp

theorem certificate_11_2_20 :
    frontierCoeff 11 2 20 = 1 := by
  have zero_10_2_19 :
      frontierCoeff 10 2 19 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 10 1 1 20,
        frontierCoeff 10 1 leftFrontier *
          frontierCoeff 10 1 (20 - leftFrontier)) = 1 := by
    have live0 : supportedSplitFrontiers 10 1 1 20 = {10} := by
      rw [supportedSplitFrontiers_eq_Icc, support_10_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {10},
          frontierCoeff 10 1 leftFrontier *
            frontierCoeff 10 1 (20 - leftFrontier)) =
          ∑ leftFrontier ∈ {10},
            if leftFrontier = 10 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_10_1_10] <;> simp
      _ = 1 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
            (2 - (offset + 1)) 20,
          frontierCoeff 10 (offset + 1) leftFrontier *
            frontierCoeff 10 (2 - (offset + 1))
              (20 - leftFrontier)) = 1 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 10 (offset + 1)
              (2 - (offset + 1)) 20,
            frontierCoeff 10 (offset + 1) leftFrontier *
              frontierCoeff 10 (2 - (offset + 1))
                (20 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 1 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_10_2_19] <;> simp

end AspisV6CompactFrontierTailCertificate
