import AspisFormal.V6CompactFrontierTailCertificate.Depth08

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence

/-! ## Depth 9, chunk 111
Cells 167 through 167;
recurrence workload 497. -/

theorem certificate_9_8_70 :
    frontierCoeff 9 8 70 = 0 := by
  rw [frontierCoeff]
  norm_num [Finset.sum_range_succ,
    frontierCoeff_eq_zero_of_frontier_gt_mul]

end AspisV6CompactFrontierTailCertificate
