import AspisFormal.V6CompactFrontierTailCertificate.Depth17
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 18, chunk 3
Cells 3 through 3;
recurrence workload 3210. -/

theorem certificate_18_16_213 :
    frontierCoeff 18 16 213 = 146678756 := by
  have zero_17_16_212 :
      frontierCoeff 17 16 212 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 1 15 213,
        frontierCoeff 17 1 leftFrontier *
          frontierCoeff 17 15 (213 - leftFrontier)) = 8 := by
    have live0 : supportedSplitFrontiers 17 1 15 213 = {17} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_1, support_17_15]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {17},
          frontierCoeff 17 1 leftFrontier *
            frontierCoeff 17 15 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {17},
            if leftFrontier = 17 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_17_15_196, certificate_17_1_17] <;> simp
      _ = 8 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 2 14 213,
        frontierCoeff 17 2 leftFrontier *
          frontierCoeff 17 14 (213 - leftFrontier)) = 33268 := by
    have live1 : supportedSplitFrontiers 17 2 14 213 = {29, 30, 31, 32} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_14, support_17_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {29, 30, 31, 32},
          frontierCoeff 17 2 leftFrontier *
            frontierCoeff 17 14 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {29, 30, 31, 32},
            if leftFrontier = 29 then 28 else if leftFrontier = 30 then 732 else if leftFrontier = 31 then 5712 else if leftFrontier = 32 then 26796 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_14_181, certificate_17_14_182, certificate_17_14_183, certificate_17_14_184, certificate_17_2_29, certificate_17_2_30,
            certificate_17_2_31, certificate_17_2_32] <;> simp
      _ = 33268 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 3 13 213,
        frontierCoeff 17 3 leftFrontier *
          frontierCoeff 17 13 (213 - leftFrontier)) = 606240 := by
    have live2 : supportedSplitFrontiers 17 3 13 213 = {41, 42, 43, 44, 45, 46} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_13, support_17_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {41, 42, 43, 44, 45, 46},
          frontierCoeff 17 3 leftFrontier *
            frontierCoeff 17 13 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {41, 42, 43, 44, 45, 46},
            if leftFrontier = 41 then 336 else if leftFrontier = 42 then 5208 else if leftFrontier = 43 then 19712 else if leftFrontier = 44 then 81488 else if leftFrontier = 45 then 131608 else if leftFrontier = 46 then 367888 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_13_167, certificate_17_13_168, certificate_17_13_169, certificate_17_13_170, certificate_17_13_171, certificate_17_13_172,
            certificate_17_3_41, certificate_17_3_42, certificate_17_3_43, certificate_17_3_44, certificate_17_3_45, certificate_17_3_46] <;> simp
      _ = 606240 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 4 12 213,
        frontierCoeff 17 4 leftFrontier *
          frontierCoeff 17 12 (213 - leftFrontier)) = 3242090 := by
    have live3 : supportedSplitFrontiers 17 4 12 213 = {53, 54, 55, 56, 57, 58, 59, 60} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_12, support_17_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {53, 54, 55, 56, 57, 58, 59, 60},
          frontierCoeff 17 4 leftFrontier *
            frontierCoeff 17 12 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {53, 54, 55, 56, 57, 58, 59, 60},
            if leftFrontier = 53 then 3010 else if leftFrontier = 54 then 22400 else if leftFrontier = 55 then 85550 else if leftFrontier = 56 then 239514 else if leftFrontier = 57 then 477984 else if leftFrontier = 58 then 660114 else if leftFrontier = 59 then 1295856 else if leftFrontier = 60 then 457662 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_12_153, certificate_17_12_154, certificate_17_12_155, certificate_17_12_156, certificate_17_12_157, certificate_17_12_158,
            certificate_17_12_159, certificate_17_12_160, certificate_17_4_53, certificate_17_4_54, certificate_17_4_55, certificate_17_4_56,
            certificate_17_4_57, certificate_17_4_58, certificate_17_4_59, certificate_17_4_60] <;> simp
      _ = 3242090 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 5 11 213,
        frontierCoeff 17 5 leftFrontier *
          frontierCoeff 17 11 (213 - leftFrontier)) = 9406016 := by
    have live4 : supportedSplitFrontiers 17 5 11 213 = {65, 66, 67, 68, 69, 70, 71, 72, 73} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_11, support_17_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {65, 66, 67, 68, 69, 70, 71, 72, 73},
          frontierCoeff 17 5 leftFrontier *
            frontierCoeff 17 11 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {65, 66, 67, 68, 69, 70, 71, 72, 73},
            if leftFrontier = 65 then 14112 else if leftFrontier = 66 then 76440 else if leftFrontier = 67 then 284568 else if leftFrontier = 68 then 613632 else if leftFrontier = 69 then 1165296 else if leftFrontier = 70 then 1578976 else if leftFrontier = 71 then 2524704 else if leftFrontier = 72 then 1792960 else if leftFrontier = 73 then 1355328 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_11_140, certificate_17_11_141, certificate_17_11_142, certificate_17_11_143, certificate_17_11_144, certificate_17_11_145,
            certificate_17_11_146, certificate_17_11_147, certificate_17_11_148, certificate_17_5_65, certificate_17_5_66, certificate_17_5_67,
            certificate_17_5_68, certificate_17_5_69, certificate_17_5_70, certificate_17_5_71, certificate_17_5_72, certificate_17_5_73] <;> simp
      _ = 9406016 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 6 10 213,
        frontierCoeff 17 6 leftFrontier *
          frontierCoeff 17 10 (213 - leftFrontier)) = 18366572 := by
    have live5 : supportedSplitFrontiers 17 6 10 213 = {77, 78, 79, 80, 81, 82, 83, 84, 85, 86} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_10, support_17_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {77, 78, 79, 80, 81, 82, 83, 84, 85, 86},
          frontierCoeff 17 6 leftFrontier *
            frontierCoeff 17 10 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {77, 78, 79, 80, 81, 82, 83, 84, 85, 86},
            if leftFrontier = 77 then 38192 else if leftFrontier = 78 then 212424 else if leftFrontier = 79 then 662200 else if leftFrontier = 80 then 1343040 else if leftFrontier = 81 then 2197920 else if leftFrontier = 82 then 3288072 else if leftFrontier = 83 then 3489944 else if leftFrontier = 84 then 3501120 else if leftFrontier = 85 then 2479620 else if leftFrontier = 86 then 1154040 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_10_127, certificate_17_10_128, certificate_17_10_129, certificate_17_10_130, certificate_17_10_131, certificate_17_10_132,
            certificate_17_10_133, certificate_17_10_134, certificate_17_10_135, certificate_17_10_136, certificate_17_6_77, certificate_17_6_78,
            certificate_17_6_79, certificate_17_6_80, certificate_17_6_81, certificate_17_6_82, certificate_17_6_83, certificate_17_6_84,
            certificate_17_6_85, certificate_17_6_86] <;> simp
      _ = 18366572 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 7 9 213,
        frontierCoeff 17 7 leftFrontier *
          frontierCoeff 17 9 (213 - leftFrontier)) = 26661856 := by
    have live6 : supportedSplitFrontiers 17 7 9 213 = {89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_7, support_17_9]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99},
          frontierCoeff 17 7 leftFrontier *
            frontierCoeff 17 9 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99},
            if leftFrontier = 89 then 55072 else if leftFrontier = 90 then 447488 else if leftFrontier = 91 then 1150336 else if leftFrontier = 92 then 2428736 else if leftFrontier = 93 then 3419832 else if leftFrontier = 94 then 4561664 else if leftFrontier = 95 then 4786432 else if leftFrontier = 96 then 4539776 else if leftFrontier = 97 then 2937616 else if leftFrontier = 98 then 1987488 else if leftFrontier = 99 then 347416 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_7_89, certificate_17_7_90, certificate_17_7_91, certificate_17_7_92, certificate_17_7_93, certificate_17_7_94,
            certificate_17_7_95, certificate_17_7_96, certificate_17_7_97, certificate_17_7_98, certificate_17_7_99, certificate_17_9_114,
            certificate_17_9_115, certificate_17_9_116, certificate_17_9_117, certificate_17_9_118, certificate_17_9_119, certificate_17_9_120,
            certificate_17_9_121, certificate_17_9_122, certificate_17_9_123, certificate_17_9_124] <;> simp
      _ = 26661856 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 8 8 213,
        frontierCoeff 17 8 leftFrontier *
          frontierCoeff 17 8 (213 - leftFrontier)) = 30046656 := by
    have live7 : supportedSplitFrontiers 17 8 8 213 = {101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112},
          frontierCoeff 17 8 leftFrontier *
            frontierCoeff 17 8 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112},
            if leftFrontier = 101 then 31929 else if leftFrontier = 102 then 602476 else if leftFrontier = 103 then 1676308 else if leftFrontier = 104 then 3137050 else if leftFrontier = 105 then 4355805 else if leftFrontier = 106 then 5219760 else if leftFrontier = 107 then 5219760 else if leftFrontier = 108 then 4355805 else if leftFrontier = 109 then 3137050 else if leftFrontier = 110 then 1676308 else if leftFrontier = 111 then 602476 else if leftFrontier = 112 then 31929 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_8_101, certificate_17_8_102, certificate_17_8_103, certificate_17_8_104, certificate_17_8_105, certificate_17_8_106,
            certificate_17_8_107, certificate_17_8_108, certificate_17_8_109, certificate_17_8_110, certificate_17_8_111, certificate_17_8_112] <;> simp
      _ = 30046656 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 9 7 213,
        frontierCoeff 17 9 leftFrontier *
          frontierCoeff 17 7 (213 - leftFrontier)) = 26661856 := by
    have live8 : supportedSplitFrontiers 17 9 7 213 = {114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_7, support_17_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124},
          frontierCoeff 17 9 leftFrontier *
            frontierCoeff 17 7 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124},
            if leftFrontier = 114 then 347416 else if leftFrontier = 115 then 1987488 else if leftFrontier = 116 then 2937616 else if leftFrontier = 117 then 4539776 else if leftFrontier = 118 then 4786432 else if leftFrontier = 119 then 4561664 else if leftFrontier = 120 then 3419832 else if leftFrontier = 121 then 2428736 else if leftFrontier = 122 then 1150336 else if leftFrontier = 123 then 447488 else if leftFrontier = 124 then 55072 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_7_89, certificate_17_7_90, certificate_17_7_91, certificate_17_7_92, certificate_17_7_93, certificate_17_7_94,
            certificate_17_7_95, certificate_17_7_96, certificate_17_7_97, certificate_17_7_98, certificate_17_7_99, certificate_17_9_114,
            certificate_17_9_115, certificate_17_9_116, certificate_17_9_117, certificate_17_9_118, certificate_17_9_119, certificate_17_9_120,
            certificate_17_9_121, certificate_17_9_122, certificate_17_9_123, certificate_17_9_124] <;> simp
      _ = 26661856 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 10 6 213,
        frontierCoeff 17 10 leftFrontier *
          frontierCoeff 17 6 (213 - leftFrontier)) = 18366572 := by
    have live9 : supportedSplitFrontiers 17 10 6 213 = {127, 128, 129, 130, 131, 132, 133, 134, 135, 136} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_10, support_17_6]
      ext value
      simp <;> omega
    rw [live9]
    calc
      (∑ leftFrontier ∈ {127, 128, 129, 130, 131, 132, 133, 134, 135, 136},
          frontierCoeff 17 10 leftFrontier *
            frontierCoeff 17 6 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {127, 128, 129, 130, 131, 132, 133, 134, 135, 136},
            if leftFrontier = 127 then 1154040 else if leftFrontier = 128 then 2479620 else if leftFrontier = 129 then 3501120 else if leftFrontier = 130 then 3489944 else if leftFrontier = 131 then 3288072 else if leftFrontier = 132 then 2197920 else if leftFrontier = 133 then 1343040 else if leftFrontier = 134 then 662200 else if leftFrontier = 135 then 212424 else if leftFrontier = 136 then 38192 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_10_127, certificate_17_10_128, certificate_17_10_129, certificate_17_10_130, certificate_17_10_131, certificate_17_10_132,
            certificate_17_10_133, certificate_17_10_134, certificate_17_10_135, certificate_17_10_136, certificate_17_6_77, certificate_17_6_78,
            certificate_17_6_79, certificate_17_6_80, certificate_17_6_81, certificate_17_6_82, certificate_17_6_83, certificate_17_6_84,
            certificate_17_6_85, certificate_17_6_86] <;> simp
      _ = 18366572 := by norm_num
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 11 5 213,
        frontierCoeff 17 11 leftFrontier *
          frontierCoeff 17 5 (213 - leftFrontier)) = 9406016 := by
    have live10 : supportedSplitFrontiers 17 11 5 213 = {140, 141, 142, 143, 144, 145, 146, 147, 148} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_11, support_17_5]
      ext value
      simp <;> omega
    rw [live10]
    calc
      (∑ leftFrontier ∈ {140, 141, 142, 143, 144, 145, 146, 147, 148},
          frontierCoeff 17 11 leftFrontier *
            frontierCoeff 17 5 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {140, 141, 142, 143, 144, 145, 146, 147, 148},
            if leftFrontier = 140 then 1355328 else if leftFrontier = 141 then 1792960 else if leftFrontier = 142 then 2524704 else if leftFrontier = 143 then 1578976 else if leftFrontier = 144 then 1165296 else if leftFrontier = 145 then 613632 else if leftFrontier = 146 then 284568 else if leftFrontier = 147 then 76440 else if leftFrontier = 148 then 14112 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_11_140, certificate_17_11_141, certificate_17_11_142, certificate_17_11_143, certificate_17_11_144, certificate_17_11_145,
            certificate_17_11_146, certificate_17_11_147, certificate_17_11_148, certificate_17_5_65, certificate_17_5_66, certificate_17_5_67,
            certificate_17_5_68, certificate_17_5_69, certificate_17_5_70, certificate_17_5_71, certificate_17_5_72, certificate_17_5_73] <;> simp
      _ = 9406016 := by norm_num
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 12 4 213,
        frontierCoeff 17 12 leftFrontier *
          frontierCoeff 17 4 (213 - leftFrontier)) = 3242090 := by
    have live11 : supportedSplitFrontiers 17 12 4 213 = {153, 154, 155, 156, 157, 158, 159, 160} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_12, support_17_4]
      ext value
      simp <;> omega
    rw [live11]
    calc
      (∑ leftFrontier ∈ {153, 154, 155, 156, 157, 158, 159, 160},
          frontierCoeff 17 12 leftFrontier *
            frontierCoeff 17 4 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {153, 154, 155, 156, 157, 158, 159, 160},
            if leftFrontier = 153 then 457662 else if leftFrontier = 154 then 1295856 else if leftFrontier = 155 then 660114 else if leftFrontier = 156 then 477984 else if leftFrontier = 157 then 239514 else if leftFrontier = 158 then 85550 else if leftFrontier = 159 then 22400 else if leftFrontier = 160 then 3010 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_12_153, certificate_17_12_154, certificate_17_12_155, certificate_17_12_156, certificate_17_12_157, certificate_17_12_158,
            certificate_17_12_159, certificate_17_12_160, certificate_17_4_53, certificate_17_4_54, certificate_17_4_55, certificate_17_4_56,
            certificate_17_4_57, certificate_17_4_58, certificate_17_4_59, certificate_17_4_60] <;> simp
      _ = 3242090 := by norm_num
  have split12 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 13 3 213,
        frontierCoeff 17 13 leftFrontier *
          frontierCoeff 17 3 (213 - leftFrontier)) = 606240 := by
    have live12 : supportedSplitFrontiers 17 13 3 213 = {167, 168, 169, 170, 171, 172} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_13, support_17_3]
      ext value
      simp <;> omega
    rw [live12]
    calc
      (∑ leftFrontier ∈ {167, 168, 169, 170, 171, 172},
          frontierCoeff 17 13 leftFrontier *
            frontierCoeff 17 3 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {167, 168, 169, 170, 171, 172},
            if leftFrontier = 167 then 367888 else if leftFrontier = 168 then 131608 else if leftFrontier = 169 then 81488 else if leftFrontier = 170 then 19712 else if leftFrontier = 171 then 5208 else if leftFrontier = 172 then 336 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_13_167, certificate_17_13_168, certificate_17_13_169, certificate_17_13_170, certificate_17_13_171, certificate_17_13_172,
            certificate_17_3_41, certificate_17_3_42, certificate_17_3_43, certificate_17_3_44, certificate_17_3_45, certificate_17_3_46] <;> simp
      _ = 606240 := by norm_num
  have split13 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 14 2 213,
        frontierCoeff 17 14 leftFrontier *
          frontierCoeff 17 2 (213 - leftFrontier)) = 33268 := by
    have live13 : supportedSplitFrontiers 17 14 2 213 = {181, 182, 183, 184} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_14, support_17_2]
      ext value
      simp <;> omega
    rw [live13]
    calc
      (∑ leftFrontier ∈ {181, 182, 183, 184},
          frontierCoeff 17 14 leftFrontier *
            frontierCoeff 17 2 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {181, 182, 183, 184},
            if leftFrontier = 181 then 26796 else if leftFrontier = 182 then 5712 else if leftFrontier = 183 then 732 else if leftFrontier = 184 then 28 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_17_14_181, certificate_17_14_182, certificate_17_14_183, certificate_17_14_184, certificate_17_2_29, certificate_17_2_30,
            certificate_17_2_31, certificate_17_2_32] <;> simp
      _ = 33268 := by norm_num
  have split14 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 17 15 1 213,
        frontierCoeff 17 15 leftFrontier *
          frontierCoeff 17 1 (213 - leftFrontier)) = 8 := by
    have live14 : supportedSplitFrontiers 17 15 1 213 = {196} := by
      rw [supportedSplitFrontiers_eq_Icc, support_17_1, support_17_15]
      ext value
      simp <;> omega
    rw [live14]
    calc
      (∑ leftFrontier ∈ {196},
          frontierCoeff 17 15 leftFrontier *
            frontierCoeff 17 1 (213 - leftFrontier)) =
          ∑ leftFrontier ∈ {196},
            if leftFrontier = 196 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_17_15_196, certificate_17_1_17] <;> simp
      _ = 8 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (16 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 17 (offset + 1)
            (16 - (offset + 1)) 213,
          frontierCoeff 17 (offset + 1) leftFrontier *
            frontierCoeff 17 (16 - (offset + 1))
              (213 - leftFrontier)) = 146678756 := by
    have offsets : Finset.range (16 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
          ∑ leftFrontier ∈ supportedSplitFrontiers 17 (offset + 1)
              (16 - (offset + 1)) 213,
            frontierCoeff 17 (offset + 1) leftFrontier *
              frontierCoeff 17 (16 - (offset + 1))
                (213 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            if offset = 0 then 8 else if offset = 1 then 33268 else if offset = 2 then 606240 else if offset = 3 then 3242090 else if offset = 4 then 9406016 else if offset = 5 then 18366572 else if offset = 6 then 26661856 else if offset = 7 then 30046656 else if offset = 8 then 26661856 else if offset = 9 then 18366572 else if offset = 10 then 9406016 else if offset = 11 then 3242090 else if offset = 12 then 606240 else if offset = 13 then 33268 else if offset = 14 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11,
            split12, split13, split14] <;> simp
      _ = 146678756 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_17_16_212] <;> simp

theorem weighted_certificate_18_16_213 :
    concreteFrontierCount 18 16 213 = 1930884491681641557463795511326792565814715985981733169460991727765553152 := by
  rw [concreteFrontierCount, certificate_18_16_213]
  norm_num

end AspisV6CompactFrontierTailCertificate
