import AspisFormal.V6CompactFrontierTailCertificate.Depth14
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 15, chunk 16
Cells 41 through 41;
recurrence workload 80. -/

theorem certificate_15_3_39 :
    frontierCoeff 15 3 39 = 2 := by
  have zero_14_3_38 :
      frontierCoeff 14 3 38 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 2 39,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 2 (39 - leftFrontier)) = 1 := by
    have live0 : supportedSplitFrontiers 14 1 2 39 = {13, 14} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1, support_14_2]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {13, 14},
          frontierCoeff 14 1 leftFrontier *
            frontierCoeff 14 2 (39 - leftFrontier)) =
          ∑ leftFrontier ∈ {13, 14},
            if leftFrontier = 13 then 0 else if leftFrontier = 14 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_14_1_13, certificate_14_1_14, certificate_14_2_25, certificate_14_2_26] <;> simp
      _ = 1 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 2 1 39,
        frontierCoeff 14 2 leftFrontier *
          frontierCoeff 14 1 (39 - leftFrontier)) = 1 := by
    have live1 : supportedSplitFrontiers 14 2 1 39 = {25, 26} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1, support_14_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {25, 26},
          frontierCoeff 14 2 leftFrontier *
            frontierCoeff 14 1 (39 - leftFrontier)) =
          ∑ leftFrontier ∈ {25, 26},
            if leftFrontier = 25 then 1 else if leftFrontier = 26 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_14_1_13, certificate_14_1_14, certificate_14_2_25, certificate_14_2_26] <;> simp
      _ = 1 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (3 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (3 - (offset + 1)) 39,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (3 - (offset + 1))
              (39 - leftFrontier)) = 2 := by
    have offsets : Finset.range (3 - 1) = {0, 1} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (3 - (offset + 1)) 39,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (3 - (offset + 1))
                (39 - leftFrontier)) =
          ∑ offset ∈ {0, 1},
            if offset = 0 then 1 else if offset = 1 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [split0, split1] <;> simp
      _ = 2 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_14_3_38] <;> simp

end AspisV6CompactFrontierTailCertificate
