import AspisFormal.V6CompactFrontierTailCertificate.Depth14
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 15, chunk 60
Cells 85 through 85;
recurrence workload 665. -/

theorem certificate_15_8_94 :
    frontierCoeff 15 8 94 = 118 := by
  have zero_14_8_93 :
      frontierCoeff 14 8 93 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 7 94,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 7 (94 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 14 1 7 94 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1, support_14_7]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 2 6 94,
        frontierCoeff 14 2 leftFrontier *
          frontierCoeff 14 6 (94 - leftFrontier)) = 6 := by
    have live1 : supportedSplitFrontiers 14 2 6 94 = {26} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_2, support_14_6]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {26},
          frontierCoeff 14 2 leftFrontier *
            frontierCoeff 14 6 (94 - leftFrontier)) =
          ∑ leftFrontier ∈ {26},
            if leftFrontier = 26 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_14_2_26, certificate_14_6_68] <;> simp
      _ = 6 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 3 5 94,
        frontierCoeff 14 3 leftFrontier *
          frontierCoeff 14 5 (94 - leftFrontier)) = 28 := by
    have live2 : supportedSplitFrontiers 14 3 5 94 = {36, 37} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_3, support_14_5]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {36, 37},
          frontierCoeff 14 3 leftFrontier *
            frontierCoeff 14 5 (94 - leftFrontier)) =
          ∑ leftFrontier ∈ {36, 37},
            if leftFrontier = 36 then 8 else if leftFrontier = 37 then 20 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_14_3_36, certificate_14_3_37, certificate_14_5_57, certificate_14_5_58] <;> simp
      _ = 28 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 4 4 94,
        frontierCoeff 14 4 leftFrontier *
          frontierCoeff 14 4 (94 - leftFrontier)) = 50 := by
    have live3 : supportedSplitFrontiers 14 4 4 94 = {46, 47, 48} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {46, 47, 48},
          frontierCoeff 14 4 leftFrontier *
            frontierCoeff 14 4 (94 - leftFrontier)) =
          ∑ leftFrontier ∈ {46, 47, 48},
            if leftFrontier = 46 then 7 else if leftFrontier = 47 then 36 else if leftFrontier = 48 then 7 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_14_4_46, certificate_14_4_47, certificate_14_4_48] <;> simp
      _ = 50 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 5 3 94,
        frontierCoeff 14 5 leftFrontier *
          frontierCoeff 14 3 (94 - leftFrontier)) = 28 := by
    have live4 : supportedSplitFrontiers 14 5 3 94 = {57, 58} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_3, support_14_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {57, 58},
          frontierCoeff 14 5 leftFrontier *
            frontierCoeff 14 3 (94 - leftFrontier)) =
          ∑ leftFrontier ∈ {57, 58},
            if leftFrontier = 57 then 20 else if leftFrontier = 58 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_14_3_36, certificate_14_3_37, certificate_14_5_57, certificate_14_5_58] <;> simp
      _ = 28 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 6 2 94,
        frontierCoeff 14 6 leftFrontier *
          frontierCoeff 14 2 (94 - leftFrontier)) = 6 := by
    have live5 : supportedSplitFrontiers 14 6 2 94 = {68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_2, support_14_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {68},
          frontierCoeff 14 6 leftFrontier *
            frontierCoeff 14 2 (94 - leftFrontier)) =
          ∑ leftFrontier ∈ {68},
            if leftFrontier = 68 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_14_2_26, certificate_14_6_68] <;> simp
      _ = 6 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 7 1 94,
        frontierCoeff 14 7 leftFrontier *
          frontierCoeff 14 1 (94 - leftFrontier)) = 0 := by
    have live6 : supportedSplitFrontiers 14 7 1 94 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1, support_14_7]
      ext value
      simp <;> omega
    rw [live6]
    simp
  have outer :
      (∑ offset ∈ Finset.range (8 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (8 - (offset + 1)) 94,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (8 - (offset + 1))
              (94 - leftFrontier)) = 118 := by
    have offsets : Finset.range (8 - 1) = {0, 1, 2, 3, 4, 5, 6} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (8 - (offset + 1)) 94,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (8 - (offset + 1))
                (94 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6},
            if offset = 0 then 0 else if offset = 1 then 6 else if offset = 2 then 28 else if offset = 3 then 50 else if offset = 4 then 28 else if offset = 5 then 6 else if offset = 6 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6] <;> simp
      _ = 118 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_14_8_93] <;> simp

end AspisV6CompactFrontierTailCertificate
