import AspisFormal.V6CompactFrontierTailCertificate.Depth16
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 17, chunk 47
Cells 55 through 55;
recurrence workload 435. -/

theorem certificate_17_6_86 :
    frontierCoeff 17 6 86 = 6 := by
  have zero_16_6_85 :
      frontierCoeff 16 6 85 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 1 5 86,
        frontierCoeff 16 1 leftFrontier *
          frontierCoeff 16 5 (86 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 16 1 5 86 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_5]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 2 4 86,
        frontierCoeff 16 2 leftFrontier *
          frontierCoeff 16 4 (86 - leftFrontier)) = 1 := by
    have live1 : supportedSplitFrontiers 16 2 4 86 = {30} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_2, support_16_4]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {30},
          frontierCoeff 16 2 leftFrontier *
            frontierCoeff 16 4 (86 - leftFrontier)) =
          ∑ leftFrontier ∈ {30},
            if leftFrontier = 30 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_2_30, certificate_16_4_56] <;> simp
      _ = 1 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 3 3 86,
        frontierCoeff 16 3 leftFrontier *
          frontierCoeff 16 3 (86 - leftFrontier)) = 4 := by
    have live2 : supportedSplitFrontiers 16 3 3 86 = {43} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {43},
          frontierCoeff 16 3 leftFrontier *
            frontierCoeff 16 3 (86 - leftFrontier)) =
          ∑ leftFrontier ∈ {43},
            if leftFrontier = 43 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_3_43] <;> simp
      _ = 4 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 4 2 86,
        frontierCoeff 16 4 leftFrontier *
          frontierCoeff 16 2 (86 - leftFrontier)) = 1 := by
    have live3 : supportedSplitFrontiers 16 4 2 86 = {56} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_2, support_16_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {56},
          frontierCoeff 16 4 leftFrontier *
            frontierCoeff 16 2 (86 - leftFrontier)) =
          ∑ leftFrontier ∈ {56},
            if leftFrontier = 56 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_16_2_30, certificate_16_4_56] <;> simp
      _ = 1 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 5 1 86,
        frontierCoeff 16 5 leftFrontier *
          frontierCoeff 16 1 (86 - leftFrontier)) = 0 := by
    have live4 : supportedSplitFrontiers 16 5 1 86 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_5]
      ext value
      simp <;> omega
    rw [live4]
    simp
  have outer :
      (∑ offset ∈ Finset.range (6 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
            (6 - (offset + 1)) 86,
          frontierCoeff 16 (offset + 1) leftFrontier *
            frontierCoeff 16 (6 - (offset + 1))
              (86 - leftFrontier)) = 6 := by
    have offsets : Finset.range (6 - 1) = {0, 1, 2, 3, 4} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4},
          ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
              (6 - (offset + 1)) 86,
            frontierCoeff 16 (offset + 1) leftFrontier *
              frontierCoeff 16 (6 - (offset + 1))
                (86 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4},
            if offset = 0 then 0 else if offset = 1 then 1 else if offset = 2 then 4 else if offset = 3 then 1 else if offset = 4 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4] <;> simp
      _ = 6 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_16_6_85] <;> simp

end AspisV6CompactFrontierTailCertificate
