import AspisFormal.V6CompactFrontierTailCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v6_compact_frontier_tail.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV6CompactFrontierTailCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 80
Cells 100 through 100;
recurrence workload 721. -/

theorem certificate_16_8_102 :
    frontierCoeff 16 8 102 = 118 := by
  have zero_15_8_101 :
      frontierCoeff 15 8 101 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 7 102,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 7 (102 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 15 1 7 102 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_7]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 6 102,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 6 (102 - leftFrontier)) = 6 := by
    have live1 : supportedSplitFrontiers 15 2 6 102 = {28} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_6]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {28},
          frontierCoeff 15 2 leftFrontier *
            frontierCoeff 15 6 (102 - leftFrontier)) =
          ∑ leftFrontier ∈ {28},
            if leftFrontier = 28 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_15_2_28, certificate_15_6_74] <;> simp
      _ = 6 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 5 102,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 5 (102 - leftFrontier)) = 28 := by
    have live2 : supportedSplitFrontiers 15 3 5 102 = {39, 40} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_5]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {39, 40},
          frontierCoeff 15 3 leftFrontier *
            frontierCoeff 15 5 (102 - leftFrontier)) =
          ∑ leftFrontier ∈ {39, 40},
            if leftFrontier = 39 then 8 else if leftFrontier = 40 then 20 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_3_39, certificate_15_3_40, certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 28 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 4 4 102,
        frontierCoeff 15 4 leftFrontier *
          frontierCoeff 15 4 (102 - leftFrontier)) = 50 := by
    have live3 : supportedSplitFrontiers 15 4 4 102 = {50, 51, 52} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {50, 51, 52},
          frontierCoeff 15 4 leftFrontier *
            frontierCoeff 15 4 (102 - leftFrontier)) =
          ∑ leftFrontier ∈ {50, 51, 52},
            if leftFrontier = 50 then 7 else if leftFrontier = 51 then 36 else if leftFrontier = 52 then 7 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_15_4_50, certificate_15_4_51, certificate_15_4_52] <;> simp
      _ = 50 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 5 3 102,
        frontierCoeff 15 5 leftFrontier *
          frontierCoeff 15 3 (102 - leftFrontier)) = 28 := by
    have live4 : supportedSplitFrontiers 15 5 3 102 = {62, 63} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {62, 63},
          frontierCoeff 15 5 leftFrontier *
            frontierCoeff 15 3 (102 - leftFrontier)) =
          ∑ leftFrontier ∈ {62, 63},
            if leftFrontier = 62 then 20 else if leftFrontier = 63 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_15_3_39, certificate_15_3_40, certificate_15_5_62, certificate_15_5_63] <;> simp
      _ = 28 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 6 2 102,
        frontierCoeff 15 6 leftFrontier *
          frontierCoeff 15 2 (102 - leftFrontier)) = 6 := by
    have live5 : supportedSplitFrontiers 15 6 2 102 = {74} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_2, support_15_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {74},
          frontierCoeff 15 6 leftFrontier *
            frontierCoeff 15 2 (102 - leftFrontier)) =
          ∑ leftFrontier ∈ {74},
            if leftFrontier = 74 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_15_2_28, certificate_15_6_74] <;> simp
      _ = 6 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 7 1 102,
        frontierCoeff 15 7 leftFrontier *
          frontierCoeff 15 1 (102 - leftFrontier)) = 0 := by
    have live6 : supportedSplitFrontiers 15 7 1 102 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_7]
      ext value
      simp <;> omega
    rw [live6]
    simp
  have outer :
      (∑ offset ∈ Finset.range (8 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (8 - (offset + 1)) 102,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (8 - (offset + 1))
              (102 - leftFrontier)) = 118 := by
    have offsets : Finset.range (8 - 1) = {0, 1, 2, 3, 4, 5, 6} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (8 - (offset + 1)) 102,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (8 - (offset + 1))
                (102 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6},
            if offset = 0 then 0 else if offset = 1 then 6 else if offset = 2 then 28 else if offset = 3 then 50 else if offset = 4 then 28 else if offset = 5 then 6 else if offset = 6 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6] <;> simp
      _ = 118 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_15_8_101] <;> simp

end AspisV6CompactFrontierTailCertificate
