import Tag67SixActualStepsProof

#print axioms AspisTag67SixActualSteps.generated_batch_helper_check_precedes_absorb
#print axioms AspisTag67SixActualSteps.generated_fold_helper_check_precedes_absorb
#print axioms AspisTag67SixActualSteps.generated_final_helper_check_precedes_absorb
#print axioms AspisTag67SixActualSteps.generated_six_steps_success_iff
#print axioms AspisTag67SixActualSteps.generated_failure_returns_before_absorption
#print axioms AspisTag67SixActualSteps.maintained_trace_has_exact_six_positions
#print axioms AspisTag67SixActualSteps.maintained_trace_payloads_are_exact
#print axioms AspisTag67SixActualSteps.proofFacingSuccess_iff_exactSixActualSteps
#print axioms AspisTag67SixActualSteps.proofFacingSuccess_iff_exactSixPositionedStateTrace
