import Tag67WorkVerifierClosure

#print axioms AspisTag67WorkWireMaintained.generated_acceptance_constructs_exact_work_wire_view
#print axioms AspisTag67DigestPredicate.extracted_digest_predicate_iff_maintained
#print axioms AspisTag67SixActualStepsExtracted.extracted_success_iff_maintained_success
#print axioms AspisTag67SixActualSteps.proofFacingSuccess_iff_exactSixPositionedStateTrace
#print axioms AspisTag67WorkVerifierClosure.exactGrindingHashInput
#print axioms AspisTag67WorkVerifierClosure.acceptanceIffExactSixSteps
#print axioms AspisTag67WorkVerifierClosure.exactRustWorkVerifierCorrespondence_of_hash_application
#print axioms AspisTag67WorkVerifierClosure.tag67AcceptedWireAndVerifierClosure
