import Tag67SixActualStepsExtractedProof

#print axioms AspisTag67SixActualStepsExtracted.extracted_require_is_exact
#print axioms AspisTag67SixActualStepsExtracted.extracted_individual_helpers_are_exact
#print axioms AspisTag67SixActualStepsExtracted.extracted_six_actual_steps_exact_success
#print axioms AspisTag67SixActualStepsExtracted.extracted_failure_before_corresponding_absorb
#print axioms AspisTag67SixActualStepsExtracted.extracted_success_iff_maintained_success
