import Tag67WorkWireLE64Bridge

#print axioms AspisTag67WorkWire.extracted_work_offsets_exact
#print axioms AspisTag67WorkWire.extracted_batch_work_difficulty_exact
#print axioms AspisTag67WorkWire.extracted_fold_work_difficulties_exact
#print axioms AspisTag67WorkWire.extracted_final_work_difficulty_exact
#print axioms AspisTag67WorkWire.extracted_fold_difficulty_out_of_range_four
#print axioms AspisTag67WorkWire.extracted_batch_and_final_records_are_le64
#print axioms AspisTag67WorkWire.extracted_selector_is_exact_range_check
#print axioms AspisTag67WorkWire.extracted_selector_accepts_exact_candidates
#print axioms AspisTag67WorkWire.extracted_selector_rejects_three
#print axioms AspisTag67WorkWire.extracted_selector_rejects_255
#print axioms AspisTag67WorkWire.extracted_batch_and_final_positions_are_distinct
#print axioms AspisTag67WorkWire.extracted_fold_zero_and_one_positions_are_distinct
#print axioms AspisTag67WorkWire.extracted_batch_and_final_difficulties_are_distinct
#print axioms AspisTag67WorkWire.extracted_fold_round_zero_and_one_difficulties_are_distinct
#print axioms AspisTag67WorkWire.extracted_fold_absorb_input_exact
#print axioms AspisTag67WorkWire.extracted_batch_absorb_input_exact
#print axioms AspisTag67WorkWire.extracted_final_absorb_input_exact
#print axioms AspisTag67WorkWire.extracted_projection_preserves_exact_order
#print axioms AspisTag67WorkWireMaintained.generated_maps_match_maintained_work_model
#print axioms AspisTag67WorkWireMaintained.generated_read_zero
#print axioms AspisTag67WorkWireMaintained.generated_u64_from_le_bytes_roundtrip
#print axioms AspisTag67WorkWireMaintained.model_le64_roundtrip
#print axioms AspisTag67WorkWireMaintained.nonceLEBytes_matches_generated_u64
#print axioms AspisTag67WorkWireMaintained.bitVec_fromLEBytes_recovers_generated_u64
#print axioms AspisTag67WorkWireMaintained.generated_acceptance_constructs_exact_work_wire_view
