import FSV8S7DynamicSelectedRoot
import FSV8S7DynamicSuccessfulCut
import FSV8S7SelectedSourcePrefixBudget
import FSV8S7CompactWordTargetInclusion

/-!
# S7 promoted-endpoint audit

This root intentionally promotes only the source-connected facts completed in
S7.  It does not import a global soundness corollary: the literal terminal,
chronological authentication cuts, actual-root ordinary-event inclusion,
cached restoration and permitted-access extraction are still open producers.
-/

set_option autoImplicit false
set_option Elab.async false

#print AspisV8Completion.FSV8S7DynamicSelectedRoot.DynamicConfiguration
#print AspisV8Completion.FSV8S7DynamicSelectedRoot.Runtime
#print AspisV8Completion.FSV8S7DynamicSelectedRoot.successful_run_constructs_dynamic_context
#print AspisV8Completion.FSV8S7DynamicSelectedRoot.successful_run_has_canonical_wire
#print AspisV8Completion.FSV8S7DynamicSelectedRoot.run_dynamic_root_trace_is_erased_exposure_trace
#print AspisV8Completion.FSV8S7DynamicSuccessfulCut.successful_verifier_constructs_post_semantic_cut

#print AspisV8Completion.FSV8S7SelectedSourcePrefixBudget.selectedRelaxedThroughAlpha_call_bound
#print AspisV8Completion.FSV8S7SelectedSourcePrefixBudget.selectedRelaxedThroughAlpha_fresh_bound
#print AspisV8Completion.FSV8S7SelectedSourcePrefixBudget.successful_before_marker_has_canonical_body

#print AspisV8Completion.FSV8S7CompactWordTargetInclusion.false_claim_collision_mem_compactTarget

#print axioms AspisV8Completion.FSV8S7DynamicSelectedRoot.successful_run_constructs_dynamic_context
#print axioms AspisV8Completion.FSV8S7DynamicSelectedRoot.successful_run_has_canonical_wire
#print axioms AspisV8Completion.FSV8S7DynamicSelectedRoot.run_dynamic_root_trace_is_erased_exposure_trace
#print axioms AspisV8Completion.FSV8S7DynamicSuccessfulCut.successful_verifier_constructs_post_semantic_cut
#print axioms AspisV8Completion.FSV8S7SelectedSourcePrefixBudget.selectedRelaxedThroughAlpha_call_bound
#print axioms AspisV8Completion.FSV8S7SelectedSourcePrefixBudget.selectedRelaxedThroughAlpha_fresh_bound
#print axioms AspisV8Completion.FSV8S7SelectedSourcePrefixBudget.successful_before_marker_has_canonical_body
#print axioms AspisV8Completion.FSV8S7CompactWordTargetInclusion.false_claim_collision_mem_compactTarget
