-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aspis_v8_performance_host]: type definitions
import Aeneas.Std
import Aeneas.Data.Discriminant
import Aeneas.Tactic.RustAttributes
import AspisR136BeforeOod.TypesExternal
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AspisR136BeforeOod

/-- [aspis_core::field::M31]
    Source: '/home/dombarker/project-offloads/aspis-r20-r117-primal-20260930-a/crates/aspis-core/src/field.rs', lines 20:0-20:14
    Name pattern: [aspis_core::field::M31]
    Visibility: public -/
@[reducible, rust_type "aspis_core::field::M31"]
def aspis_core.field.M31 := Std.U32

/-- [aspis_core::field::CM31]
    Source: '/home/dombarker/project-offloads/aspis-r20-r117-primal-20260930-a/crates/aspis-core/src/field.rs', lines 207:0-207:15
    Name pattern: [aspis_core::field::CM31]
    Visibility: public -/
@[rust_type "aspis_core::field::CM31"]
structure aspis_core.field.CM31 where
  a : aspis_core.field.M31
  b : aspis_core.field.M31

/-- [aspis_core::field::QM31]
    Source: '/home/dombarker/project-offloads/aspis-r20-r117-primal-20260930-a/crates/aspis-core/src/field.rs', lines 375:0-375:15
    Name pattern: [aspis_core::field::QM31]
    Visibility: public -/
@[rust_type "aspis_core::field::QM31"]
structure aspis_core.field.QM31 where
  c0 : aspis_core.field.CM31
  c1 : aspis_core.field.CM31

/-- [aspis_core::transcript::ChallengeSampleExhausted]
    Source: '/home/dombarker/project-offloads/aspis-r20-r117-primal-20260930-a/crates/aspis-core/src/transcript.rs', lines 270:0-270:35
    Name pattern: [aspis_core::transcript::ChallengeSampleExhausted]
    Visibility: public -/
@[reducible, rust_type "aspis_core::transcript::ChallengeSampleExhausted"]
def aspis_core.transcript.ChallengeSampleExhausted := Unit

/-- [aspis_v8_performance_host::Error]
    Source: '../relation_callback.rs', lines 62:27-62:101 -/
@[discriminant isize]
inductive Error where
| Length : Error
| Canonical : Error
| Sampler : Error
| Shape : Error
| Authentication : Error
| Terminal : Error
| Domain : Error

/-- [aspis_v8_performance_host::sample::closure]
    Source: '../relation_callback.rs', lines 108:131-108:148 -/
@[reducible]
def sample.closure := Unit

/-- [aspis_v8_performance_host::Wire]
    Source: '../relation_callback.rs', lines 109:0-109:108 -/
structure Wire where
  v : alloc.vec.Vec aspis_core.field.QM31
  roots : ((Array Std.U8 26#usize) × (Array Std.U8 26#usize))
  nonces : Slice Std.U8
  records : Slice Std.U8
  frontiers : ((Slice Std.U8) × (Slice Std.U8))

end AspisR136BeforeOod
