from pathlib import Path
import hashlib,json,re,subprocess
repo=Path('/Users/dominic/ZK/.worktrees/ZK-v8-r21-public-arithmetic-20260922'); base=repo/'docs/research/v8-full-view-zk-20260912'
items=[('r340-current-batch-output-raw','lean/AspisR340BatchOutputRaw.lean','AspisR340BatchOutputRaw.lean','e735429b0b4d75348394ff897c704b06849b215d149d9264720e5945926fc63c','0:01.06',2531348,4),('r342-current-batch-output-setup','lean/AspisV8R19/R342OutputSetup.lean','R342OutputSetup.lean','9db388997a553eaaaa1e42ce3990239a80ef60be74a2365c676bba63542e24c4','0:01.66',3719400,9)]
current=subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip(); bundles=[]
for key,target_rel,copied_name,expected_sha,wall,rss,nreports in items:
 b=base/'evidence'/key; m=json.loads((b/'manifest.json').read_text()); t=base/target_rel; log=(b/m['log']).read_text(); runner=(b/'run_focus.py').read_text(); sums=json.loads((b/'SHA256SUMS.json').read_text()); hashchecks={r:hashlib.sha256((b/r).read_bytes()).hexdigest()==h for r,h in sums.items()}; reports=re.findall(r"'[^']+' (?:does not depend on any axioms|depends on axioms: \[.*?\])",log,re.S)
 checks={'all_checksums':all(hashchecks.values()),'source_copy_equal':t.read_bytes()==(b/'source'/copied_name).read_bytes(),'target_sha':hashlib.sha256(t.read_bytes()).hexdigest()==m['source_sha256']==expected_sha,'revision_ancestor':subprocess.run(['git','merge-base','--is-ancestor',m['source_revision'],current],cwd=repo).returncode==0,'successful_log_metrics':m['exit_status']==0 and m['wall_time']==wall and m['peak_rss_kib']==rss and m['swaps']==0 and f'Elapsed (wall clock) time (h:mm:ss or m:ss): {wall}' in log and f'Maximum resident set size (kbytes): {rss}' in log and 'Swaps: 0' in log and 'Exit status: 0' in log,'runner_caps':all(x in runner for x in ['MemoryHigh=5G','MemoryMax=7G','MemorySwapMax=0','TasksMax=128','-j1','-M4500']),'complete_axiom_reports':len(reports)==nreports and ' '.join((b/'axioms.txt').read_text().split())==' '.join('\n'.join(reports).split()),'no_sorry_success':'sorryAx' not in '\n'.join(reports)}
 if key.startswith('r340'):
  raw=b/'raw-adapter-audit'; a=json.loads((raw/'raw-binding-audit.json').read_text()); src=(raw/'provenance/R292Funs.input.lean').read_bytes(); lines=src.decode().splitlines(keepends=True); staged=t.read_text(); ranges={'clone_declarations':(183,200),'selectedOutput0_body':(569,586),'selectedOutput1_body':(587,604)}; exact={k:''.join(lines[i-1:j]) for k,(i,j) in ranges.items()}
  checks.update({'R292_source_sha':hashlib.sha256(src).hexdigest()==a['source_sha256']=='4d40a5b7b540adec90efef80a5ed8a5b4403704b388506af21f357761d95aec4','source_declarations_and_bodies_exact':all(staged.count(x)==1 for x in exact.values()),'clone_defs_axiom_free_and_two_wrappers_foundational':sum('does not depend on any axioms' in x for x in reports)==2 and sum('selectedOutput' in x and 'depends on axioms' in x for x in reports)==2,'no_operation_adaptations':a['allowed_source_adaptations']==[]})
 else:
  s=t.read_text(); sigs=[s.split('theorem '+n,1)[1].split(':= by',1)[0] for n in ['selectedOutput0_model','selectedOutput1_model']]; note=(base/'R342_CURRENT_BATCH_OUTPUT_SETUP.md').read_text(); dep=hashlib.sha256((base/'lean/AspisR340BatchOutputRaw.lean').read_bytes()).hexdigest()
  checks.update({'compiled_R340_dependency_hash':dep==m['compile_dependency_status']['source_sha256']=='e735429b0b4d75348394ff897c704b06849b215d149d9264720e5945926fc63c','input_conditions_are_explicit':('hnonempty : 0 < xs.val.length' in sigs[0] and 'hxs : ∀ j, 1 ≤ j → j < xs.val.length' in sigs[0] and 'hpx : ∀ j, j < xs.val.length - 1' in sigs[0] and 'hnonempty : 0 < ys.val.length' in sigs[1] and 'hys : ∀ j, 1 ≤ j → j < ys.val.length' in sigs[1] and 'hpy : ∀ j, j < ys.val.length - 1' in sigs[1]),'no_output_length_capacity_nonzero_or_success_premise':all(not re.search(r'\b(?:ox|oy|hcapacity|hcap|hnonzero|hsuccess)\b',x) for x in sigs) and all('≠ 0' not in x for x in sigs),'allocation_range_index_and_output_length_derived':'from_elem_zeroVec' in s and 'output_reverse_range_default' in s and 'have hcapacity' in s and 'have hindex' in s and 'reverseModel_output_length' in s,'second_model_definitional_equality':'selectedOutput1_eq_selectedOutput0' in s and 'by\n  rfl' in s.split('theorem selectedOutput1_eq_selectedOutput0',1)[1].split('theorem selectedOutput0_model',1)[0],'scope_limitations_documented':all(x in note for x in ['independent Rust-standard-library/compiler correspondence','original source guards','complete batch/callback'])})
 bundles.append({'bundle':key,'manifest':m,'checksums':hashchecks,'axiom_reports':reports,'checks':checks,'result':'PASS' if all(checks.values()) else 'DISCREPANCY'})
# Historical failures must remain visible and show sorryAx only in rejected attempts.
failed=[]; history=base/'evidence/r342-current-batch-output-setup/development-history'
for i in [1,2]:
 d=history/f'attempt-{i}'; receipt=json.loads((d/'receipt.json').read_text()); log=(d/'compile.log').read_text(); fc={'exit1':receipt['exit_status']==1 and 'Exit status: 1' in log,'metrics_recorded':receipt['wall_time'] in log and str(receipt['peak_rss_kib']) in log and receipt['swaps']==0 and 'Swaps: 0' in log,'source_matches_receipt':hashlib.sha256((d/'source.lean').read_bytes()).hexdigest()==receipt['source_sha256'],'sorryAx_in_rejected_only': 'sorryAx' in log,'all_files_present':all((d/f).exists() for f in ['source.lean','compile.log','receipt.json'])}; failed.append({'attempt':i,'receipt':receipt,'checks':fc,'result':'PASS' if all(fc.values()) else 'DISCREPANCY'})
worker=history/'worker-draft'; worker_ok=(worker/'source.lean').exists() and (worker/'audit.md').exists()
report={'audit':'R340/R342 saved-evidence audit','read_only':True,'no_lean_rerun_or_tracked_edits':True,'current_revision':current,'bundles':bundles,'failed_attempts':failed,'worker_draft_preserved':worker_ok,'scope':'R340 copies clone definitions and two R292 output fragments exactly with no operation substitutions; clone declarations are axiom-free, wrappers foundational only. R342 theorem hypotheses are explicit nonempty input and canonical reads over indices 1..length−1 plus prefix reads below length−1. No output vector/length, capacity, nonzero or successful execution premise is supplied; cloned-zero allocation/from_elem result, reverse range/end, capacity, output length and safe index-zero bound are derived from Slice bounds and the model. This only proves against pinned Aeneas Std definitions and established reverse-loop models; original source guards, independent Rust Std/compiler correspondence, full batch and callback remain open. Failed drafts and worker original are preserved.' ,'overall':'PASS' if all(b['result']=='PASS' for b in bundles) and all(f['result']=='PASS' for f in failed) and worker_ok else 'DISCREPANCY'}
(repo/'.r21-scratch/r342-saved-evidence-audit/audit.json').write_text(json.dumps(report,indent=2)+'\n')
print(report['overall'])
for b in bundles: print(b['bundle'],b['result'],b['manifest']['source_revision'],b['manifest']['wall_time'],b['manifest']['peak_rss_kib'],len(b['axiom_reports']))
for f in failed: print('attempt',f['attempt'],f['result'],f['receipt']['wall_time'],f['receipt']['peak_rss_kib'])
