name = "aspis-aeneas-verif"
version = "0.0.0"
defaultTargets = ["AspisAeneas"]

[[require]]
name = "aeneas"
git = { url = "https://github.com/AeneasVerif/aeneas", subDir = "backends/lean" }
rev = "b59d5188c082f704a418c7cb4e52ad69328002d1"

[[lean_lib]]
name = "AspisAeneas"
roots = ["AspisCoreFieldAdd", "M31AddProof"]
