#!/usr/bin/env python3
"""Read-only consistency audit for saved R425 main build and failed translation."""
import hashlib,json,pathlib,re
BASE=pathlib.Path(__file__).resolve().parents[1]; OUT=pathlib.Path(__file__).resolve().parent
checks=[]
def ck(n,v,d):checks.append({'check':n,'pass':bool(v),'detail':d})
def j(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def timed(p):
 t=p.read_text(); z=re.search(r'Elapsed \(wall clock\) time .*: ([0-9:]+\.[0-9]+)',t).group(1).split(':'); w=sum(float(x)*60**(len(z)-i-1) for i,x in enumerate(z)); return {'wall_seconds':w,'peak_rss_kib':int(re.search(r'Maximum resident set size \(kbytes\): (\d+)',t).group(1)),'swaps':int(re.search(r'Swaps: (\d+)',t).group(1)),'exit_status':int(re.search(r'Exit status: (\d+)',t).group(1)),'sha256':sha(p)}
main=BASE/'build-preflight/r425-main-build-v1'; tm=BASE/'translation-runner/output/ee7ba72da456-20261002T210856Z'; hist=BASE/'translation-runner/launch-history/ee7ba72da456-20261002T210856Z'
c=j(main/'command.json'); r=j(main/'result.json'); inp=j(BASE/'build-preflight/main-build-inputs.reviewed.json'); mt=timed(main/'gnu-time.txt')
ck('main release target and status',c['target']=='main.exe plus unique aeneas-r425-unit-constant-candidate' and mt['exit_status']==0 and r['exit_status']==0 and r['binary_sha256']=='eadb205fc1e00cf7e32197dd7cbbbd82aa42b59442d8f186cfdca7c8fdca9b01',{'target':c['target'],'metrics':mt,'binary_sha256':r['binary_sha256']})
ck('main measurements',mt['wall_seconds']==1.74 and mt['peak_rss_kib']==334792 and mt['swaps']==0,mt)
ck('main source/launch revision provenance',c['source_revision']==r['source_revision']==inp['source_revision']=='ee7ba72da456d5f353bca9f6739b23750a5dfffa',{'compiled_source_revision':c['source_revision'],'launch_revision':inp['source_revision']})
sourcefacts={}
for rel,want in c['source_sha256'].items():
 p=main/'source'/('R419_candidate.llbc' if rel=='R419_candidate.llbc' else rel); got=sha(p) if p.is_file() else None; sourcefacts[rel]=got; ck('main source snapshot '+rel,got==want,{'expected':want,'actual':got})
ck('main records both fixture gates',c['fixture11_assertions']==11 and c['fixture8_assertions']==8 and c['fixture11_receipt_sha256']==sha(BASE/'build-preflight/r425-unit-fixture-execution-v1/result.json') and c['fixture8_receipt_sha256']==sha(BASE/'build-preflight/r425-unit-evaluator-execution-v1/result.json') and c['fixture11_log_sha256']==sha(BASE/'build-preflight/r425-unit-fixture-execution-v1/raw.log') and c['fixture8_log_sha256']==sha(BASE/'build-preflight/r425-unit-evaluator-execution-v1/raw.log'),{'fixture11_receipt':c['fixture11_receipt_sha256'],'fixture8_receipt':c['fixture8_receipt_sha256']})
di=j(main/'docker-inspect.json')[0]; h=di['HostConfig']; st=di['State']; sl=j(main/'reservation-before.json')['slice']; scopeok=h['MemoryReservation']==5368709120 and h['Memory']==7516192768 and h['MemorySwap']==7516192768 and h['PidsLimit']==128 and h['NetworkMode']=='none' and h['CgroupParent']=='aspisr425.slice' and st['ExitCode']==0 and not st['OOMKilled'] and all(x in sl for x in ('MemoryHigh=5368709120','MemoryMax=7516192768','MemorySwapMax=0','TasksMax=128'))
ck('main capped status',scopeok,{'docker_exit':st['ExitCode'],'oom':st['OOMKilled'],'docker_caps':{k:h[k] for k in ('MemoryReservation','Memory','MemorySwap','PidsLimit','NetworkMode','CgroupParent')},'systemd_slice':sl})
# Translation input, command and receipts all match the unchanged R419 candidate and R396 baseline.
tcmd=j(tm/'translate-command.json'); tres=j(tm/'translation-result.json'); tr=j(tm/'result.json'); launch=j(hist/'launch-result.json'); ljson=j(hist/'launch.json'); log=(tm/'translate.log').read_text(); g=timed(tm/'translate.log'); mr=j(tm/'metrics-receipt.json')
ck('translation is the selected exact R419 candidate and R396 baseline',tcmd['candidate_sha256']=='7f82eaabe855e89d735b21f9af5f6a983abea6b2f4d93d4b8bae747abd2829e2' and tcmd['baseline_sha256']=='399020435e94aaa7135c06d68445e9b936bd22fe6d1e1d197ee708d448d584ae' and tr['candidate_sha256']==tcmd['candidate_sha256'] and tr['baseline_sha256']==tcmd['baseline_sha256'] and ljson['candidate_sha256']==tcmd['candidate_sha256'] and ljson['baseline_sha256']==tcmd['baseline_sha256'],{'candidate_sha256':tcmd['candidate_sha256'],'baseline_sha256':tcmd['baseline_sha256']})
ck('translation executable equals successful main binary',tcmd['binary_sha256']==r['binary_sha256']==tr['binary_sha256']==ljson['binary_sha256']=='eadb205fc1e00cf7e32197dd7cbbbd82aa42b59442d8f186cfdca7c8fdca9b01',{'main_binary':r['binary_sha256'],'translation_binary':tcmd['binary_sha256']})
expected_flags=['-sequential','-no-progress-bar','-abort-on-error','-backend','lean','-namespace','AspisR425UnitConstant','-dest','<fresh>/generated','-subdir','AspisR425UnitConstant','-split-files','-emit-json']
ck('translation root namespace and flags unchanged',tcmd['namespace']=='AspisR425UnitConstant' and tcmd['flags']==expected_flags and tcmd['command'][-1].endswith('/candidate.llbc'),{'namespace':tcmd['namespace'],'flags':tcmd['flags'],'root':'crate::circle_norm::joined_inverse::line_norm::r110_norm::batch'})
ck('translation failure diagnostic and absence of output',g['exit_status']==2 and tr['translator_exit_status']==2 and tres['generated_dir_exists'] is False and tres['translation_json_exists'] is False and tres['manifest_function_entries']==0 and 'Can\'t copy a mutable borrow' in log and 'iterator.rs\', lines 78:4-78:45' in log and 'InterpExpressions.ml, line 234' in log,{'metrics':g,'generated_dir_exists':tres['generated_dir_exists'],'translation_json_exists':tres['translation_json_exists'],'diagnostic':'Can\'t copy a mutable borrow at Iterator::next lines 78:4–78:45; compiler InterpExpressions.ml:234'})
ck('translation launch resource gate and statuses',launch['caps']=={'MemoryHigh':'5G','MemoryMax':'7G','MemorySwapMax':'0','TasksMax':128} and launch['launcher_exit_status']==2 and launch['scp_exit_status']==0 and launch['binary_sha256']==r['binary_sha256'] and launch['translation_launch_revision']=='ee7ba72da456d5f353bca9f6739b23750a5dfffa',{'caps':launch['caps'],'launcher_exit_status':launch['launcher_exit_status'],'scp_exit_status':launch['scp_exit_status']})
ck('translation compiler metrics',g['wall_seconds']==0.77 and g['peak_rss_kib']==142032 and g['swaps']==0,g)
ck('translation supplemental metrics receipt matches raw log',mr['exit_status']==g['exit_status']==2 and mr['wall_time']=='0:00.77' and mr['peak_rss_kib']==g['peak_rss_kib']==142032 and mr['swap']==g['swaps']==0 and mr['complete_log_sha256']==sha(tm/'translate.log') and mr['binary_sha256']==tcmd['binary_sha256'] and mr['candidate_input_sha256']==tcmd['candidate_sha256'], {'metrics_receipt_sha256':sha(tm/'metrics-receipt.json'),'receipt':mr})
ck('translation has no generated Lean axioms to report',tr['scope']=='Translation inventory only; no Lean compile, template fill, proof, or source claim.' and not any(p.is_file() for p in tm.rglob('*.lean')),'No Lean source emitted; #print axioms N/A.')
ck('axiom reporting N/A for native build',c['axioms']=='NA: OCaml compilation only','Native OCaml compilation; no Lean theorem.')
rawpaths=[main/'command.json',main/'result.json',main/'gnu-time.txt',main/'build.log',main/'docker-inspect.json',main/'reservation-before.json',tm/'translate-command.json',tm/'translation-result.json',tm/'result.json',tm/'translate.log',tm/'metrics-receipt.json',tm/'host-reservation-before.json',tm/'host-reservation-after.json',hist/'launch.json',hist/'launch-result.json',hist/'launch.log',hist/'remote_translate.py',BASE/'translation-runner/translation-launch.log']
rawsha={str(p.relative_to(BASE)):sha(p) for p in rawpaths}
metrics={'main_build':{'source_revision':c['source_revision'],'exit_status':mt['exit_status'],'wall_seconds':mt['wall_seconds'],'peak_rss_kib':mt['peak_rss_kib'],'swaps':mt['swaps'],'binary_sha256':r['binary_sha256'],'gnu_time_sha256':mt['sha256']},'translation':{'candidate_sha256':tcmd['candidate_sha256'],'baseline_sha256':tcmd['baseline_sha256'],'binary_sha256':tcmd['binary_sha256'],'exit_status':g['exit_status'],'wall_seconds':g['wall_seconds'],'peak_rss_kib':g['peak_rss_kib'],'swaps':g['swaps'],'diagnostic':'Can\'t copy a mutable borrow; Iterator::next source span 78:4–78:45, compiler interp/InterpExpressions.ml:234','generated_files':0,'gnu_time_sha256':g['sha256']},'translation_launch_revision':ljson['translation_launch_revision'],'caps':launch['caps'],'axioms':'Not applicable: OCaml build succeeded; Aeneas translation failed before generating Lean files.','raw_artifact_sha256':rawsha}
(OUT/'metrics-receipt.json').write_text(json.dumps(metrics,indent=2)+'\n')
a={'result':'PASS' if all(x['pass'] for x in checks) else 'FAIL','scope':'Saved R425 main-build and single-translation diagnostics only; no reruns. Translation failed before generating Lean source; no formal or source-correspondence theorem is claimed.','checks':checks,'raw_artifact_sha256':rawsha}
(OUT/'audit.json').write_text(json.dumps(a,indent=2)+'\n')
(OUT/'REPORT.md').write_text('# R425 main build and translation diagnostic audit\n\n'+a['result']+' — '+a['scope']+'\n\nThe R425 main executable build passed in 1.74 s, peak RSS 334792 KiB, zero swaps; its recorded executable SHA256 is `eadb205f…ca9b01`. The single translation used unchanged R419 and R396 inputs with the reviewed namespace and flags. It exited 2 in 0.77 s, peak RSS 142032 KiB, zero swaps. Aeneas stopped at the mutable-borrow copy failure for `Iterator::next` (Rust span `iterator.rs:78:4–78:45`; compiler `InterpExpressions.ml:234`). No generated Lean or JSON manifest was produced. The translation has no Lean axiom report; the OCaml build axiom field is N/A.\n')
print(a['result']);[print(('PASS ' if x['pass'] else 'FAIL ')+x['check']) for x in checks]
