#!/usr/bin/env python3
"""Read-only audit for the saved R425 eight-check build/execution phases."""
import hashlib,json,pathlib,re
BASE=pathlib.Path(__file__).resolve().parents[1]; OUT=pathlib.Path(__file__).resolve().parent
checks=[]
def ck(n,v,d):checks.append({'check':n,'pass':bool(v),'detail':d})
def j(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def timed(p):
 t=p.read_text(); q=re.search(r'Elapsed \(wall clock\) time .*: ([0-9:]+\.[0-9]+)',t).group(1).split(':'); wall=sum(float(x)*60**(len(q)-i-1) for i,x in enumerate(q)); return {'wall_seconds':wall,'peak_rss_kib':int(re.search(r'Maximum resident set size \(kbytes\): (\d+)',t).group(1)),'swaps':int(re.search(r'Swaps: (\d+)',t).group(1)),'exit_status':int(re.search(r'Exit status: (\d+)',t).group(1)),'sha256':sha(p)}
failed=BASE/'r425-unit-execution-fixture-build-v1'; good=BASE/'r425-unit-execution-fixture-build-v2'; run=BASE/'r425-unit-evaluator-execution-v1'
c1=j(failed/'command.json'); r1=j(failed/'result.json'); c2=j(good/'command.json'); r2=j(good/'result.json'); ce=j(run/'command.json'); rexe=j(run/'result.json')
# Every saved source snapshot is covered by its phase's exact source SHA map.
for label,phase,command in [('failed build v1',failed,c1),('successful build v2',good,c2),('execution',run,ce)]:
 for rel,want in command['source_sha256'].items():
  file=phase/'source'/('R419_candidate.llbc' if rel=='R419_candidate.llbc' else rel)
  ck(label+' source '+rel,file.is_file() and sha(file)==want,{'expected':want,'actual':sha(file) if file.is_file() else None})
ck('v1 source is retained private evaluator API version',c1['source_sha256']['src/UnitConstantExecutionFixture.ml']=='a9bab4cc922e59626755995d37bd080b8c227a42ede7b1987f33a38228214dbb' and 'eval_operand_no_reorganize' in (failed/'build.log').read_text() and 'Unbound value' in (failed/'build.log').read_text(),{'fixture_sha256':c1['source_sha256']['src/UnitConstantExecutionFixture.ml'],'diagnostic':'Unbound value InterpExpressions.eval_operand_no_reorganize'})
ck('v1 is classified as compile failure',timed(failed/'gnu-time.txt')['exit_status']==1 and r1['exit_status']==1 and r1['fixture_executable_sha256'] is None,{'gnu':timed(failed/'gnu-time.txt'),'result_exit':r1['exit_status']})
ck('v2 exports evaluator call API in exact fixture snapshot',c2['source_sha256']['src/UnitConstantExecutionFixture.ml']=='2bf4937f01e2ed053c0599071862239204c54945805490a3f6261ccbcbdd7a00' and 'eval_operands' in (good/'source/src/UnitConstantExecutionFixture.ml').read_text() and 'eval_operand_no_reorganize' not in (good/'source/src/UnitConstantExecutionFixture.ml').read_text(),{'fixture_sha256':c2['source_sha256']['src/UnitConstantExecutionFixture.ml']})
ck('build v1/v2 differ only on fixture source among common inputs',all(c1['source_sha256'][k]==c2['source_sha256'][k] for k in c1['source_sha256'] if k!='src/UnitConstantExecutionFixture.ml') and c2['source_sha256']['src/UnitConstantExecutionFixture.ml']!=c1['source_sha256']['src/UnitConstantExecutionFixture.ml'],{'changed_input':'src/UnitConstantExecutionFixture.ml','v1':c1['source_sha256']['src/UnitConstantExecutionFixture.ml'],'v2':c2['source_sha256']['src/UnitConstantExecutionFixture.ml']})
# Reviewed sources correspond to successful inputs.
reviewed={'src/UnitConstantExecutionFixture.ml':pathlib.Path('.r21-scratch/r425-unit-constant-frontier/fixtures/UnitConstantExecutionFixture.reviewed-v2.ml'),'src/dune':pathlib.Path('.r21-scratch/r425-unit-constant-frontier/fixtures/dune.execution.reviewed')}
for rel,p in reviewed.items():ck('v2 reviewed input '+rel,sha(p)==c2['source_sha256'][rel],{'path':str(p),'expected':c2['source_sha256'][rel],'actual':sha(p)})
m1=timed(failed/'gnu-time.txt');m2=timed(good/'gnu-time.txt');me=timed(run/'gnu-time.txt')
ck('v2 successful build metrics',m2['exit_status']==0 and m2['wall_seconds']==1.48 and m2['peak_rss_kib']==296544 and m2['swaps']==0,m2)
ck('execution metrics',me['exit_status']==0 and me['wall_seconds']==0.13 and me['peak_rss_kib']==49808 and me['swaps']==0,me)
for label,p in [('v1 failed build',failed),('v2 successful build',good),('8-check execution',run)]:
 d=j(p/'docker-inspect.json')[0];h=d['HostConfig'];st=d['State'];sl=j(p/'reservation-before.json')['slice'];ok=h['MemoryReservation']==5368709120 and h['Memory']==7516192768 and h['MemorySwap']==7516192768 and h['PidsLimit']==128 and h['NetworkMode']=='none' and h['CgroupParent']=='aspisr425.slice' and all(x in sl for x in ('MemoryHigh=5368709120','MemoryMax=7516192768','MemorySwapMax=0','TasksMax=128')) and st['ExitCode']==({'v1 failed build':1,'v2 successful build':0,'8-check execution':0}[label]) and not st['OOMKilled'];ck(label+' capped status',ok,{'container_exit':st['ExitCode'],'oom':st['OOMKilled'],'caps':{k:h[k] for k in ('MemoryReservation','Memory','MemorySwap','PidsLimit','NetworkMode','CgroupParent')},'systemd_slice':sl})
raw=(run/'raw.log').read_text(); diag='Found unexpected constant: ((),)'; dcount=raw.count(diag); src='Source: \'/rustc/library/core/src/iter/traits/iterator.rs\', lines 2486:4-2490:35'; scount=raw.count(src); marker='R425 unit execution checks passed: 8'
ck('exact expected evaluator diagnostic repeats twice',dcount==2 and scount==2,{'diagnostic_count':dcount,'source_span_count':scount,'diagnostic':diag,'source':src})
ck('eight-check fixture marker and result',rexe['exit_status']==0 and rexe['all_checks_passed'] is True and rexe['assertions_passed']==8 and rexe['success_marker_count']==1 and raw.count(marker)==1 and rexe['raw_log_sha256']==sha(run/'raw.log'),{'result':rexe,'marker':marker})
ck('execution uses exact v2 binary and exact R419 input',r2['fixture_executable_sha256']=='fcdbd8dafe0769cd941101724c63cc3a644b068d08c5ee682edf349ef2b0fd08' and ce['fixture_executable_sha256']==r2['fixture_executable_sha256'] and ce['input_sha256']==c2['source_sha256']['R419_candidate.llbc'] and c2['expected_assertions']==ce['expected_assertions']==8 and ce['lead_approval'] is True,{'built_executable_sha256':r2['fixture_executable_sha256'],'execution_executable_sha256':ce['fixture_executable_sha256'],'input_sha256':ce['input_sha256'],'expected_checks':ce['expected_assertions'],'approval':ce['lead_approval']})
ck('axiom reporting N/A',c1['axioms']==c2['axioms']=='NA: OCaml compilation only' and ce['axioms']=='NA: finite OCaml fixture checks, not Lean.','No Lean theorem involved.')
artifacts=[failed/'command.json',failed/'result.json',failed/'gnu-time.txt',failed/'build.log',failed/'docker-inspect.json',failed/'reservation-before.json',good/'command.json',good/'result.json',good/'gnu-time.txt',good/'build.log',good/'docker-inspect.json',good/'reservation-before.json',run/'command.json',run/'result.json',run/'gnu-time.txt',run/'raw.log',run/'docker-inspect.json',run/'reservation-before.json',BASE/'run_execution_fixture_build.reviewed.py',BASE/'run_execution_fixture_build.reviewed-v2.py',BASE/'run_evaluator_execution.reviewed.py']
rawsha={str(p.relative_to(BASE)):sha(p) for p in artifacts}
metrics={'source_revision':c2['source_revision'],'build_v1_failed':{'source_sha256':c1['source_sha256'],'exit_status':m1['exit_status'],'wall_seconds':m1['wall_seconds'],'peak_rss_kib':m1['peak_rss_kib'],'swaps':m1['swaps'],'failure':'Unbound private evaluator helper eval_operand_no_reorganize'},'build_v2':{'source_sha256':c2['source_sha256'],'exit_status':m2['exit_status'],'wall_seconds':m2['wall_seconds'],'peak_rss_kib':m2['peak_rss_kib'],'swaps':m2['swaps'],'executable_sha256':r2['fixture_executable_sha256']},'execution':{'exit_status':me['exit_status'],'wall_seconds':me['wall_seconds'],'peak_rss_kib':me['peak_rss_kib'],'swaps':me['swaps'],'checks_passed':rexe['assertions_passed'],'expected_diagnostic_occurrences':dcount,'expected_source_span_occurrences':scount,'executable_sha256':ce['fixture_executable_sha256'],'input_sha256':ce['input_sha256']},'resource_scope':'Each Docker phase: 5GiB reservation, 7GiB memory and memory-swap (no extra container swap), 128 PIDs, no network, aspisr425.slice; host slice MemoryHigh=5G, MemoryMax=7G, MemorySwapMax=0, TasksMax=128.','axioms':'Not applicable: native OCaml compilation and fixture checks, not Lean.','raw_artifact_sha256':rawsha}
(OUT/'metrics-receipt.json').write_text(json.dumps(metrics,indent=2)+'\n')
a={'result':'PASS' if all(x['pass'] for x in checks) else 'FAIL','scope':'Saved R425 8-check fixture build and execution evidence only; no reruns. The checks are finite native behavior on exact R419 LLBC and do not prove translator or Lean/source correspondence.','checks':checks,'raw_artifact_sha256':rawsha}
(OUT/'audit.json').write_text(json.dumps(a,indent=2)+'\n')
(OUT/'REPORT.md').write_text('# R425 eight-check fixture evidence audit\n\n'+a['result']+' — '+a['scope']+'\n\nThe first build attempt failed to compile because the fixture named private `eval_operand_no_reorganize`; the saved compiler diagnostic says it was unbound. The corrected source uses exported `eval_operands` and built successfully in 1.48 s with 296544 KiB peak RSS and zero swaps. Its execution passed eight checks in 0.13 s with 49808 KiB peak RSS and zero swaps. The raw output contains the expected unsupported `((),)` constant diagnostic twice at `iterator.rs:2486:4-2490:35`, followed by the single eight-check success marker. Systemd and Docker receipts confirm the capped scope. No Lean theorem or source-execution correspondence was proved.\n')
print(a['result']); [print(('PASS ' if x['pass'] else 'FAIL ')+x['check']) for x in checks]
