-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aspis_v8_performance_host]: type definitions
import Aeneas.Std
import Aeneas.Data.Discriminant
import Aeneas.Tactic.RustAttributes
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AspisR569MaskedClaimCompleteConsts

/-- [aspis_core::field::M31]
    Source: '/home/dombarker/project-offloads/aspis-r569-masked-claim-20261004-b/crates/aspis-core/src/field.rs', lines 20:0-20:14
    Name pattern: [aspis_core::field::M31]
    Visibility: public -/
@[reducible, rust_type "aspis_core::field::M31"]
def aspis_core.field.M31 := Std.U32

/-- [aspis_core::field::CM31]
    Source: '/home/dombarker/project-offloads/aspis-r569-masked-claim-20261004-b/crates/aspis-core/src/field.rs', lines 207:0-207:15
    Name pattern: [aspis_core::field::CM31]
    Visibility: public -/
@[rust_type "aspis_core::field::CM31"]
structure aspis_core.field.CM31 where
  a : aspis_core.field.M31
  b : aspis_core.field.M31

/-- [aspis_core::field::QM31]
    Source: '/home/dombarker/project-offloads/aspis-r569-masked-claim-20261004-b/crates/aspis-core/src/field.rs', lines 375:0-375:15
    Name pattern: [aspis_core::field::QM31]
    Visibility: public -/
@[rust_type "aspis_core::field::QM31"]
structure aspis_core.field.QM31 where
  c0 : aspis_core.field.CM31
  c1 : aspis_core.field.CM31

/-- [aspis_core::state_only_hiding::StateOnlyHidingScheduleError]
    Source: '/home/dombarker/project-offloads/aspis-r569-masked-claim-20261004-b/crates/aspis-core/src/state_only_hiding.rs', lines 187:0-187:37
    Name pattern: [aspis_core::state_only_hiding::StateOnlyHidingScheduleError]
    Visibility: public -/
@[discriminant isize, rust_type
  "aspis_core::state_only_hiding::StateOnlyHidingScheduleError"]
inductive aspis_core.state_only_hiding.StateOnlyHidingScheduleError where
| ZeroMaskNonce : aspis_core.state_only_hiding.StateOnlyHidingScheduleError
| MaskLayoutFingerprint :
  aspis_core.state_only_hiding.StateOnlyHidingScheduleError
| LayoutFactorFingerprint :
  aspis_core.state_only_hiding.StateOnlyHidingScheduleError
| ChallengeSampleExhausted :
  aspis_core.state_only_hiding.StateOnlyHidingScheduleError

/-- [aspis_core::transcript::ChallengeSampleExhausted]
    Source: '/home/dombarker/project-offloads/aspis-r569-masked-claim-20261004-b/crates/aspis-core/src/transcript.rs', lines 270:0-270:35
    Name pattern: [aspis_core::transcript::ChallengeSampleExhausted]
    Visibility: public -/
@[reducible, rust_type "aspis_core::transcript::ChallengeSampleExhausted"]
def aspis_core.transcript.ChallengeSampleExhausted := Unit

/-- [aspis_core::transcript::Transcript]
    Source: '/home/dombarker/project-offloads/aspis-r569-masked-claim-20261004-b/crates/aspis-core/src/transcript.rs', lines 302:0-302:21
    Name pattern: [aspis_core::transcript::Transcript]
    Visibility: public -/
@[rust_type "aspis_core::transcript::Transcript"]
structure aspis_core.transcript.Transcript where
  state : Array Std.U8 32#usize
  hash : Slice (Slice Std.U8) → Result (Array Std.U8 32#usize)

end AspisR569MaskedClaimCompleteConsts
