[package]
name = "whir-ud-verifier"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
no-entrypoint = []
custom-heap = []
custom-panic = []

[dependencies]
solana-program.workspace = true
whir-ud-host = { path = "../../crates/whir-ud-host" }
