from pathlib import Path
import hashlib,json,re,subprocess
repo=Path('/Users/dominic/ZK/.worktrees/ZK-v8-r21-public-arithmetic-20260922'); base=repo/'docs/research/v8-full-view-zk-20260912'; ss=repo/'.r21-scratch'
inputs=[('r335-current-prefix-pair-inverse-raw','lean/AspisR335PrefixPairInverseRaw.lean','AspisR335PrefixPairInverseRaw.lean','67fca6d8afa06270da4eb289adbc582bb8106e3a65730a2e3685ec086b1e9af7',['AspisR335PrefixPairInverseRaw.selectedPrefix1','AspisR335PrefixPairInverseRaw.selectedPairInverse'],'0:00.97',2526928),('r336-current-prefix-pair-inverse-execution','lean/AspisV8R19/R336PrefixPairInverseExecution.lean','R336PrefixPairInverseExecution.lean','a0a96da4bd0b52d04dfce491d154499700942ccef41553c1a96a4713504a4f56',['AspisV8R19.R336PrefixPairInverseExecution.second_prefix_eq_first','AspisV8R19.R336PrefixPairInverseExecution.second_prefix_empty','AspisV8R19.R336PrefixPairInverseExecution.second_prefix_bundle','AspisV8R19.R336PrefixPairInverseExecution.pair_inverse_complete','AspisV8R19.R336PrefixPairInverseExecution.initialized_pair_inverse'],'0:01.68',3710716)]
current=subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo,text=True).strip(); bundles=[]
for key,target_rel,src_name,sha,names,wall,rss in inputs:
 b=base/'evidence'/key; m=json.loads((b/'manifest.json').read_text()); target=base/target_rel; log=(b/m['log']).read_text(); scopy=(b/'source'/src_name).read_bytes(); manifest_hashes=json.loads((b/'SHA256SUMS.json').read_text()); checksums={p:hashlib.sha256((b/p).read_bytes()).hexdigest()==h for p,h in manifest_hashes.items()}
 axioms=[]
 for name in names:
  mt=re.search(re.escape("'"+name+"' depends on axioms: [")+r"(.*?)\]",log,re.S); axioms.append({'name':name,'found':bool(mt),'items':sorted(y.strip() for y in mt.group(1).replace('\n',' ').split(',')) if mt else []})
 runner=(b/'run_focus.py').read_text(); revision=m['source_revision']; ancestor=subprocess.run(['git','merge-base','--is-ancestor',revision,current],cwd=repo).returncode==0
 checks={'checksums_all_match':all(checksums.values()),'saved_source_copy_matches_target':target.read_bytes()==scopy,'target_sha_matches_expected':hashlib.sha256(target.read_bytes()).hexdigest()==sha==m['source_sha256'],'recorded_compile_revision_is_ancestor':revision=='d04d10ffd971f0821e29afcbb6d04528a2873f9c' and ancestor,'log_and_manifest_metrics_match':m['exit_status']==0 and m['wall_time']==wall and m['peak_rss_kib']==rss and m['swaps']==0 and f'Elapsed (wall clock) time (h:mm:ss or m:ss): {wall}' in log and f'Maximum resident set size (kbytes): {rss}' in log and 'Swaps: 0' in log and 'Exit status: 0' in log,'runner_has_caps':all(k in runner for k in ['MemoryHigh=5G','MemoryMax=7G','MemorySwapMax=0','TasksMax=128','-j1','-M4500']),'all_reports_foundation_only':all(a['found'] and set(a['items'])=={'propext','Classical.choice','Quot.sound'} for a in axioms),'axioms_file_matches_log':' '.join((b/'axioms.txt').read_text().split())==' '.join('\n'.join(re.findall(r"'[^']+' depends on axioms: \[.*?\]",log,re.S)).split())}
 if key.startswith('r335'):
  ad=json.loads((ss/'r335-prefix-pair-inverse-raw/raw-adapter.json').read_text()); lean=target.read_text(); bind=(ss/'aspis-focus-1790936018208299000.log').read_text(); inp=base/'evidence/r305-current-batch-reverse-raw/raw-adapter-audit/provenance/R292Funs.input.lean'
  checks.update({'R292_input_hash_matches':hashlib.sha256(inp.read_bytes()).hexdigest()==ad['source_sha256']=='4d40a5b7b540adec90efef80a5ed8a5b4403704b388506af21f357761d95aec4','both_source_fragments_exact':all(f['exact'] and lean.count(f['text'])==1 for f in ad['fragments']),'no_operation_replacements':ad['operation_replacements']==0,'binding_probe_success': 'Exit status: 0' in bind,'binding_probe_resolves_private_mul_inv_and_slice_last':all(x in bind for x in ['AspisR249R110Raw.circle_norm.joined_inverse.line_norm.r110_norm.B.mul p q','AspisR278PrivateInverseRaw.circle_norm.joined_inverse.line_norm.r110_norm.B.inv b5','AspisR316SliceLastRaw.core.slice.Slice.last s2','AspisR316SliceLastRaw.core.slice.Slice.last s3'])})
 else:
  lean=target.read_text(); theorem=lean.split('theorem initialized_pair_inverse',1)[1].split(':= by',1)[0]
  checks.update({'second_prefix_equality_proved_rfl':'selectedPrefix1 ys = AspisR328PrefixInitializationRaw.selectedPrefix0 ys := by\n  rfl' in lean,'nonempty_encoded_read_conditions_explicit':'(hx : 0 < xs.val.length) (hy : 0 < ys.val.length)' in theorem and 'xs.val[j]? = some (encodeBase (f j))' in theorem and 'ys.val[j]? = some (encodeBase (g j))' in theorem,'no_capacity_or_nonzero_premise':'hcap' not in theorem and '≠ 0' not in theorem and 'nonzero' not in theorem.lower(),'inverse_zero_failure_explicit':'if p * q = 0 then .fail .assertionFailure' in lean and 'then .fail .assertionFailure' in theorem})
 bundles.append({'evidence':key,'manifest':m,'checksums':checksums,'axioms':axioms,'checks':checks,'result':'PASS' if all(checks.values()) else 'DISCREPANCY'})
attempts=[]
for n in [1,2]:
 d=ss/f'r336-development-history/attempt-{n}'; log=(d/'compile.log').read_text(); attempts.append({'attempt':n,'source_sha256':hashlib.sha256((d/'source.lean').read_bytes()).hexdigest(),'log_sha256':hashlib.sha256((d/'compile.log').read_bytes()).hexdigest(),'failed_exit1':'Exit status: 1' in log,'sorryAx_present_in_rejected_output':'sorryAx' in log,'source_retained':(d/'source.lean').exists()})
supplement={str(p.relative_to(repo)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [ss/'r335-prefix-pair-inverse-raw/build_raw.py',ss/'r335-prefix-pair-inverse-raw/raw-adapter.json',ss/'R335BindingInspect.lean',ss/'aspis-focus-1790936018208299000.log']}
report={'audit':'R335/R336 saved-evidence consistency audit','read_only':True,'no_compile_or_tracked_edits':True,'compile_revision':'d04d10ffd971f0821e29afcbb6d04528a2873f9c','current_checkout_revision':current,'revision_note':'Both successful runs completed at compile revision d04d10ffd971f0821e29afcbb6d04528a2873f9c. The checkout later advanced to 37d5dd7ecb2c6f7b98822147522b043884ef77d9 for R333 diagnostic evidence; the recorded compile commit is an ancestor. The initial checker compared the historical compile revision to new HEAD and was corrected; see revision-check-initial.json.','bundles':bundles,'scratch_supplement_hashes':supplement,'failed_drafts':attempts,'scope':'R335 contains two source-contiguous R292 fragments with no operation replacements: second-prefix initialization and shared last/unwrap/mul/inv/mul. Its exact R292 input hash is recorded, and successful binding inspection resolves B.mul, B.inv and Slice.last to existing selected definitions. R336 proves second-prefix equality by rfl, explicit empty-input arrayOutOfBounds, initialization under explicit nonempty and canonical encoded-read conditions, and pair inverse complete Result (zero total => assertionFailure; nonzero total => two encoded inverse seeds). Capacity is derived, zero products are allowed, and no nonzero premise is used. Full guard, reverse/output setup, independent Rust Std/compiler correspondence and whole callback/privacy/security remain open. The two failed drafts are retained, with sorryAx only in failed outputs.','overall':'PASS' if all(b['result']=='PASS' for b in bundles) and all(a['failed_exit1'] and a['sorryAx_present_in_rejected_output'] and a['source_retained'] for a in attempts) else 'DISCREPANCY'}
out=ss/'r336-saved-evidence-audit'; (out/'audit.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({'overall':report['overall'],'current':current,'bundle_checks':[{'evidence':b['evidence'],'result':b['result'],'checks':b['checks']} for b in bundles],'failed_drafts':attempts},indent=2))
