-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [aspis_v8_performance_host]: function definitions
import Aeneas.Std
import Aeneas.Tactic.RustAttributes
import AspisV8R19.R498UsizePrimitiveNames
import AspisR490AlignOffsets.Types
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace AspisR490AlignOffsets

/-- [core::mem::SizedTypeProperties::SIZE::<u8>]
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1379:4-1379:21
    Instantiated source name: [core::mem::SizedTypeProperties::SIZE::<u8>]
    Visibility: public -/
@[global_simps, irreducible, trait_default, rust_const
  "core::mem::SizedTypeProperties::SIZE<u8>"]
def
  core.mem.SizedTypeProperties.SIZE.default_mono_28ce8d95b2593a4923576aa3ad2ebabc
  : Std.Usize :=
  1#usize

/-- [core::mem::SizedTypeProperties::SIZE::<u32>]
    Source: '/rustc/library/core/src/mem/mod.rs', lines 1379:4-1379:21
    Instantiated source name: [core::mem::SizedTypeProperties::SIZE::<u32>]
    Visibility: public -/
@[global_simps, irreducible, trait_default, rust_const
  "core::mem::SizedTypeProperties::SIZE<u32>"]
def
  core.mem.SizedTypeProperties.SIZE.default_mono_e9319eea2781deb4b1add44e36347b0b
  : Std.Usize :=
  4#usize

/-- [core::slice::{[u8]}::align_to_offsets::<u8, u32>]:
    Source: '/rustc/library/core/src/slice/mod.rs', lines 4435:4-4435:51
    Instantiated source name: [core::slice::{[u8]}::align_to_offsets::<u8, u32>] -/
@[rust_fun "core::slice::{[u8]}::align_to_offsets<u8, u32>"]
def core.slice.SliceU8.align_to_offsets_mono_4c96ec488904b27cff1cab4fcd1cc6b4
  (self : Slice Std.U8) : Result (Std.Usize × Std.Usize) := do
  massert (¬ (1#usize = 0#usize))
  let ts ←
    Usize.div
      core.mem.SizedTypeProperties.SIZE.default_mono_e9319eea2781deb4b1add44e36347b0b
      1#usize
  let us ←
    Usize.div
      core.mem.SizedTypeProperties.SIZE.default_mono_28ce8d95b2593a4923576aa3ad2ebabc
      1#usize
  let i := Slice.len self
  massert (¬ (ts = 0#usize))
  let i1 ← Usize.div i ts
  let us_len ← lift (Std.Usize.wrapping_mul i1 us)
  let ts_len ← Usize.rem i ts
  ok (us_len, ts_len)

end AspisR490AlignOffsets
