[package]
name = "whir-jb-host"
edition = "2021"
license = "MIT"
version = "0.1.0"

[dependencies]
anyhow = "1.0.100"
ark-ff = "0.5"
serde = { version = "1.0.228", features = ["derive"] }
spongefish = { git = "https://github.com/arkworks-rs/spongefish", features = ["ark-ff"], rev = "fcc277f8a857fdeeadd7cca92ab08de63b1ff1a1" }
whir = { git = "https://github.com/WizardOfMenlo/whir", rev = "0aeaa7f337c743d9ddfcb9d909628d6491e3355c" }
