[package]
name = "circle-p3-verifier"
edition.workspace = true
license.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
custom-heap = []
custom-panic = []
no-entrypoint = []

[dependencies]
solana-program.workspace = true
circle-p3-core = { path = "../../crates/circle-p3-core", default-features = false }
