import AspisFormal.V7CompactFrontierDeltaCertificate.Depth11
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 12, chunk 0
Cells 0 through 6;
recurrence workload 89. -/

theorem certificate_12_2_5 :
    frontierCoeff 12 2 5 = 0 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 1 5,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 1 (5 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 1 5 = {0, 1, 2, 3, 4, 5} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 1 (5 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3, AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (2 - (offset + 1)) 5,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (2 - (offset + 1))
              (5 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (2 - (offset + 1)) 5,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (2 - (offset + 1))
                (5 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_2_4] <;> simp

theorem certificate_12_2_6 :
    frontierCoeff 12 2 6 = 0 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 1 6,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 1 (6 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 1 6 = {0, 1, 2, 3, 4, 5, 6} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 1 (6 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3, AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_6] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (2 - (offset + 1)) 6,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (2 - (offset + 1))
              (6 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (2 - (offset + 1)) 6,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (2 - (offset + 1))
                (6 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_2_5] <;> simp

theorem certificate_12_2_7 :
    frontierCoeff 12 2 7 = 0 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 1 7,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 1 (7 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 1 7 = {0, 1, 2, 3, 4, 5, 6, 7} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 1 (7 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3, AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_6, AspisV6CompactFrontierTailCertificate.certificate_11_1_7] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (2 - (offset + 1)) 7,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (2 - (offset + 1))
              (7 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (2 - (offset + 1)) 7,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (2 - (offset + 1))
                (7 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_2_6] <;> simp

theorem certificate_12_2_8 :
    frontierCoeff 12 2 8 = 0 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 1 8,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 1 (8 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 1 8 = {0, 1, 2, 3, 4, 5, 6, 7, 8} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 1 (8 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3, AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_6, AspisV6CompactFrontierTailCertificate.certificate_11_1_7, AspisV6CompactFrontierTailCertificate.certificate_11_1_8] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (2 - (offset + 1)) 8,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (2 - (offset + 1))
              (8 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (2 - (offset + 1)) 8,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (2 - (offset + 1))
                (8 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_2_7] <;> simp

theorem certificate_12_2_9 :
    frontierCoeff 12 2 9 = 0 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 1 9,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 1 (9 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 1 9 = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 1 (9 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3, AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_6, AspisV6CompactFrontierTailCertificate.certificate_11_1_7, AspisV6CompactFrontierTailCertificate.certificate_11_1_8, AspisV6CompactFrontierTailCertificate.certificate_11_1_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (2 - (offset + 1)) 9,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (2 - (offset + 1))
              (9 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (2 - (offset + 1)) 9,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (2 - (offset + 1))
                (9 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_2_8] <;> simp

theorem certificate_12_2_10 :
    frontierCoeff 12 2 10 = 0 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 1 10,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 1 (10 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 1 10 = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 1 (10 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_10, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3, AspisV6CompactFrontierTailCertificate.certificate_11_1_4,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_5, AspisV6CompactFrontierTailCertificate.certificate_11_1_6, AspisV6CompactFrontierTailCertificate.certificate_11_1_7, AspisV6CompactFrontierTailCertificate.certificate_11_1_8, AspisV6CompactFrontierTailCertificate.certificate_11_1_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (2 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (2 - (offset + 1)) 10,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (2 - (offset + 1))
              (10 - leftFrontier)) = 0 := by
    have offsets : Finset.range (2 - 1) = {0} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (2 - (offset + 1)) 10,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (2 - (offset + 1))
                (10 - leftFrontier)) =
          ∑ offset ∈ {0},
            if offset = 0 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [split0] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_2_9] <;> simp

theorem certificate_12_3_18 :
    frontierCoeff 12 3 18 = 8 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 2 18,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 2 (18 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 11 1 2 18 = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1, support_11_2]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 2 (18 - leftFrontier)) =
          ∑ leftFrontier ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
            if leftFrontier = 0 then 0 else if leftFrontier = 1 then 0 else if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else if leftFrontier = 11 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_10, AspisV6CompactFrontierTailCertificate.certificate_11_1_11, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5, AspisV6CompactFrontierTailCertificate.certificate_11_1_6, AspisV6CompactFrontierTailCertificate.certificate_11_1_7, AspisV6CompactFrontierTailCertificate.certificate_11_1_8, AspisV6CompactFrontierTailCertificate.certificate_11_1_9,
            AspisV6CompactFrontierTailCertificate.certificate_11_2_10, AspisV6CompactFrontierTailCertificate.certificate_11_2_11, AspisV6CompactFrontierTailCertificate.certificate_11_2_12, AspisV6CompactFrontierTailCertificate.certificate_11_2_13, AspisV6CompactFrontierTailCertificate.certificate_11_2_14, AspisV6CompactFrontierTailCertificate.certificate_11_2_15,
            AspisV6CompactFrontierTailCertificate.certificate_11_2_16, AspisV6CompactFrontierTailCertificate.certificate_11_2_17, AspisV6CompactFrontierTailCertificate.certificate_11_2_18, certificate_11_2_7, certificate_11_2_8, certificate_11_2_9] <;> simp
      _ = 0 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 2 1 18,
        frontierCoeff 11 2 leftFrontier *
          frontierCoeff 11 1 (18 - leftFrontier)) = 0 := by
    have live1 : supportedSplitFrontiers 11 2 1 18 = {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1, support_11_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18},
          frontierCoeff 11 2 leftFrontier *
            frontierCoeff 11 1 (18 - leftFrontier)) =
          ∑ leftFrontier ∈ {7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18},
            if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else if leftFrontier = 11 then 0 else if leftFrontier = 12 then 0 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 0 else if leftFrontier = 15 then 0 else if leftFrontier = 16 then 0 else if leftFrontier = 17 then 0 else if leftFrontier = 18 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_0, AspisV6CompactFrontierTailCertificate.certificate_11_1_1, AspisV6CompactFrontierTailCertificate.certificate_11_1_10, AspisV6CompactFrontierTailCertificate.certificate_11_1_11, AspisV6CompactFrontierTailCertificate.certificate_11_1_2, AspisV6CompactFrontierTailCertificate.certificate_11_1_3,
            AspisV6CompactFrontierTailCertificate.certificate_11_1_4, AspisV6CompactFrontierTailCertificate.certificate_11_1_5, AspisV6CompactFrontierTailCertificate.certificate_11_1_6, AspisV6CompactFrontierTailCertificate.certificate_11_1_7, AspisV6CompactFrontierTailCertificate.certificate_11_1_8, AspisV6CompactFrontierTailCertificate.certificate_11_1_9,
            AspisV6CompactFrontierTailCertificate.certificate_11_2_10, AspisV6CompactFrontierTailCertificate.certificate_11_2_11, AspisV6CompactFrontierTailCertificate.certificate_11_2_12, AspisV6CompactFrontierTailCertificate.certificate_11_2_13, AspisV6CompactFrontierTailCertificate.certificate_11_2_14, AspisV6CompactFrontierTailCertificate.certificate_11_2_15,
            AspisV6CompactFrontierTailCertificate.certificate_11_2_16, AspisV6CompactFrontierTailCertificate.certificate_11_2_17, AspisV6CompactFrontierTailCertificate.certificate_11_2_18, certificate_11_2_7, certificate_11_2_8, certificate_11_2_9] <;> simp
      _ = 0 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (3 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (3 - (offset + 1)) 18,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (3 - (offset + 1))
              (18 - leftFrontier)) = 0 := by
    have offsets : Finset.range (3 - 1) = {0, 1} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (3 - (offset + 1)) 18,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (3 - (offset + 1))
                (18 - leftFrontier)) =
          ∑ offset ∈ {0, 1},
            if offset = 0 then 0 else if offset = 1 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [split0, split1] <;> simp
      _ = 0 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_11_3_17] <;> simp

end AspisV7CompactFrontierDeltaCertificate
