import AspisFormal.V7CompactFrontierDeltaCertificate.Depth14
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 15, chunk 10
Cells 19 through 19;
recurrence workload 120. -/

theorem certificate_15_4_39 :
    frontierCoeff 15 4 39 = 116 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 3 39,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 3 (39 - leftFrontier)) = 14 := by
    have live0 : supportedSplitFrontiers 14 1 3 39 = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_14_1, AspisV6CompactFrontierTailCertificate.support_14_3]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
          frontierCoeff 14 1 leftFrontier *
            frontierCoeff 14 3 (39 - leftFrontier)) =
          ∑ leftFrontier ∈ {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else if leftFrontier = 11 then 0 else if leftFrontier = 12 then 0 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 14 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_1_10, AspisV6CompactFrontierTailCertificate.certificate_14_1_11, AspisV6CompactFrontierTailCertificate.certificate_14_1_12, AspisV6CompactFrontierTailCertificate.certificate_14_1_13, AspisV6CompactFrontierTailCertificate.certificate_14_1_14, AspisV6CompactFrontierTailCertificate.certificate_14_1_2,
            AspisV6CompactFrontierTailCertificate.certificate_14_1_3, AspisV6CompactFrontierTailCertificate.certificate_14_1_4, AspisV6CompactFrontierTailCertificate.certificate_14_1_5, AspisV6CompactFrontierTailCertificate.certificate_14_1_6, AspisV6CompactFrontierTailCertificate.certificate_14_1_7, AspisV6CompactFrontierTailCertificate.certificate_14_1_8,
            AspisV6CompactFrontierTailCertificate.certificate_14_1_9, certificate_14_3_25, AspisV6CompactFrontierTailCertificate.certificate_14_3_26, AspisV6CompactFrontierTailCertificate.certificate_14_3_27, AspisV6CompactFrontierTailCertificate.certificate_14_3_28, AspisV6CompactFrontierTailCertificate.certificate_14_3_29,
            AspisV6CompactFrontierTailCertificate.certificate_14_3_30, AspisV6CompactFrontierTailCertificate.certificate_14_3_31, AspisV6CompactFrontierTailCertificate.certificate_14_3_32, AspisV6CompactFrontierTailCertificate.certificate_14_3_33, AspisV6CompactFrontierTailCertificate.certificate_14_3_34, AspisV6CompactFrontierTailCertificate.certificate_14_3_35,
            AspisV6CompactFrontierTailCertificate.certificate_14_3_36, AspisV6CompactFrontierTailCertificate.certificate_14_3_37] <;> simp
      _ = 14 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 2 2 39,
        frontierCoeff 14 2 leftFrontier *
          frontierCoeff 14 2 (39 - leftFrontier)) = 14 := by
    have live1 : supportedSplitFrontiers 14 2 2 39 = {13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_14_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26},
          frontierCoeff 14 2 leftFrontier *
            frontierCoeff 14 2 (39 - leftFrontier)) =
          ∑ leftFrontier ∈ {13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26},
            if leftFrontier = 13 then 1 else if leftFrontier = 14 then 1 else if leftFrontier = 15 then 1 else if leftFrontier = 16 then 1 else if leftFrontier = 17 then 1 else if leftFrontier = 18 then 1 else if leftFrontier = 19 then 1 else if leftFrontier = 20 then 1 else if leftFrontier = 21 then 1 else if leftFrontier = 22 then 1 else if leftFrontier = 23 then 1 else if leftFrontier = 24 then 1 else if leftFrontier = 25 then 1 else if leftFrontier = 26 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_2_13, AspisV6CompactFrontierTailCertificate.certificate_14_2_14, AspisV6CompactFrontierTailCertificate.certificate_14_2_15, AspisV6CompactFrontierTailCertificate.certificate_14_2_16, AspisV6CompactFrontierTailCertificate.certificate_14_2_17, AspisV6CompactFrontierTailCertificate.certificate_14_2_18,
            AspisV6CompactFrontierTailCertificate.certificate_14_2_19, AspisV6CompactFrontierTailCertificate.certificate_14_2_20, AspisV6CompactFrontierTailCertificate.certificate_14_2_21, AspisV6CompactFrontierTailCertificate.certificate_14_2_22, AspisV6CompactFrontierTailCertificate.certificate_14_2_23, AspisV6CompactFrontierTailCertificate.certificate_14_2_24,
            AspisV6CompactFrontierTailCertificate.certificate_14_2_25, AspisV6CompactFrontierTailCertificate.certificate_14_2_26] <;> simp
      _ = 14 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 3 1 39,
        frontierCoeff 14 3 leftFrontier *
          frontierCoeff 14 1 (39 - leftFrontier)) = 14 := by
    have live2 : supportedSplitFrontiers 14 3 1 39 = {25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_14_1, AspisV6CompactFrontierTailCertificate.support_14_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37},
          frontierCoeff 14 3 leftFrontier *
            frontierCoeff 14 1 (39 - leftFrontier)) =
          ∑ leftFrontier ∈ {25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37},
            if leftFrontier = 25 then 14 else if leftFrontier = 26 then 0 else if leftFrontier = 27 then 0 else if leftFrontier = 28 then 0 else if leftFrontier = 29 then 0 else if leftFrontier = 30 then 0 else if leftFrontier = 31 then 0 else if leftFrontier = 32 then 0 else if leftFrontier = 33 then 0 else if leftFrontier = 34 then 0 else if leftFrontier = 35 then 0 else if leftFrontier = 36 then 0 else if leftFrontier = 37 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_1_10, AspisV6CompactFrontierTailCertificate.certificate_14_1_11, AspisV6CompactFrontierTailCertificate.certificate_14_1_12, AspisV6CompactFrontierTailCertificate.certificate_14_1_13, AspisV6CompactFrontierTailCertificate.certificate_14_1_14, AspisV6CompactFrontierTailCertificate.certificate_14_1_2,
            AspisV6CompactFrontierTailCertificate.certificate_14_1_3, AspisV6CompactFrontierTailCertificate.certificate_14_1_4, AspisV6CompactFrontierTailCertificate.certificate_14_1_5, AspisV6CompactFrontierTailCertificate.certificate_14_1_6, AspisV6CompactFrontierTailCertificate.certificate_14_1_7, AspisV6CompactFrontierTailCertificate.certificate_14_1_8,
            AspisV6CompactFrontierTailCertificate.certificate_14_1_9, certificate_14_3_25, AspisV6CompactFrontierTailCertificate.certificate_14_3_26, AspisV6CompactFrontierTailCertificate.certificate_14_3_27, AspisV6CompactFrontierTailCertificate.certificate_14_3_28, AspisV6CompactFrontierTailCertificate.certificate_14_3_29,
            AspisV6CompactFrontierTailCertificate.certificate_14_3_30, AspisV6CompactFrontierTailCertificate.certificate_14_3_31, AspisV6CompactFrontierTailCertificate.certificate_14_3_32, AspisV6CompactFrontierTailCertificate.certificate_14_3_33, AspisV6CompactFrontierTailCertificate.certificate_14_3_34, AspisV6CompactFrontierTailCertificate.certificate_14_3_35,
            AspisV6CompactFrontierTailCertificate.certificate_14_3_36, AspisV6CompactFrontierTailCertificate.certificate_14_3_37] <;> simp
      _ = 14 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (4 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (4 - (offset + 1)) 39,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (4 - (offset + 1))
              (39 - leftFrontier)) = 42 := by
    have offsets : Finset.range (4 - 1) = {0, 1, 2} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (4 - (offset + 1)) 39,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (4 - (offset + 1))
                (39 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2},
            if offset = 0 then 14 else if offset = 1 then 14 else if offset = 2 then 14 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2] <;> simp
      _ = 42 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_14_4_38] <;> simp

end AspisV7CompactFrontierDeltaCertificate
