import AspisFormal.V7CompactFrontierDeltaCertificate.Depth12
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 13, chunk 3
Cells 11 through 11;
recurrence workload 50. -/

theorem certificate_13_3_24 :
    frontierCoeff 13 3 24 = 12 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 12 1 2 24,
        frontierCoeff 12 1 leftFrontier *
          frontierCoeff 12 2 (24 - leftFrontier)) = 1 := by
    have live0 : supportedSplitFrontiers 12 1 2 24 = {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_12_1, AspisV6CompactFrontierTailCertificate.support_12_2]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12},
          frontierCoeff 12 1 leftFrontier *
            frontierCoeff 12 2 (24 - leftFrontier)) =
          ∑ leftFrontier ∈ {2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12},
            if leftFrontier = 2 then 0 else if leftFrontier = 3 then 0 else if leftFrontier = 4 then 0 else if leftFrontier = 5 then 0 else if leftFrontier = 6 then 0 else if leftFrontier = 7 then 0 else if leftFrontier = 8 then 0 else if leftFrontier = 9 then 0 else if leftFrontier = 10 then 0 else if leftFrontier = 11 then 0 else if leftFrontier = 12 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_12_1_10, AspisV6CompactFrontierTailCertificate.certificate_12_1_11, AspisV6CompactFrontierTailCertificate.certificate_12_1_12, AspisV6CompactFrontierTailCertificate.certificate_12_1_2, AspisV6CompactFrontierTailCertificate.certificate_12_1_3, AspisV6CompactFrontierTailCertificate.certificate_12_1_4,
            AspisV6CompactFrontierTailCertificate.certificate_12_1_5, AspisV6CompactFrontierTailCertificate.certificate_12_1_6, AspisV6CompactFrontierTailCertificate.certificate_12_1_7, AspisV6CompactFrontierTailCertificate.certificate_12_1_8, AspisV6CompactFrontierTailCertificate.certificate_12_1_9, AspisV6CompactFrontierTailCertificate.certificate_12_2_12,
            AspisV6CompactFrontierTailCertificate.certificate_12_2_13, AspisV6CompactFrontierTailCertificate.certificate_12_2_14, AspisV6CompactFrontierTailCertificate.certificate_12_2_15, AspisV6CompactFrontierTailCertificate.certificate_12_2_16, AspisV6CompactFrontierTailCertificate.certificate_12_2_17, AspisV6CompactFrontierTailCertificate.certificate_12_2_18,
            AspisV6CompactFrontierTailCertificate.certificate_12_2_19, AspisV6CompactFrontierTailCertificate.certificate_12_2_20, AspisV6CompactFrontierTailCertificate.certificate_12_2_21, AspisV6CompactFrontierTailCertificate.certificate_12_2_22] <;> simp
      _ = 1 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 12 2 1 24,
        frontierCoeff 12 2 leftFrontier *
          frontierCoeff 12 1 (24 - leftFrontier)) = 1 := by
    have live1 : supportedSplitFrontiers 12 2 1 24 = {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_12_1, AspisV6CompactFrontierTailCertificate.support_12_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22},
          frontierCoeff 12 2 leftFrontier *
            frontierCoeff 12 1 (24 - leftFrontier)) =
          ∑ leftFrontier ∈ {12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22},
            if leftFrontier = 12 then 1 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 0 else if leftFrontier = 15 then 0 else if leftFrontier = 16 then 0 else if leftFrontier = 17 then 0 else if leftFrontier = 18 then 0 else if leftFrontier = 19 then 0 else if leftFrontier = 20 then 0 else if leftFrontier = 21 then 0 else if leftFrontier = 22 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_12_1_10, AspisV6CompactFrontierTailCertificate.certificate_12_1_11, AspisV6CompactFrontierTailCertificate.certificate_12_1_12, AspisV6CompactFrontierTailCertificate.certificate_12_1_2, AspisV6CompactFrontierTailCertificate.certificate_12_1_3, AspisV6CompactFrontierTailCertificate.certificate_12_1_4,
            AspisV6CompactFrontierTailCertificate.certificate_12_1_5, AspisV6CompactFrontierTailCertificate.certificate_12_1_6, AspisV6CompactFrontierTailCertificate.certificate_12_1_7, AspisV6CompactFrontierTailCertificate.certificate_12_1_8, AspisV6CompactFrontierTailCertificate.certificate_12_1_9, AspisV6CompactFrontierTailCertificate.certificate_12_2_12,
            AspisV6CompactFrontierTailCertificate.certificate_12_2_13, AspisV6CompactFrontierTailCertificate.certificate_12_2_14, AspisV6CompactFrontierTailCertificate.certificate_12_2_15, AspisV6CompactFrontierTailCertificate.certificate_12_2_16, AspisV6CompactFrontierTailCertificate.certificate_12_2_17, AspisV6CompactFrontierTailCertificate.certificate_12_2_18,
            AspisV6CompactFrontierTailCertificate.certificate_12_2_19, AspisV6CompactFrontierTailCertificate.certificate_12_2_20, AspisV6CompactFrontierTailCertificate.certificate_12_2_21, AspisV6CompactFrontierTailCertificate.certificate_12_2_22] <;> simp
      _ = 1 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (3 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 12 (offset + 1)
            (3 - (offset + 1)) 24,
          frontierCoeff 12 (offset + 1) leftFrontier *
            frontierCoeff 12 (3 - (offset + 1))
              (24 - leftFrontier)) = 2 := by
    have offsets : Finset.range (3 - 1) = {0, 1} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1},
          ∑ leftFrontier ∈ supportedSplitFrontiers 12 (offset + 1)
              (3 - (offset + 1)) 24,
            frontierCoeff 12 (offset + 1) leftFrontier *
              frontierCoeff 12 (3 - (offset + 1))
                (24 - leftFrontier)) =
          ∑ offset ∈ {0, 1},
            if offset = 0 then 1 else if offset = 1 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [split0, split1] <;> simp
      _ = 2 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_12_3_23] <;> simp

end AspisV7CompactFrontierDeltaCertificate
