import AspisFormal.V7CompactFrontierDeltaCertificate.Depth16
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 17, chunk 74
Cells 84 through 84;
recurrence workload 2632. -/

theorem certificate_17_15_187 :
    frontierCoeff 17 15 187 = 18123384 := by
  have zero_16_15_186 :
      frontierCoeff 16 15 186 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 1 14 187,
        frontierCoeff 16 1 leftFrontier *
          frontierCoeff 16 14 (187 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 16 1 14 187 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_14]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 2 13 187,
        frontierCoeff 16 2 leftFrontier *
          frontierCoeff 16 13 (187 - leftFrontier)) = 5852 := by
    have live1 : supportedSplitFrontiers 16 2 13 187 = {28, 29, 30} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_13, support_16_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {28, 29, 30},
          frontierCoeff 16 2 leftFrontier *
            frontierCoeff 16 13 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {28, 29, 30},
            if leftFrontier = 28 then 56 else if leftFrontier = 29 then 868 else if leftFrontier = 30 then 4928 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_16_13_157, certificate_16_13_158, certificate_16_13_159, AspisV6CompactFrontierTailCertificate.certificate_16_2_28, AspisV6CompactFrontierTailCertificate.certificate_16_2_29, AspisV6CompactFrontierTailCertificate.certificate_16_2_30] <;> simp
      _ = 5852 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 3 12 187,
        frontierCoeff 16 3 leftFrontier *
          frontierCoeff 16 12 (187 - leftFrontier)) = 115656 := by
    have live2 : supportedSplitFrontiers 16 3 12 187 = {39, 40, 41, 42, 43} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_12, support_16_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {39, 40, 41, 42, 43},
          frontierCoeff 16 3 leftFrontier *
            frontierCoeff 16 12 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {39, 40, 41, 42, 43},
            if leftFrontier = 39 then 420 else if leftFrontier = 40 then 2800 else if leftFrontier = 41 then 13688 else if leftFrontier = 42 then 25212 else if leftFrontier = 43 then 73536 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_12_144, certificate_16_12_145, certificate_16_12_146, certificate_16_12_147, AspisV6CompactFrontierTailCertificate.certificate_16_12_148, AspisV6CompactFrontierTailCertificate.certificate_16_3_39,
            AspisV6CompactFrontierTailCertificate.certificate_16_3_40, AspisV6CompactFrontierTailCertificate.certificate_16_3_41, AspisV6CompactFrontierTailCertificate.certificate_16_3_42, AspisV6CompactFrontierTailCertificate.certificate_16_3_43] <;> simp
      _ = 115656 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 4 11 187,
        frontierCoeff 16 4 leftFrontier *
          frontierCoeff 16 11 (187 - leftFrontier)) = 596536 := by
    have live3 : supportedSplitFrontiers 16 4 11 187 = {50, 51, 52, 53, 54, 55, 56} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {50, 51, 52, 53, 54, 55, 56},
          frontierCoeff 16 4 leftFrontier *
            frontierCoeff 16 11 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {50, 51, 52, 53, 54, 55, 56},
            if leftFrontier = 50 then 1792 else if leftFrontier = 51 then 10500 else if leftFrontier = 52 then 38076 else if leftFrontier = 53 then 83096 else if leftFrontier = 54 then 123592 else if leftFrontier = 55 then 249312 else if leftFrontier = 56 then 90168 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_11_131, certificate_16_11_132, certificate_16_11_133, AspisV6CompactFrontierTailCertificate.certificate_16_11_134, AspisV6CompactFrontierTailCertificate.certificate_16_11_135, AspisV6CompactFrontierTailCertificate.certificate_16_11_136,
            AspisV6CompactFrontierTailCertificate.certificate_16_11_137, AspisV6CompactFrontierTailCertificate.certificate_16_4_50, AspisV6CompactFrontierTailCertificate.certificate_16_4_51, AspisV6CompactFrontierTailCertificate.certificate_16_4_52, AspisV6CompactFrontierTailCertificate.certificate_16_4_53, AspisV6CompactFrontierTailCertificate.certificate_16_4_54,
            AspisV6CompactFrontierTailCertificate.certificate_16_4_55, AspisV6CompactFrontierTailCertificate.certificate_16_4_56] <;> simp
      _ = 596536 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 5 10 187,
        frontierCoeff 16 5 leftFrontier *
          frontierCoeff 16 10 (187 - leftFrontier)) = 1616048 := by
    have live4 : supportedSplitFrontiers 16 5 10 187 = {61, 62, 63, 64, 65, 66, 67, 68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {61, 62, 63, 64, 65, 66, 67, 68},
          frontierCoeff 16 5 leftFrontier *
            frontierCoeff 16 10 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {61, 62, 63, 64, 65, 66, 67, 68},
            if leftFrontier = 61 then 5096 else if leftFrontier = 62 then 30104 else if leftFrontier = 63 then 90816 else if leftFrontier = 64 then 184668 else if leftFrontier = 65 then 274740 else if leftFrontier = 66 then 451304 else if leftFrontier = 67 then 329240 else if leftFrontier = 68 then 250080 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_10_119, AspisV6CompactFrontierTailCertificate.certificate_16_10_120, AspisV6CompactFrontierTailCertificate.certificate_16_10_121, AspisV6CompactFrontierTailCertificate.certificate_16_10_122, AspisV6CompactFrontierTailCertificate.certificate_16_10_123, AspisV6CompactFrontierTailCertificate.certificate_16_10_124,
            AspisV6CompactFrontierTailCertificate.certificate_16_10_125, AspisV6CompactFrontierTailCertificate.certificate_16_10_126, AspisV6CompactFrontierTailCertificate.certificate_16_5_61, AspisV6CompactFrontierTailCertificate.certificate_16_5_62, AspisV6CompactFrontierTailCertificate.certificate_16_5_63, AspisV6CompactFrontierTailCertificate.certificate_16_5_64,
            AspisV6CompactFrontierTailCertificate.certificate_16_5_65, AspisV6CompactFrontierTailCertificate.certificate_16_5_66, AspisV6CompactFrontierTailCertificate.certificate_16_5_67, AspisV6CompactFrontierTailCertificate.certificate_16_5_68] <;> simp
      _ = 1616048 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 6 9 187,
        frontierCoeff 16 6 leftFrontier *
          frontierCoeff 16 9 (187 - leftFrontier)) = 2904956 := by
    have live5 : supportedSplitFrontiers 16 6 9 187 = {72, 73, 74, 75, 76, 77, 78, 79, 80} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_6, support_16_9]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {72, 73, 74, 75, 76, 77, 78, 79, 80},
          frontierCoeff 16 6 leftFrontier *
            frontierCoeff 16 9 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {72, 73, 74, 75, 76, 77, 78, 79, 80},
            if leftFrontier = 72 then 8016 else if leftFrontier = 73 then 64400 else if leftFrontier = 74 then 168960 else if leftFrontier = 75 then 333184 else if leftFrontier = 76 then 514488 else if leftFrontier = 77 then 586816 else if leftFrontier = 78 then 598304 else if leftFrontier = 79 then 430496 else if leftFrontier = 80 then 200292 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_6_72, AspisV6CompactFrontierTailCertificate.certificate_16_6_73, AspisV6CompactFrontierTailCertificate.certificate_16_6_74, AspisV6CompactFrontierTailCertificate.certificate_16_6_75, AspisV6CompactFrontierTailCertificate.certificate_16_6_76, AspisV6CompactFrontierTailCertificate.certificate_16_6_77,
            AspisV6CompactFrontierTailCertificate.certificate_16_6_78, AspisV6CompactFrontierTailCertificate.certificate_16_6_79, AspisV6CompactFrontierTailCertificate.certificate_16_6_80, AspisV6CompactFrontierTailCertificate.certificate_16_9_107, AspisV6CompactFrontierTailCertificate.certificate_16_9_108, AspisV6CompactFrontierTailCertificate.certificate_16_9_109,
            AspisV6CompactFrontierTailCertificate.certificate_16_9_110, AspisV6CompactFrontierTailCertificate.certificate_16_9_111, AspisV6CompactFrontierTailCertificate.certificate_16_9_112, AspisV6CompactFrontierTailCertificate.certificate_16_9_113, AspisV6CompactFrontierTailCertificate.certificate_16_9_114, AspisV6CompactFrontierTailCertificate.certificate_16_9_115] <;> simp
      _ = 2904956 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 7 8 187,
        frontierCoeff 16 7 leftFrontier *
          frontierCoeff 16 8 (187 - leftFrontier)) = 3822644 := by
    have live6 : supportedSplitFrontiers 16 7 8 187 = {83, 84, 85, 86, 87, 88, 89, 90, 91, 92} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_7, support_16_8]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {83, 84, 85, 86, 87, 88, 89, 90, 91, 92},
          frontierCoeff 16 7 leftFrontier *
            frontierCoeff 16 8 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {83, 84, 85, 86, 87, 88, 89, 90, 91, 92},
            if leftFrontier = 83 then 4864 else if leftFrontier = 84 then 91504 else if leftFrontier = 85 then 261488 else if leftFrontier = 86 then 474600 else if leftFrontier = 87 then 655080 else if leftFrontier = 88 then 752640 else if leftFrontier = 89 then 720824 else if leftFrontier = 90 then 482152 else if leftFrontier = 91 then 322668 else if leftFrontier = 92 then 56824 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_7_83, AspisV6CompactFrontierTailCertificate.certificate_16_7_84, AspisV6CompactFrontierTailCertificate.certificate_16_7_85, AspisV6CompactFrontierTailCertificate.certificate_16_7_86, AspisV6CompactFrontierTailCertificate.certificate_16_7_87, AspisV6CompactFrontierTailCertificate.certificate_16_7_88,
            AspisV6CompactFrontierTailCertificate.certificate_16_7_89, AspisV6CompactFrontierTailCertificate.certificate_16_7_90, AspisV6CompactFrontierTailCertificate.certificate_16_7_91, AspisV6CompactFrontierTailCertificate.certificate_16_7_92, AspisV6CompactFrontierTailCertificate.certificate_16_8_100, AspisV6CompactFrontierTailCertificate.certificate_16_8_101,
            AspisV6CompactFrontierTailCertificate.certificate_16_8_102, AspisV6CompactFrontierTailCertificate.certificate_16_8_103, AspisV6CompactFrontierTailCertificate.certificate_16_8_104, AspisV6CompactFrontierTailCertificate.certificate_16_8_95, AspisV6CompactFrontierTailCertificate.certificate_16_8_96, AspisV6CompactFrontierTailCertificate.certificate_16_8_97,
            AspisV6CompactFrontierTailCertificate.certificate_16_8_98, AspisV6CompactFrontierTailCertificate.certificate_16_8_99] <;> simp
      _ = 3822644 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 8 7 187,
        frontierCoeff 16 8 leftFrontier *
          frontierCoeff 16 7 (187 - leftFrontier)) = 3822644 := by
    have live7 : supportedSplitFrontiers 16 8 7 187 = {95, 96, 97, 98, 99, 100, 101, 102, 103, 104} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_7, support_16_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {95, 96, 97, 98, 99, 100, 101, 102, 103, 104},
          frontierCoeff 16 8 leftFrontier *
            frontierCoeff 16 7 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {95, 96, 97, 98, 99, 100, 101, 102, 103, 104},
            if leftFrontier = 95 then 56824 else if leftFrontier = 96 then 322668 else if leftFrontier = 97 then 482152 else if leftFrontier = 98 then 720824 else if leftFrontier = 99 then 752640 else if leftFrontier = 100 then 655080 else if leftFrontier = 101 then 474600 else if leftFrontier = 102 then 261488 else if leftFrontier = 103 then 91504 else if leftFrontier = 104 then 4864 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_7_83, AspisV6CompactFrontierTailCertificate.certificate_16_7_84, AspisV6CompactFrontierTailCertificate.certificate_16_7_85, AspisV6CompactFrontierTailCertificate.certificate_16_7_86, AspisV6CompactFrontierTailCertificate.certificate_16_7_87, AspisV6CompactFrontierTailCertificate.certificate_16_7_88,
            AspisV6CompactFrontierTailCertificate.certificate_16_7_89, AspisV6CompactFrontierTailCertificate.certificate_16_7_90, AspisV6CompactFrontierTailCertificate.certificate_16_7_91, AspisV6CompactFrontierTailCertificate.certificate_16_7_92, AspisV6CompactFrontierTailCertificate.certificate_16_8_100, AspisV6CompactFrontierTailCertificate.certificate_16_8_101,
            AspisV6CompactFrontierTailCertificate.certificate_16_8_102, AspisV6CompactFrontierTailCertificate.certificate_16_8_103, AspisV6CompactFrontierTailCertificate.certificate_16_8_104, AspisV6CompactFrontierTailCertificate.certificate_16_8_95, AspisV6CompactFrontierTailCertificate.certificate_16_8_96, AspisV6CompactFrontierTailCertificate.certificate_16_8_97,
            AspisV6CompactFrontierTailCertificate.certificate_16_8_98, AspisV6CompactFrontierTailCertificate.certificate_16_8_99] <;> simp
      _ = 3822644 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 9 6 187,
        frontierCoeff 16 9 leftFrontier *
          frontierCoeff 16 6 (187 - leftFrontier)) = 2904956 := by
    have live8 : supportedSplitFrontiers 16 9 6 187 = {107, 108, 109, 110, 111, 112, 113, 114, 115} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_6, support_16_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {107, 108, 109, 110, 111, 112, 113, 114, 115},
          frontierCoeff 16 9 leftFrontier *
            frontierCoeff 16 6 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {107, 108, 109, 110, 111, 112, 113, 114, 115},
            if leftFrontier = 107 then 200292 else if leftFrontier = 108 then 430496 else if leftFrontier = 109 then 598304 else if leftFrontier = 110 then 586816 else if leftFrontier = 111 then 514488 else if leftFrontier = 112 then 333184 else if leftFrontier = 113 then 168960 else if leftFrontier = 114 then 64400 else if leftFrontier = 115 then 8016 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_6_72, AspisV6CompactFrontierTailCertificate.certificate_16_6_73, AspisV6CompactFrontierTailCertificate.certificate_16_6_74, AspisV6CompactFrontierTailCertificate.certificate_16_6_75, AspisV6CompactFrontierTailCertificate.certificate_16_6_76, AspisV6CompactFrontierTailCertificate.certificate_16_6_77,
            AspisV6CompactFrontierTailCertificate.certificate_16_6_78, AspisV6CompactFrontierTailCertificate.certificate_16_6_79, AspisV6CompactFrontierTailCertificate.certificate_16_6_80, AspisV6CompactFrontierTailCertificate.certificate_16_9_107, AspisV6CompactFrontierTailCertificate.certificate_16_9_108, AspisV6CompactFrontierTailCertificate.certificate_16_9_109,
            AspisV6CompactFrontierTailCertificate.certificate_16_9_110, AspisV6CompactFrontierTailCertificate.certificate_16_9_111, AspisV6CompactFrontierTailCertificate.certificate_16_9_112, AspisV6CompactFrontierTailCertificate.certificate_16_9_113, AspisV6CompactFrontierTailCertificate.certificate_16_9_114, AspisV6CompactFrontierTailCertificate.certificate_16_9_115] <;> simp
      _ = 2904956 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 10 5 187,
        frontierCoeff 16 10 leftFrontier *
          frontierCoeff 16 5 (187 - leftFrontier)) = 1616048 := by
    have live9 : supportedSplitFrontiers 16 10 5 187 = {119, 120, 121, 122, 123, 124, 125, 126} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_5]
      ext value
      simp <;> omega
    rw [live9]
    calc
      (∑ leftFrontier ∈ {119, 120, 121, 122, 123, 124, 125, 126},
          frontierCoeff 16 10 leftFrontier *
            frontierCoeff 16 5 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {119, 120, 121, 122, 123, 124, 125, 126},
            if leftFrontier = 119 then 250080 else if leftFrontier = 120 then 329240 else if leftFrontier = 121 then 451304 else if leftFrontier = 122 then 274740 else if leftFrontier = 123 then 184668 else if leftFrontier = 124 then 90816 else if leftFrontier = 125 then 30104 else if leftFrontier = 126 then 5096 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_10_119, AspisV6CompactFrontierTailCertificate.certificate_16_10_120, AspisV6CompactFrontierTailCertificate.certificate_16_10_121, AspisV6CompactFrontierTailCertificate.certificate_16_10_122, AspisV6CompactFrontierTailCertificate.certificate_16_10_123, AspisV6CompactFrontierTailCertificate.certificate_16_10_124,
            AspisV6CompactFrontierTailCertificate.certificate_16_10_125, AspisV6CompactFrontierTailCertificate.certificate_16_10_126, AspisV6CompactFrontierTailCertificate.certificate_16_5_61, AspisV6CompactFrontierTailCertificate.certificate_16_5_62, AspisV6CompactFrontierTailCertificate.certificate_16_5_63, AspisV6CompactFrontierTailCertificate.certificate_16_5_64,
            AspisV6CompactFrontierTailCertificate.certificate_16_5_65, AspisV6CompactFrontierTailCertificate.certificate_16_5_66, AspisV6CompactFrontierTailCertificate.certificate_16_5_67, AspisV6CompactFrontierTailCertificate.certificate_16_5_68] <;> simp
      _ = 1616048 := by norm_num
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 11 4 187,
        frontierCoeff 16 11 leftFrontier *
          frontierCoeff 16 4 (187 - leftFrontier)) = 596536 := by
    have live10 : supportedSplitFrontiers 16 11 4 187 = {131, 132, 133, 134, 135, 136, 137} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_4]
      ext value
      simp <;> omega
    rw [live10]
    calc
      (∑ leftFrontier ∈ {131, 132, 133, 134, 135, 136, 137},
          frontierCoeff 16 11 leftFrontier *
            frontierCoeff 16 4 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {131, 132, 133, 134, 135, 136, 137},
            if leftFrontier = 131 then 90168 else if leftFrontier = 132 then 249312 else if leftFrontier = 133 then 123592 else if leftFrontier = 134 then 83096 else if leftFrontier = 135 then 38076 else if leftFrontier = 136 then 10500 else if leftFrontier = 137 then 1792 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_11_131, certificate_16_11_132, certificate_16_11_133, AspisV6CompactFrontierTailCertificate.certificate_16_11_134, AspisV6CompactFrontierTailCertificate.certificate_16_11_135, AspisV6CompactFrontierTailCertificate.certificate_16_11_136,
            AspisV6CompactFrontierTailCertificate.certificate_16_11_137, AspisV6CompactFrontierTailCertificate.certificate_16_4_50, AspisV6CompactFrontierTailCertificate.certificate_16_4_51, AspisV6CompactFrontierTailCertificate.certificate_16_4_52, AspisV6CompactFrontierTailCertificate.certificate_16_4_53, AspisV6CompactFrontierTailCertificate.certificate_16_4_54,
            AspisV6CompactFrontierTailCertificate.certificate_16_4_55, AspisV6CompactFrontierTailCertificate.certificate_16_4_56] <;> simp
      _ = 596536 := by norm_num
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 12 3 187,
        frontierCoeff 16 12 leftFrontier *
          frontierCoeff 16 3 (187 - leftFrontier)) = 115656 := by
    have live11 : supportedSplitFrontiers 16 12 3 187 = {144, 145, 146, 147, 148} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_12, support_16_3]
      ext value
      simp <;> omega
    rw [live11]
    calc
      (∑ leftFrontier ∈ {144, 145, 146, 147, 148},
          frontierCoeff 16 12 leftFrontier *
            frontierCoeff 16 3 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {144, 145, 146, 147, 148},
            if leftFrontier = 144 then 73536 else if leftFrontier = 145 then 25212 else if leftFrontier = 146 then 13688 else if leftFrontier = 147 then 2800 else if leftFrontier = 148 then 420 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [certificate_16_12_144, certificate_16_12_145, certificate_16_12_146, certificate_16_12_147, AspisV6CompactFrontierTailCertificate.certificate_16_12_148, AspisV6CompactFrontierTailCertificate.certificate_16_3_39,
            AspisV6CompactFrontierTailCertificate.certificate_16_3_40, AspisV6CompactFrontierTailCertificate.certificate_16_3_41, AspisV6CompactFrontierTailCertificate.certificate_16_3_42, AspisV6CompactFrontierTailCertificate.certificate_16_3_43] <;> simp
      _ = 115656 := by norm_num
  have split12 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 13 2 187,
        frontierCoeff 16 13 leftFrontier *
          frontierCoeff 16 2 (187 - leftFrontier)) = 5852 := by
    have live12 : supportedSplitFrontiers 16 13 2 187 = {157, 158, 159} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_13, support_16_2]
      ext value
      simp <;> omega
    rw [live12]
    calc
      (∑ leftFrontier ∈ {157, 158, 159},
          frontierCoeff 16 13 leftFrontier *
            frontierCoeff 16 2 (187 - leftFrontier)) =
          ∑ leftFrontier ∈ {157, 158, 159},
            if leftFrontier = 157 then 4928 else if leftFrontier = 158 then 868 else if leftFrontier = 159 then 56 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [certificate_16_13_157, certificate_16_13_158, certificate_16_13_159, AspisV6CompactFrontierTailCertificate.certificate_16_2_28, AspisV6CompactFrontierTailCertificate.certificate_16_2_29, AspisV6CompactFrontierTailCertificate.certificate_16_2_30] <;> simp
      _ = 5852 := by norm_num
  have split13 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 14 1 187,
        frontierCoeff 16 14 leftFrontier *
          frontierCoeff 16 1 (187 - leftFrontier)) = 0 := by
    have live13 : supportedSplitFrontiers 16 14 1 187 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_14]
      ext value
      simp <;> omega
    rw [live13]
    simp
  have outer :
      (∑ offset ∈ Finset.range (15 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
            (15 - (offset + 1)) 187,
          frontierCoeff 16 (offset + 1) leftFrontier *
            frontierCoeff 16 (15 - (offset + 1))
              (187 - leftFrontier)) = 18123384 := by
    have offsets : Finset.range (15 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13},
          ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
              (15 - (offset + 1)) 187,
            frontierCoeff 16 (offset + 1) leftFrontier *
              frontierCoeff 16 (15 - (offset + 1))
                (187 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13},
            if offset = 0 then 0 else if offset = 1 then 5852 else if offset = 2 then 115656 else if offset = 3 then 596536 else if offset = 4 then 1616048 else if offset = 5 then 2904956 else if offset = 6 then 3822644 else if offset = 7 then 3822644 else if offset = 8 then 2904956 else if offset = 9 then 1616048 else if offset = 10 then 596536 else if offset = 11 then 115656 else if offset = 12 then 5852 else if offset = 13 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11,
            split12, split13] <;> simp
      _ = 18123384 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_16_15_186] <;> simp

end AspisV7CompactFrontierDeltaCertificate
