import AspisFormal.V7CompactFrontierDeltaCertificate.Depth11
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 12, chunk 12
Cells 20 through 20;
recurrence workload 188. -/

theorem certificate_12_5_46 :
    frontierCoeff 12 5 46 = 28 := by
  have zero_11_5_45 :
      frontierCoeff 11 5 45 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 4 46,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 4 (46 - leftFrontier)) = 6 := by
    have live0 : supportedSplitFrontiers 11 1 4 46 = {10, 11} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1, support_11_4]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {10, 11},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 4 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {10, 11},
            if leftFrontier = 10 then 0 else if leftFrontier = 11 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_10, AspisV6CompactFrontierTailCertificate.certificate_11_1_11, certificate_11_4_35, AspisV6CompactFrontierTailCertificate.certificate_11_4_36] <;> simp
      _ = 6 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 2 3 46,
        frontierCoeff 11 2 leftFrontier *
          frontierCoeff 11 3 (46 - leftFrontier)) = 8 := by
    have live1 : supportedSplitFrontiers 11 2 3 46 = {18, 19, 20} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_2, support_11_3]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {18, 19, 20},
          frontierCoeff 11 2 leftFrontier *
            frontierCoeff 11 3 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {18, 19, 20},
            if leftFrontier = 18 then 2 else if leftFrontier = 19 then 2 else if leftFrontier = 20 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_2_18, AspisV6CompactFrontierTailCertificate.certificate_11_2_19, AspisV6CompactFrontierTailCertificate.certificate_11_2_20, AspisV6CompactFrontierTailCertificate.certificate_11_3_26, AspisV6CompactFrontierTailCertificate.certificate_11_3_27, AspisV6CompactFrontierTailCertificate.certificate_11_3_28] <;> simp
      _ = 8 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 3 2 46,
        frontierCoeff 11 3 leftFrontier *
          frontierCoeff 11 2 (46 - leftFrontier)) = 8 := by
    have live2 : supportedSplitFrontiers 11 3 2 46 = {26, 27, 28} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_2, support_11_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {26, 27, 28},
          frontierCoeff 11 3 leftFrontier *
            frontierCoeff 11 2 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {26, 27, 28},
            if leftFrontier = 26 then 4 else if leftFrontier = 27 then 2 else if leftFrontier = 28 then 2 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_2_18, AspisV6CompactFrontierTailCertificate.certificate_11_2_19, AspisV6CompactFrontierTailCertificate.certificate_11_2_20, AspisV6CompactFrontierTailCertificate.certificate_11_3_26, AspisV6CompactFrontierTailCertificate.certificate_11_3_27, AspisV6CompactFrontierTailCertificate.certificate_11_3_28] <;> simp
      _ = 8 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 4 1 46,
        frontierCoeff 11 4 leftFrontier *
          frontierCoeff 11 1 (46 - leftFrontier)) = 6 := by
    have live3 : supportedSplitFrontiers 11 4 1 46 = {35, 36} := by
      rw [supportedSplitFrontiers_eq_Icc, support_11_1, support_11_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {35, 36},
          frontierCoeff 11 4 leftFrontier *
            frontierCoeff 11 1 (46 - leftFrontier)) =
          ∑ leftFrontier ∈ {35, 36},
            if leftFrontier = 35 then 6 else if leftFrontier = 36 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_10, AspisV6CompactFrontierTailCertificate.certificate_11_1_11, certificate_11_4_35, AspisV6CompactFrontierTailCertificate.certificate_11_4_36] <;> simp
      _ = 6 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (5 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (5 - (offset + 1)) 46,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (5 - (offset + 1))
              (46 - leftFrontier)) = 28 := by
    have offsets : Finset.range (5 - 1) = {0, 1, 2, 3} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (5 - (offset + 1)) 46,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (5 - (offset + 1))
                (46 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3},
            if offset = 0 then 6 else if offset = 1 then 8 else if offset = 2 then 8 else if offset = 3 then 6 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3] <;> simp
      _ = 28 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_11_5_45] <;> simp

end AspisV7CompactFrontierDeltaCertificate
