import AspisFormal.V7CompactFrontierDeltaCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 57
Cells 68 through 68;
recurrence workload 1595. -/

theorem certificate_16_12_144 :
    frontierCoeff 16 12 144 = 36768 := by
  have zero_15_12_143 :
      frontierCoeff 15 12 143 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 11 144,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 11 (144 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 15 1 11 144 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_11]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 10 144,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 10 (144 - leftFrontier)) = 28 := by
    have live1 : supportedSplitFrontiers 15 2 10 144 = {28} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_10, support_15_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {28},
          frontierCoeff 15 2 leftFrontier *
            frontierCoeff 15 10 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {28},
            if leftFrontier = 28 then 28 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_15_10_116, AspisV6CompactFrontierTailCertificate.certificate_15_2_28] <;> simp
      _ = 28 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 9 144,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 9 (144 - leftFrontier)) = 920 := by
    have live2 : supportedSplitFrontiers 15 3 9 144 = {38, 39, 40} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_9]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {38, 39, 40},
          frontierCoeff 15 3 leftFrontier *
            frontierCoeff 15 9 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {38, 39, 40},
            if leftFrontier = 38 then 32 else if leftFrontier = 39 then 184 else if leftFrontier = 40 then 704 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_3_38, AspisV6CompactFrontierTailCertificate.certificate_15_3_39, AspisV6CompactFrontierTailCertificate.certificate_15_3_40, certificate_15_9_104, AspisV6CompactFrontierTailCertificate.certificate_15_9_105, AspisV6CompactFrontierTailCertificate.certificate_15_9_106] <;> simp
      _ = 920 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 4 8 144,
        frontierCoeff 15 4 leftFrontier *
          frontierCoeff 15 8 (144 - leftFrontier)) = 4104 := by
    have live3 : supportedSplitFrontiers 15 4 8 144 = {48, 49, 50, 51, 52} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4, support_15_8]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {48, 49, 50, 51, 52},
          frontierCoeff 15 4 leftFrontier *
            frontierCoeff 15 8 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {48, 49, 50, 51, 52},
            if leftFrontier = 48 then 19 else if leftFrontier = 49 then 364 else if leftFrontier = 50 then 826 else if leftFrontier = 51 then 2100 else if leftFrontier = 52 then 795 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_4_48, AspisV6CompactFrontierTailCertificate.certificate_15_4_49, AspisV6CompactFrontierTailCertificate.certificate_15_4_50, AspisV6CompactFrontierTailCertificate.certificate_15_4_51, AspisV6CompactFrontierTailCertificate.certificate_15_4_52, AspisV6CompactFrontierTailCertificate.certificate_15_8_92,
            AspisV6CompactFrontierTailCertificate.certificate_15_8_93, AspisV6CompactFrontierTailCertificate.certificate_15_8_94, AspisV6CompactFrontierTailCertificate.certificate_15_8_95, AspisV6CompactFrontierTailCertificate.certificate_15_8_96] <;> simp
      _ = 4104 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 5 7 144,
        frontierCoeff 15 5 leftFrontier *
          frontierCoeff 15 7 (144 - leftFrontier)) = 8208 := by
    have live4 : supportedSplitFrontiers 15 5 7 144 = {59, 60, 61, 62, 63} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_5, support_15_7]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {59, 60, 61, 62, 63},
          frontierCoeff 15 5 leftFrontier *
            frontierCoeff 15 7 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {59, 60, 61, 62, 63},
            if leftFrontier = 59 then 264 else if leftFrontier = 60 then 1368 else if leftFrontier = 61 then 2464 else if leftFrontier = 62 then 2320 else if leftFrontier = 63 then 1792 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_5_59, AspisV6CompactFrontierTailCertificate.certificate_15_5_60, AspisV6CompactFrontierTailCertificate.certificate_15_5_61, AspisV6CompactFrontierTailCertificate.certificate_15_5_62, AspisV6CompactFrontierTailCertificate.certificate_15_5_63, AspisV6CompactFrontierTailCertificate.certificate_15_7_81,
            AspisV6CompactFrontierTailCertificate.certificate_15_7_82, AspisV6CompactFrontierTailCertificate.certificate_15_7_83, AspisV6CompactFrontierTailCertificate.certificate_15_7_84, AspisV6CompactFrontierTailCertificate.certificate_15_7_85] <;> simp
      _ = 8208 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 6 6 144,
        frontierCoeff 15 6 leftFrontier *
          frontierCoeff 15 6 (144 - leftFrontier)) = 10248 := by
    have live5 : supportedSplitFrontiers 15 6 6 144 = {70, 71, 72, 73, 74} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {70, 71, 72, 73, 74},
          frontierCoeff 15 6 leftFrontier *
            frontierCoeff 15 6 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {70, 71, 72, 73, 74},
            if leftFrontier = 70 then 1224 else if leftFrontier = 71 then 2332 else if leftFrontier = 72 then 3136 else if leftFrontier = 73 then 2332 else if leftFrontier = 74 then 1224 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_6_70, AspisV6CompactFrontierTailCertificate.certificate_15_6_71, AspisV6CompactFrontierTailCertificate.certificate_15_6_72, AspisV6CompactFrontierTailCertificate.certificate_15_6_73, AspisV6CompactFrontierTailCertificate.certificate_15_6_74] <;> simp
      _ = 10248 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 7 5 144,
        frontierCoeff 15 7 leftFrontier *
          frontierCoeff 15 5 (144 - leftFrontier)) = 8208 := by
    have live6 : supportedSplitFrontiers 15 7 5 144 = {81, 82, 83, 84, 85} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_5, support_15_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {81, 82, 83, 84, 85},
          frontierCoeff 15 7 leftFrontier *
            frontierCoeff 15 5 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {81, 82, 83, 84, 85},
            if leftFrontier = 81 then 1792 else if leftFrontier = 82 then 2320 else if leftFrontier = 83 then 2464 else if leftFrontier = 84 then 1368 else if leftFrontier = 85 then 264 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_5_59, AspisV6CompactFrontierTailCertificate.certificate_15_5_60, AspisV6CompactFrontierTailCertificate.certificate_15_5_61, AspisV6CompactFrontierTailCertificate.certificate_15_5_62, AspisV6CompactFrontierTailCertificate.certificate_15_5_63, AspisV6CompactFrontierTailCertificate.certificate_15_7_81,
            AspisV6CompactFrontierTailCertificate.certificate_15_7_82, AspisV6CompactFrontierTailCertificate.certificate_15_7_83, AspisV6CompactFrontierTailCertificate.certificate_15_7_84, AspisV6CompactFrontierTailCertificate.certificate_15_7_85] <;> simp
      _ = 8208 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 8 4 144,
        frontierCoeff 15 8 leftFrontier *
          frontierCoeff 15 4 (144 - leftFrontier)) = 4104 := by
    have live7 : supportedSplitFrontiers 15 8 4 144 = {92, 93, 94, 95, 96} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_4, support_15_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {92, 93, 94, 95, 96},
          frontierCoeff 15 8 leftFrontier *
            frontierCoeff 15 4 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {92, 93, 94, 95, 96},
            if leftFrontier = 92 then 795 else if leftFrontier = 93 then 2100 else if leftFrontier = 94 then 826 else if leftFrontier = 95 then 364 else if leftFrontier = 96 then 19 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_4_48, AspisV6CompactFrontierTailCertificate.certificate_15_4_49, AspisV6CompactFrontierTailCertificate.certificate_15_4_50, AspisV6CompactFrontierTailCertificate.certificate_15_4_51, AspisV6CompactFrontierTailCertificate.certificate_15_4_52, AspisV6CompactFrontierTailCertificate.certificate_15_8_92,
            AspisV6CompactFrontierTailCertificate.certificate_15_8_93, AspisV6CompactFrontierTailCertificate.certificate_15_8_94, AspisV6CompactFrontierTailCertificate.certificate_15_8_95, AspisV6CompactFrontierTailCertificate.certificate_15_8_96] <;> simp
      _ = 4104 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 9 3 144,
        frontierCoeff 15 9 leftFrontier *
          frontierCoeff 15 3 (144 - leftFrontier)) = 920 := by
    have live8 : supportedSplitFrontiers 15 9 3 144 = {104, 105, 106} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_3, support_15_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {104, 105, 106},
          frontierCoeff 15 9 leftFrontier *
            frontierCoeff 15 3 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {104, 105, 106},
            if leftFrontier = 104 then 704 else if leftFrontier = 105 then 184 else if leftFrontier = 106 then 32 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_3_38, AspisV6CompactFrontierTailCertificate.certificate_15_3_39, AspisV6CompactFrontierTailCertificate.certificate_15_3_40, certificate_15_9_104, AspisV6CompactFrontierTailCertificate.certificate_15_9_105, AspisV6CompactFrontierTailCertificate.certificate_15_9_106] <;> simp
      _ = 920 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 10 2 144,
        frontierCoeff 15 10 leftFrontier *
          frontierCoeff 15 2 (144 - leftFrontier)) = 28 := by
    have live9 : supportedSplitFrontiers 15 10 2 144 = {116} := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_10, support_15_2]
      ext value
      simp <;> omega
    rw [live9]
    calc
      (∑ leftFrontier ∈ {116},
          frontierCoeff 15 10 leftFrontier *
            frontierCoeff 15 2 (144 - leftFrontier)) =
          ∑ leftFrontier ∈ {116},
            if leftFrontier = 116 then 28 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [certificate_15_10_116, AspisV6CompactFrontierTailCertificate.certificate_15_2_28] <;> simp
      _ = 28 := by norm_num
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 11 1 144,
        frontierCoeff 15 11 leftFrontier *
          frontierCoeff 15 1 (144 - leftFrontier)) = 0 := by
    have live10 : supportedSplitFrontiers 15 11 1 144 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_15_1, support_15_11]
      ext value
      simp <;> omega
    rw [live10]
    simp
  have outer :
      (∑ offset ∈ Finset.range (12 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (12 - (offset + 1)) 144,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (12 - (offset + 1))
              (144 - leftFrontier)) = 36768 := by
    have offsets : Finset.range (12 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (12 - (offset + 1)) 144,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (12 - (offset + 1))
                (144 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
            if offset = 0 then 0 else if offset = 1 then 28 else if offset = 2 then 920 else if offset = 3 then 4104 else if offset = 4 then 8208 else if offset = 5 then 10248 else if offset = 6 then 8208 else if offset = 7 then 4104 else if offset = 8 then 920 else if offset = 9 then 28 else if offset = 10 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10] <;> simp
      _ = 36768 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_15_12_143] <;> simp

end AspisV7CompactFrontierDeltaCertificate
