import AspisFormal.V7CompactFrontierDeltaCertificate.Depth16
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 17, chunk 80
Cells 90 through 90;
recurrence workload 3060. -/

theorem certificate_17_16_203 :
    frontierCoeff 17 16 203 = 476064 := by
  have zero_16_16_202 :
      frontierCoeff 16 16 202 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 1 15 203,
        frontierCoeff 16 1 leftFrontier *
          frontierCoeff 16 15 (203 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 16 1 15 203 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_15]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 2 14 203,
        frontierCoeff 16 2 leftFrontier *
          frontierCoeff 16 14 (203 - leftFrontier)) = 0 := by
    have live1 : supportedSplitFrontiers 16 2 14 203 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_14, support_16_2]
      ext value
      simp <;> omega
    rw [live1]
    simp
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 3 13 203,
        frontierCoeff 16 3 leftFrontier *
          frontierCoeff 16 13 (203 - leftFrontier)) = 0 := by
    have live2 : supportedSplitFrontiers 16 3 13 203 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_13, support_16_3]
      ext value
      simp <;> omega
    rw [live2]
    simp
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 4 12 203,
        frontierCoeff 16 4 leftFrontier *
          frontierCoeff 16 12 (203 - leftFrontier)) = 1120 := by
    have live3 : supportedSplitFrontiers 16 4 12 203 = {55, 56} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_12, support_16_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {55, 56},
          frontierCoeff 16 4 leftFrontier *
            frontierCoeff 16 12 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {55, 56},
            if leftFrontier = 55 then 420 else if leftFrontier = 56 then 700 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_16_12_147, AspisV6CompactFrontierTailCertificate.certificate_16_12_148, AspisV6CompactFrontierTailCertificate.certificate_16_4_55, AspisV6CompactFrontierTailCertificate.certificate_16_4_56] <;> simp
      _ = 1120 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 5 11 203,
        frontierCoeff 16 5 leftFrontier *
          frontierCoeff 16 11 (203 - leftFrontier)) = 13784 := by
    have live4 : supportedSplitFrontiers 16 5 11 203 = {66, 67, 68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {66, 67, 68},
          frontierCoeff 16 5 leftFrontier *
            frontierCoeff 16 11 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {66, 67, 68},
            if leftFrontier = 66 then 1568 else if leftFrontier = 67 then 4200 else if leftFrontier = 68 then 8016 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_11_135, AspisV6CompactFrontierTailCertificate.certificate_16_11_136, AspisV6CompactFrontierTailCertificate.certificate_16_11_137, AspisV6CompactFrontierTailCertificate.certificate_16_5_66, AspisV6CompactFrontierTailCertificate.certificate_16_5_67, AspisV6CompactFrontierTailCertificate.certificate_16_5_68] <;> simp
      _ = 13784 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 6 10 203,
        frontierCoeff 16 6 leftFrontier *
          frontierCoeff 16 10 (203 - leftFrontier)) = 52440 := by
    have live5 : supportedSplitFrontiers 16 6 10 203 = {77, 78, 79, 80} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {77, 78, 79, 80},
          frontierCoeff 16 6 leftFrontier *
            frontierCoeff 16 10 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {77, 78, 79, 80},
            if leftFrontier = 77 then 2968 else if leftFrontier = 78 then 11872 else if leftFrontier = 79 then 20812 else if leftFrontier = 80 then 16788 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_10_123, AspisV6CompactFrontierTailCertificate.certificate_16_10_124, AspisV6CompactFrontierTailCertificate.certificate_16_10_125, AspisV6CompactFrontierTailCertificate.certificate_16_10_126, AspisV6CompactFrontierTailCertificate.certificate_16_6_77, AspisV6CompactFrontierTailCertificate.certificate_16_6_78,
            AspisV6CompactFrontierTailCertificate.certificate_16_6_79, AspisV6CompactFrontierTailCertificate.certificate_16_6_80] <;> simp
      _ = 52440 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 7 9 203,
        frontierCoeff 16 7 leftFrontier *
          frontierCoeff 16 9 (203 - leftFrontier)) = 105448 := by
    have live6 : supportedSplitFrontiers 16 7 9 203 = {88, 89, 90, 91, 92} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_7, support_16_9]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {88, 89, 90, 91, 92},
          frontierCoeff 16 7 leftFrontier *
            frontierCoeff 16 9 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {88, 89, 90, 91, 92},
            if leftFrontier = 88 then 3584 else if leftFrontier = 89 then 21344 else if leftFrontier = 90 then 30976 else if leftFrontier = 91 then 39456 else if leftFrontier = 92 then 10088 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_7_88, AspisV6CompactFrontierTailCertificate.certificate_16_7_89, AspisV6CompactFrontierTailCertificate.certificate_16_7_90, AspisV6CompactFrontierTailCertificate.certificate_16_7_91, AspisV6CompactFrontierTailCertificate.certificate_16_7_92, AspisV6CompactFrontierTailCertificate.certificate_16_9_111,
            AspisV6CompactFrontierTailCertificate.certificate_16_9_112, AspisV6CompactFrontierTailCertificate.certificate_16_9_113, AspisV6CompactFrontierTailCertificate.certificate_16_9_114, AspisV6CompactFrontierTailCertificate.certificate_16_9_115] <;> simp
      _ = 105448 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 8 8 203,
        frontierCoeff 16 8 leftFrontier *
          frontierCoeff 16 8 (203 - leftFrontier)) = 130480 := by
    have live7 : supportedSplitFrontiers 16 8 8 203 = {99, 100, 101, 102, 103, 104} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {99, 100, 101, 102, 103, 104},
          frontierCoeff 16 8 leftFrontier *
            frontierCoeff 16 8 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {99, 100, 101, 102, 103, 104},
            if leftFrontier = 99 then 1680 else if leftFrontier = 100 then 22260 else if leftFrontier = 101 then 41300 else if leftFrontier = 102 then 41300 else if leftFrontier = 103 then 22260 else if leftFrontier = 104 then 1680 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_8_100, AspisV6CompactFrontierTailCertificate.certificate_16_8_101, AspisV6CompactFrontierTailCertificate.certificate_16_8_102, AspisV6CompactFrontierTailCertificate.certificate_16_8_103, AspisV6CompactFrontierTailCertificate.certificate_16_8_104, AspisV6CompactFrontierTailCertificate.certificate_16_8_99] <;> simp
      _ = 130480 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 9 7 203,
        frontierCoeff 16 9 leftFrontier *
          frontierCoeff 16 7 (203 - leftFrontier)) = 105448 := by
    have live8 : supportedSplitFrontiers 16 9 7 203 = {111, 112, 113, 114, 115} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_7, support_16_9]
      ext value
      simp <;> omega
    rw [live8]
    calc
      (∑ leftFrontier ∈ {111, 112, 113, 114, 115},
          frontierCoeff 16 9 leftFrontier *
            frontierCoeff 16 7 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {111, 112, 113, 114, 115},
            if leftFrontier = 111 then 10088 else if leftFrontier = 112 then 39456 else if leftFrontier = 113 then 30976 else if leftFrontier = 114 then 21344 else if leftFrontier = 115 then 3584 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_7_88, AspisV6CompactFrontierTailCertificate.certificate_16_7_89, AspisV6CompactFrontierTailCertificate.certificate_16_7_90, AspisV6CompactFrontierTailCertificate.certificate_16_7_91, AspisV6CompactFrontierTailCertificate.certificate_16_7_92, AspisV6CompactFrontierTailCertificate.certificate_16_9_111,
            AspisV6CompactFrontierTailCertificate.certificate_16_9_112, AspisV6CompactFrontierTailCertificate.certificate_16_9_113, AspisV6CompactFrontierTailCertificate.certificate_16_9_114, AspisV6CompactFrontierTailCertificate.certificate_16_9_115] <;> simp
      _ = 105448 := by norm_num
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 10 6 203,
        frontierCoeff 16 10 leftFrontier *
          frontierCoeff 16 6 (203 - leftFrontier)) = 52440 := by
    have live9 : supportedSplitFrontiers 16 10 6 203 = {123, 124, 125, 126} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_10, support_16_6]
      ext value
      simp <;> omega
    rw [live9]
    calc
      (∑ leftFrontier ∈ {123, 124, 125, 126},
          frontierCoeff 16 10 leftFrontier *
            frontierCoeff 16 6 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {123, 124, 125, 126},
            if leftFrontier = 123 then 16788 else if leftFrontier = 124 then 20812 else if leftFrontier = 125 then 11872 else if leftFrontier = 126 then 2968 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_10_123, AspisV6CompactFrontierTailCertificate.certificate_16_10_124, AspisV6CompactFrontierTailCertificate.certificate_16_10_125, AspisV6CompactFrontierTailCertificate.certificate_16_10_126, AspisV6CompactFrontierTailCertificate.certificate_16_6_77, AspisV6CompactFrontierTailCertificate.certificate_16_6_78,
            AspisV6CompactFrontierTailCertificate.certificate_16_6_79, AspisV6CompactFrontierTailCertificate.certificate_16_6_80] <;> simp
      _ = 52440 := by norm_num
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 11 5 203,
        frontierCoeff 16 11 leftFrontier *
          frontierCoeff 16 5 (203 - leftFrontier)) = 13784 := by
    have live10 : supportedSplitFrontiers 16 11 5 203 = {135, 136, 137} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_11, support_16_5]
      ext value
      simp <;> omega
    rw [live10]
    calc
      (∑ leftFrontier ∈ {135, 136, 137},
          frontierCoeff 16 11 leftFrontier *
            frontierCoeff 16 5 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {135, 136, 137},
            if leftFrontier = 135 then 8016 else if leftFrontier = 136 then 4200 else if leftFrontier = 137 then 1568 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_16_11_135, AspisV6CompactFrontierTailCertificate.certificate_16_11_136, AspisV6CompactFrontierTailCertificate.certificate_16_11_137, AspisV6CompactFrontierTailCertificate.certificate_16_5_66, AspisV6CompactFrontierTailCertificate.certificate_16_5_67, AspisV6CompactFrontierTailCertificate.certificate_16_5_68] <;> simp
      _ = 13784 := by norm_num
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 12 4 203,
        frontierCoeff 16 12 leftFrontier *
          frontierCoeff 16 4 (203 - leftFrontier)) = 1120 := by
    have live11 : supportedSplitFrontiers 16 12 4 203 = {147, 148} := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_12, support_16_4]
      ext value
      simp <;> omega
    rw [live11]
    calc
      (∑ leftFrontier ∈ {147, 148},
          frontierCoeff 16 12 leftFrontier *
            frontierCoeff 16 4 (203 - leftFrontier)) =
          ∑ leftFrontier ∈ {147, 148},
            if leftFrontier = 147 then 700 else if leftFrontier = 148 then 420 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [certificate_16_12_147, AspisV6CompactFrontierTailCertificate.certificate_16_12_148, AspisV6CompactFrontierTailCertificate.certificate_16_4_55, AspisV6CompactFrontierTailCertificate.certificate_16_4_56] <;> simp
      _ = 1120 := by norm_num
  have split12 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 13 3 203,
        frontierCoeff 16 13 leftFrontier *
          frontierCoeff 16 3 (203 - leftFrontier)) = 0 := by
    have live12 : supportedSplitFrontiers 16 13 3 203 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_13, support_16_3]
      ext value
      simp <;> omega
    rw [live12]
    simp
  have split13 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 14 2 203,
        frontierCoeff 16 14 leftFrontier *
          frontierCoeff 16 2 (203 - leftFrontier)) = 0 := by
    have live13 : supportedSplitFrontiers 16 14 2 203 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_14, support_16_2]
      ext value
      simp <;> omega
    rw [live13]
    simp
  have split14 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 16 15 1 203,
        frontierCoeff 16 15 leftFrontier *
          frontierCoeff 16 1 (203 - leftFrontier)) = 0 := by
    have live14 : supportedSplitFrontiers 16 15 1 203 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, support_16_1, support_16_15]
      ext value
      simp <;> omega
    rw [live14]
    simp
  have outer :
      (∑ offset ∈ Finset.range (16 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
            (16 - (offset + 1)) 203,
          frontierCoeff 16 (offset + 1) leftFrontier *
            frontierCoeff 16 (16 - (offset + 1))
              (203 - leftFrontier)) = 476064 := by
    have offsets : Finset.range (16 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
          ∑ leftFrontier ∈ supportedSplitFrontiers 16 (offset + 1)
              (16 - (offset + 1)) 203,
            frontierCoeff 16 (offset + 1) leftFrontier *
              frontierCoeff 16 (16 - (offset + 1))
                (203 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14},
            if offset = 0 then 0 else if offset = 1 then 0 else if offset = 2 then 0 else if offset = 3 then 1120 else if offset = 4 then 13784 else if offset = 5 then 52440 else if offset = 6 then 105448 else if offset = 7 then 130480 else if offset = 8 then 105448 else if offset = 9 then 52440 else if offset = 10 then 13784 else if offset = 11 then 1120 else if offset = 12 then 0 else if offset = 13 then 0 else if offset = 14 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11,
            split12, split13, split14] <;> simp
      _ = 476064 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_16_16_202] <;> simp

end AspisV7CompactFrontierDeltaCertificate
