import AspisFormal.V7CompactFrontierDeltaCertificate.Depth11
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 12, chunk 13
Cells 21 through 21;
recurrence workload 192. -/

theorem certificate_12_5_47 :
    frontierCoeff 12 5 47 = 10 := by
  have zero_11_5_46 :
      frontierCoeff 11 5 46 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 1 4 47,
        frontierCoeff 11 1 leftFrontier *
          frontierCoeff 11 4 (47 - leftFrontier)) = 1 := by
    have live0 : supportedSplitFrontiers 11 1 4 47 = {11} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_11_1, AspisV6CompactFrontierTailCertificate.support_11_4]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {11},
          frontierCoeff 11 1 leftFrontier *
            frontierCoeff 11 4 (47 - leftFrontier)) =
          ∑ leftFrontier ∈ {11},
            if leftFrontier = 11 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_11, AspisV6CompactFrontierTailCertificate.certificate_11_4_36] <;> simp
      _ = 1 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 2 3 47,
        frontierCoeff 11 2 leftFrontier *
          frontierCoeff 11 3 (47 - leftFrontier)) = 4 := by
    have live1 : supportedSplitFrontiers 11 2 3 47 = {19, 20} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_11_2, AspisV6CompactFrontierTailCertificate.support_11_3]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {19, 20},
          frontierCoeff 11 2 leftFrontier *
            frontierCoeff 11 3 (47 - leftFrontier)) =
          ∑ leftFrontier ∈ {19, 20},
            if leftFrontier = 19 then 2 else if leftFrontier = 20 then 2 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_2_19, AspisV6CompactFrontierTailCertificate.certificate_11_2_20, AspisV6CompactFrontierTailCertificate.certificate_11_3_27, AspisV6CompactFrontierTailCertificate.certificate_11_3_28] <;> simp
      _ = 4 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 3 2 47,
        frontierCoeff 11 3 leftFrontier *
          frontierCoeff 11 2 (47 - leftFrontier)) = 4 := by
    have live2 : supportedSplitFrontiers 11 3 2 47 = {27, 28} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_11_2, AspisV6CompactFrontierTailCertificate.support_11_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {27, 28},
          frontierCoeff 11 3 leftFrontier *
            frontierCoeff 11 2 (47 - leftFrontier)) =
          ∑ leftFrontier ∈ {27, 28},
            if leftFrontier = 27 then 2 else if leftFrontier = 28 then 2 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_2_19, AspisV6CompactFrontierTailCertificate.certificate_11_2_20, AspisV6CompactFrontierTailCertificate.certificate_11_3_27, AspisV6CompactFrontierTailCertificate.certificate_11_3_28] <;> simp
      _ = 4 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 11 4 1 47,
        frontierCoeff 11 4 leftFrontier *
          frontierCoeff 11 1 (47 - leftFrontier)) = 1 := by
    have live3 : supportedSplitFrontiers 11 4 1 47 = {36} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_11_1, AspisV6CompactFrontierTailCertificate.support_11_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {36},
          frontierCoeff 11 4 leftFrontier *
            frontierCoeff 11 1 (47 - leftFrontier)) =
          ∑ leftFrontier ∈ {36},
            if leftFrontier = 36 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_11_1_11, AspisV6CompactFrontierTailCertificate.certificate_11_4_36] <;> simp
      _ = 1 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (5 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
            (5 - (offset + 1)) 47,
          frontierCoeff 11 (offset + 1) leftFrontier *
            frontierCoeff 11 (5 - (offset + 1))
              (47 - leftFrontier)) = 10 := by
    have offsets : Finset.range (5 - 1) = {0, 1, 2, 3} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3},
          ∑ leftFrontier ∈ supportedSplitFrontiers 11 (offset + 1)
              (5 - (offset + 1)) 47,
            frontierCoeff 11 (offset + 1) leftFrontier *
              frontierCoeff 11 (5 - (offset + 1))
                (47 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3},
            if offset = 0 then 1 else if offset = 1 then 4 else if offset = 2 then 4 else if offset = 3 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3] <;> simp
      _ = 10 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_11_5_46] <;> simp

end AspisV7CompactFrontierDeltaCertificate
