import AspisFormal.V7CompactFrontierDeltaCertificate.Depth14
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 15, chunk 28
Cells 37 through 37;
recurrence workload 474. -/

theorem certificate_15_7_78 :
    frontierCoeff 15 7 78 = 2216 := by
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 1 6 78,
        frontierCoeff 14 1 leftFrontier *
          frontierCoeff 14 6 (78 - leftFrontier)) = 204 := by
    have live0 : supportedSplitFrontiers 14 1 6 78 = {10, 11, 12, 13, 14} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1, support_14_6]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {10, 11, 12, 13, 14},
          frontierCoeff 14 1 leftFrontier *
            frontierCoeff 14 6 (78 - leftFrontier)) =
          ∑ leftFrontier ∈ {10, 11, 12, 13, 14},
            if leftFrontier = 10 then 0 else if leftFrontier = 11 then 0 else if leftFrontier = 12 then 0 else if leftFrontier = 13 then 0 else if leftFrontier = 14 then 204 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_1_10, AspisV6CompactFrontierTailCertificate.certificate_14_1_11, AspisV6CompactFrontierTailCertificate.certificate_14_1_12, AspisV6CompactFrontierTailCertificate.certificate_14_1_13, AspisV6CompactFrontierTailCertificate.certificate_14_1_14, certificate_14_6_64,
            AspisV6CompactFrontierTailCertificate.certificate_14_6_65, AspisV6CompactFrontierTailCertificate.certificate_14_6_66, AspisV6CompactFrontierTailCertificate.certificate_14_6_67, AspisV6CompactFrontierTailCertificate.certificate_14_6_68] <;> simp
      _ = 204 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 2 5 78,
        frontierCoeff 14 2 leftFrontier *
          frontierCoeff 14 5 (78 - leftFrontier)) = 384 := by
    have live1 : supportedSplitFrontiers 14 2 5 78 = {20, 21, 22, 23, 24, 25, 26} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_2, support_14_5]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {20, 21, 22, 23, 24, 25, 26},
          frontierCoeff 14 2 leftFrontier *
            frontierCoeff 14 5 (78 - leftFrontier)) =
          ∑ leftFrontier ∈ {20, 21, 22, 23, 24, 25, 26},
            if leftFrontier = 20 then 4 else if leftFrontier = 21 then 10 else if leftFrontier = 22 then 28 else if leftFrontier = 23 then 38 else if leftFrontier = 24 then 66 else if leftFrontier = 25 then 96 else if leftFrontier = 26 then 142 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_2_20, AspisV6CompactFrontierTailCertificate.certificate_14_2_21, AspisV6CompactFrontierTailCertificate.certificate_14_2_22, AspisV6CompactFrontierTailCertificate.certificate_14_2_23, AspisV6CompactFrontierTailCertificate.certificate_14_2_24, AspisV6CompactFrontierTailCertificate.certificate_14_2_25,
            AspisV6CompactFrontierTailCertificate.certificate_14_2_26, AspisV6CompactFrontierTailCertificate.certificate_14_5_52, AspisV6CompactFrontierTailCertificate.certificate_14_5_53, AspisV6CompactFrontierTailCertificate.certificate_14_5_54, AspisV6CompactFrontierTailCertificate.certificate_14_5_55, AspisV6CompactFrontierTailCertificate.certificate_14_5_56,
            AspisV6CompactFrontierTailCertificate.certificate_14_5_57, AspisV6CompactFrontierTailCertificate.certificate_14_5_58] <;> simp
      _ = 384 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 3 4 78,
        frontierCoeff 14 3 leftFrontier *
          frontierCoeff 14 4 (78 - leftFrontier)) = 502 := by
    have live2 : supportedSplitFrontiers 14 3 4 78 = {30, 31, 32, 33, 34, 35, 36, 37} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_3, support_14_4]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {30, 31, 32, 33, 34, 35, 36, 37},
          frontierCoeff 14 3 leftFrontier *
            frontierCoeff 14 4 (78 - leftFrontier)) =
          ∑ leftFrontier ∈ {30, 31, 32, 33, 34, 35, 36, 37},
            if leftFrontier = 30 then 8 else if leftFrontier = 31 then 48 else if leftFrontier = 32 then 42 else if leftFrontier = 33 then 78 else if leftFrontier = 34 then 76 else if leftFrontier = 35 then 100 else if leftFrontier = 36 then 64 else if leftFrontier = 37 then 86 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_3_30, AspisV6CompactFrontierTailCertificate.certificate_14_3_31, AspisV6CompactFrontierTailCertificate.certificate_14_3_32, AspisV6CompactFrontierTailCertificate.certificate_14_3_33, AspisV6CompactFrontierTailCertificate.certificate_14_3_34, AspisV6CompactFrontierTailCertificate.certificate_14_3_35,
            AspisV6CompactFrontierTailCertificate.certificate_14_3_36, AspisV6CompactFrontierTailCertificate.certificate_14_3_37, AspisV6CompactFrontierTailCertificate.certificate_14_4_41, AspisV6CompactFrontierTailCertificate.certificate_14_4_42, AspisV6CompactFrontierTailCertificate.certificate_14_4_43, AspisV6CompactFrontierTailCertificate.certificate_14_4_44,
            AspisV6CompactFrontierTailCertificate.certificate_14_4_45, AspisV6CompactFrontierTailCertificate.certificate_14_4_46, AspisV6CompactFrontierTailCertificate.certificate_14_4_47, AspisV6CompactFrontierTailCertificate.certificate_14_4_48] <;> simp
      _ = 502 := by norm_num
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 4 3 78,
        frontierCoeff 14 4 leftFrontier *
          frontierCoeff 14 3 (78 - leftFrontier)) = 502 := by
    have live3 : supportedSplitFrontiers 14 4 3 78 = {41, 42, 43, 44, 45, 46, 47, 48} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_3, support_14_4]
      ext value
      simp <;> omega
    rw [live3]
    calc
      (∑ leftFrontier ∈ {41, 42, 43, 44, 45, 46, 47, 48},
          frontierCoeff 14 4 leftFrontier *
            frontierCoeff 14 3 (78 - leftFrontier)) =
          ∑ leftFrontier ∈ {41, 42, 43, 44, 45, 46, 47, 48},
            if leftFrontier = 41 then 86 else if leftFrontier = 42 then 64 else if leftFrontier = 43 then 100 else if leftFrontier = 44 then 76 else if leftFrontier = 45 then 78 else if leftFrontier = 46 then 42 else if leftFrontier = 47 then 48 else if leftFrontier = 48 then 8 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_3_30, AspisV6CompactFrontierTailCertificate.certificate_14_3_31, AspisV6CompactFrontierTailCertificate.certificate_14_3_32, AspisV6CompactFrontierTailCertificate.certificate_14_3_33, AspisV6CompactFrontierTailCertificate.certificate_14_3_34, AspisV6CompactFrontierTailCertificate.certificate_14_3_35,
            AspisV6CompactFrontierTailCertificate.certificate_14_3_36, AspisV6CompactFrontierTailCertificate.certificate_14_3_37, AspisV6CompactFrontierTailCertificate.certificate_14_4_41, AspisV6CompactFrontierTailCertificate.certificate_14_4_42, AspisV6CompactFrontierTailCertificate.certificate_14_4_43, AspisV6CompactFrontierTailCertificate.certificate_14_4_44,
            AspisV6CompactFrontierTailCertificate.certificate_14_4_45, AspisV6CompactFrontierTailCertificate.certificate_14_4_46, AspisV6CompactFrontierTailCertificate.certificate_14_4_47, AspisV6CompactFrontierTailCertificate.certificate_14_4_48] <;> simp
      _ = 502 := by norm_num
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 5 2 78,
        frontierCoeff 14 5 leftFrontier *
          frontierCoeff 14 2 (78 - leftFrontier)) = 384 := by
    have live4 : supportedSplitFrontiers 14 5 2 78 = {52, 53, 54, 55, 56, 57, 58} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_2, support_14_5]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {52, 53, 54, 55, 56, 57, 58},
          frontierCoeff 14 5 leftFrontier *
            frontierCoeff 14 2 (78 - leftFrontier)) =
          ∑ leftFrontier ∈ {52, 53, 54, 55, 56, 57, 58},
            if leftFrontier = 52 then 142 else if leftFrontier = 53 then 96 else if leftFrontier = 54 then 66 else if leftFrontier = 55 then 38 else if leftFrontier = 56 then 28 else if leftFrontier = 57 then 10 else if leftFrontier = 58 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_2_20, AspisV6CompactFrontierTailCertificate.certificate_14_2_21, AspisV6CompactFrontierTailCertificate.certificate_14_2_22, AspisV6CompactFrontierTailCertificate.certificate_14_2_23, AspisV6CompactFrontierTailCertificate.certificate_14_2_24, AspisV6CompactFrontierTailCertificate.certificate_14_2_25,
            AspisV6CompactFrontierTailCertificate.certificate_14_2_26, AspisV6CompactFrontierTailCertificate.certificate_14_5_52, AspisV6CompactFrontierTailCertificate.certificate_14_5_53, AspisV6CompactFrontierTailCertificate.certificate_14_5_54, AspisV6CompactFrontierTailCertificate.certificate_14_5_55, AspisV6CompactFrontierTailCertificate.certificate_14_5_56,
            AspisV6CompactFrontierTailCertificate.certificate_14_5_57, AspisV6CompactFrontierTailCertificate.certificate_14_5_58] <;> simp
      _ = 384 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 14 6 1 78,
        frontierCoeff 14 6 leftFrontier *
          frontierCoeff 14 1 (78 - leftFrontier)) = 204 := by
    have live5 : supportedSplitFrontiers 14 6 1 78 = {64, 65, 66, 67, 68} := by
      rw [supportedSplitFrontiers_eq_Icc, support_14_1, support_14_6]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {64, 65, 66, 67, 68},
          frontierCoeff 14 6 leftFrontier *
            frontierCoeff 14 1 (78 - leftFrontier)) =
          ∑ leftFrontier ∈ {64, 65, 66, 67, 68},
            if leftFrontier = 64 then 204 else if leftFrontier = 65 then 0 else if leftFrontier = 66 then 0 else if leftFrontier = 67 then 0 else if leftFrontier = 68 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_14_1_10, AspisV6CompactFrontierTailCertificate.certificate_14_1_11, AspisV6CompactFrontierTailCertificate.certificate_14_1_12, AspisV6CompactFrontierTailCertificate.certificate_14_1_13, AspisV6CompactFrontierTailCertificate.certificate_14_1_14, certificate_14_6_64,
            AspisV6CompactFrontierTailCertificate.certificate_14_6_65, AspisV6CompactFrontierTailCertificate.certificate_14_6_66, AspisV6CompactFrontierTailCertificate.certificate_14_6_67, AspisV6CompactFrontierTailCertificate.certificate_14_6_68] <;> simp
      _ = 204 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (7 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
            (7 - (offset + 1)) 78,
          frontierCoeff 14 (offset + 1) leftFrontier *
            frontierCoeff 14 (7 - (offset + 1))
              (78 - leftFrontier)) = 2180 := by
    have offsets : Finset.range (7 - 1) = {0, 1, 2, 3, 4, 5} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5},
          ∑ leftFrontier ∈ supportedSplitFrontiers 14 (offset + 1)
              (7 - (offset + 1)) 78,
            frontierCoeff 14 (offset + 1) leftFrontier *
              frontierCoeff 14 (7 - (offset + 1))
                (78 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5},
            if offset = 0 then 204 else if offset = 1 then 384 else if offset = 2 then 502 else if offset = 3 then 502 else if offset = 4 then 384 else if offset = 5 then 204 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5] <;> simp
      _ = 2180 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, certificate_14_7_77] <;> simp

end AspisV7CompactFrontierDeltaCertificate
