import AspisFormal.V7CompactFrontierDeltaCertificate.Depth09
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 10, chunk 5
Cells 13 through 13;
recurrence workload 93. -/

theorem certificate_10_4_30 :
    frontierCoeff 10 4 30 = 7 := by
  have zero_9_4_29 :
      frontierCoeff 9 4 29 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 9 1 3 30,
        frontierCoeff 9 1 leftFrontier *
          frontierCoeff 9 3 (30 - leftFrontier)) = 2 := by
    have live0 : supportedSplitFrontiers 9 1 3 30 = {8, 9} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_9_1, AspisV6CompactFrontierTailCertificate.support_9_3]
      ext value
      simp <;> omega
    rw [live0]
    calc
      (∑ leftFrontier ∈ {8, 9},
          frontierCoeff 9 1 leftFrontier *
            frontierCoeff 9 3 (30 - leftFrontier)) =
          ∑ leftFrontier ∈ {8, 9},
            if leftFrontier = 8 then 0 else if leftFrontier = 9 then 2 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_9_1_8, AspisV6CompactFrontierTailCertificate.certificate_9_1_9, AspisV6CompactFrontierTailCertificate.certificate_9_3_21, AspisV6CompactFrontierTailCertificate.certificate_9_3_22] <;> simp
      _ = 2 := by norm_num
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 9 2 2 30,
        frontierCoeff 9 2 leftFrontier *
          frontierCoeff 9 2 (30 - leftFrontier)) = 3 := by
    have live1 : supportedSplitFrontiers 9 2 2 30 = {14, 15, 16} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_9_2]
      ext value
      simp <;> omega
    rw [live1]
    calc
      (∑ leftFrontier ∈ {14, 15, 16},
          frontierCoeff 9 2 leftFrontier *
            frontierCoeff 9 2 (30 - leftFrontier)) =
          ∑ leftFrontier ∈ {14, 15, 16},
            if leftFrontier = 14 then 1 else if leftFrontier = 15 then 1 else if leftFrontier = 16 then 1 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_9_2_14, AspisV6CompactFrontierTailCertificate.certificate_9_2_15, AspisV6CompactFrontierTailCertificate.certificate_9_2_16] <;> simp
      _ = 3 := by norm_num
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 9 3 1 30,
        frontierCoeff 9 3 leftFrontier *
          frontierCoeff 9 1 (30 - leftFrontier)) = 2 := by
    have live2 : supportedSplitFrontiers 9 3 1 30 = {21, 22} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_9_1, AspisV6CompactFrontierTailCertificate.support_9_3]
      ext value
      simp <;> omega
    rw [live2]
    calc
      (∑ leftFrontier ∈ {21, 22},
          frontierCoeff 9 3 leftFrontier *
            frontierCoeff 9 1 (30 - leftFrontier)) =
          ∑ leftFrontier ∈ {21, 22},
            if leftFrontier = 21 then 2 else if leftFrontier = 22 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl) <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_9_1_8, AspisV6CompactFrontierTailCertificate.certificate_9_1_9, AspisV6CompactFrontierTailCertificate.certificate_9_3_21, AspisV6CompactFrontierTailCertificate.certificate_9_3_22] <;> simp
      _ = 2 := by norm_num
  have outer :
      (∑ offset ∈ Finset.range (4 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 9 (offset + 1)
            (4 - (offset + 1)) 30,
          frontierCoeff 9 (offset + 1) leftFrontier *
            frontierCoeff 9 (4 - (offset + 1))
              (30 - leftFrontier)) = 7 := by
    have offsets : Finset.range (4 - 1) = {0, 1, 2} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2},
          ∑ leftFrontier ∈ supportedSplitFrontiers 9 (offset + 1)
              (4 - (offset + 1)) 30,
            frontierCoeff 9 (offset + 1) leftFrontier *
              frontierCoeff 9 (4 - (offset + 1))
                (30 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2},
            if offset = 0 then 2 else if offset = 1 then 3 else if offset = 2 then 2 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2] <;> simp
      _ = 7 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_9_4_29] <;> simp

end AspisV7CompactFrontierDeltaCertificate
