import AspisFormal.V7CompactFrontierDeltaCertificate.Depth15
import AspisFormal.V6CompactFrontierSparseSupport

/-! Generated by `tools/generate_v7_compact_frontier_delta.py`; do not edit.
Every declaration uses ordinary kernel-checked arithmetic. -/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 0

namespace AspisV7CompactFrontierDeltaCertificate

open AspisV6CompactFrontierRecurrence
open AspisV6CompactFrontierSupport

/-! ## Depth 16, chunk 64
Cells 75 through 75;
recurrence workload 1920. -/

theorem certificate_16_13_159 :
    frontierCoeff 16 13 159 = 56 := by
  have zero_15_13_158 :
      frontierCoeff 15 13 158 = 0 := by
    apply frontierCoeff_eq_zero_of_frontier_gt_support
    norm_num
  have split0 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 1 12 159,
        frontierCoeff 15 1 leftFrontier *
          frontierCoeff 15 12 (159 - leftFrontier)) = 0 := by
    have live0 : supportedSplitFrontiers 15 1 12 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_1, AspisV6CompactFrontierTailCertificate.support_15_12]
      ext value
      simp <;> omega
    rw [live0]
    simp
  have split1 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 2 11 159,
        frontierCoeff 15 2 leftFrontier *
          frontierCoeff 15 11 (159 - leftFrontier)) = 0 := by
    have live1 : supportedSplitFrontiers 15 2 11 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_11, AspisV6CompactFrontierTailCertificate.support_15_2]
      ext value
      simp <;> omega
    rw [live1]
    simp
  have split2 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 3 10 159,
        frontierCoeff 15 3 leftFrontier *
          frontierCoeff 15 10 (159 - leftFrontier)) = 0 := by
    have live2 : supportedSplitFrontiers 15 3 10 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_10, AspisV6CompactFrontierTailCertificate.support_15_3]
      ext value
      simp <;> omega
    rw [live2]
    simp
  have split3 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 4 9 159,
        frontierCoeff 15 4 leftFrontier *
          frontierCoeff 15 9 (159 - leftFrontier)) = 0 := by
    have live3 : supportedSplitFrontiers 15 4 9 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_4, AspisV6CompactFrontierTailCertificate.support_15_9]
      ext value
      simp <;> omega
    rw [live3]
    simp
  have split4 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 5 8 159,
        frontierCoeff 15 5 leftFrontier *
          frontierCoeff 15 8 (159 - leftFrontier)) = 4 := by
    have live4 : supportedSplitFrontiers 15 5 8 159 = {63} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_5, AspisV6CompactFrontierTailCertificate.support_15_8]
      ext value
      simp <;> omega
    rw [live4]
    calc
      (∑ leftFrontier ∈ {63},
          frontierCoeff 15 5 leftFrontier *
            frontierCoeff 15 8 (159 - leftFrontier)) =
          ∑ leftFrontier ∈ {63},
            if leftFrontier = 63 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_5_63, AspisV6CompactFrontierTailCertificate.certificate_15_8_96] <;> simp
      _ = 4 := by norm_num
  have split5 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 6 7 159,
        frontierCoeff 15 6 leftFrontier *
          frontierCoeff 15 7 (159 - leftFrontier)) = 24 := by
    have live5 : supportedSplitFrontiers 15 6 7 159 = {74} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_6, AspisV6CompactFrontierTailCertificate.support_15_7]
      ext value
      simp <;> omega
    rw [live5]
    calc
      (∑ leftFrontier ∈ {74},
          frontierCoeff 15 6 leftFrontier *
            frontierCoeff 15 7 (159 - leftFrontier)) =
          ∑ leftFrontier ∈ {74},
            if leftFrontier = 74 then 24 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_6_74, AspisV6CompactFrontierTailCertificate.certificate_15_7_85] <;> simp
      _ = 24 := by norm_num
  have split6 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 7 6 159,
        frontierCoeff 15 7 leftFrontier *
          frontierCoeff 15 6 (159 - leftFrontier)) = 24 := by
    have live6 : supportedSplitFrontiers 15 7 6 159 = {85} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_6, AspisV6CompactFrontierTailCertificate.support_15_7]
      ext value
      simp <;> omega
    rw [live6]
    calc
      (∑ leftFrontier ∈ {85},
          frontierCoeff 15 7 leftFrontier *
            frontierCoeff 15 6 (159 - leftFrontier)) =
          ∑ leftFrontier ∈ {85},
            if leftFrontier = 85 then 24 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_6_74, AspisV6CompactFrontierTailCertificate.certificate_15_7_85] <;> simp
      _ = 24 := by norm_num
  have split7 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 8 5 159,
        frontierCoeff 15 8 leftFrontier *
          frontierCoeff 15 5 (159 - leftFrontier)) = 4 := by
    have live7 : supportedSplitFrontiers 15 8 5 159 = {96} := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_5, AspisV6CompactFrontierTailCertificate.support_15_8]
      ext value
      simp <;> omega
    rw [live7]
    calc
      (∑ leftFrontier ∈ {96},
          frontierCoeff 15 8 leftFrontier *
            frontierCoeff 15 5 (159 - leftFrontier)) =
          ∑ leftFrontier ∈ {96},
            if leftFrontier = 96 then 4 else 0 := by
        apply Finset.sum_congr rfl
        intro leftFrontier member
        simp only [Finset.mem_singleton] at member
        rcases member with rfl <;>
          norm_num only [AspisV6CompactFrontierTailCertificate.certificate_15_5_63, AspisV6CompactFrontierTailCertificate.certificate_15_8_96] <;> simp
      _ = 4 := by norm_num
  have split8 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 9 4 159,
        frontierCoeff 15 9 leftFrontier *
          frontierCoeff 15 4 (159 - leftFrontier)) = 0 := by
    have live8 : supportedSplitFrontiers 15 9 4 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_4, AspisV6CompactFrontierTailCertificate.support_15_9]
      ext value
      simp <;> omega
    rw [live8]
    simp
  have split9 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 10 3 159,
        frontierCoeff 15 10 leftFrontier *
          frontierCoeff 15 3 (159 - leftFrontier)) = 0 := by
    have live9 : supportedSplitFrontiers 15 10 3 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_10, AspisV6CompactFrontierTailCertificate.support_15_3]
      ext value
      simp <;> omega
    rw [live9]
    simp
  have split10 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 11 2 159,
        frontierCoeff 15 11 leftFrontier *
          frontierCoeff 15 2 (159 - leftFrontier)) = 0 := by
    have live10 : supportedSplitFrontiers 15 11 2 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_11, AspisV6CompactFrontierTailCertificate.support_15_2]
      ext value
      simp <;> omega
    rw [live10]
    simp
  have split11 :
      (∑ leftFrontier ∈ supportedSplitFrontiers 15 12 1 159,
        frontierCoeff 15 12 leftFrontier *
          frontierCoeff 15 1 (159 - leftFrontier)) = 0 := by
    have live11 : supportedSplitFrontiers 15 12 1 159 = ∅ := by
      rw [supportedSplitFrontiers_eq_Icc, AspisV6CompactFrontierTailCertificate.support_15_1, AspisV6CompactFrontierTailCertificate.support_15_12]
      ext value
      simp <;> omega
    rw [live11]
    simp
  have outer :
      (∑ offset ∈ Finset.range (13 - 1),
        ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
            (13 - (offset + 1)) 159,
          frontierCoeff 15 (offset + 1) leftFrontier *
            frontierCoeff 15 (13 - (offset + 1))
              (159 - leftFrontier)) = 56 := by
    have offsets : Finset.range (13 - 1) = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11} := by decide
    rw [offsets]
    calc
      (∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
          ∑ leftFrontier ∈ supportedSplitFrontiers 15 (offset + 1)
              (13 - (offset + 1)) 159,
            frontierCoeff 15 (offset + 1) leftFrontier *
              frontierCoeff 15 (13 - (offset + 1))
                (159 - leftFrontier)) =
          ∑ offset ∈ {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11},
            if offset = 0 then 0 else if offset = 1 then 0 else if offset = 2 then 0 else if offset = 3 then 0 else if offset = 4 then 4 else if offset = 5 then 24 else if offset = 6 then 24 else if offset = 7 then 4 else if offset = 8 then 0 else if offset = 9 then 0 else if offset = 10 then 0 else if offset = 11 then 0 else 0 := by
        apply Finset.sum_congr rfl
        intro offset member
        simp only [Finset.mem_insert, Finset.mem_singleton] at member
        rcases member with (rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl | rfl) <;>
          norm_num only [split0, split1, split2, split3, split4, split5,
            split6, split7, split8, split9, split10, split11] <;> simp
      _ = 56 := by norm_num
  rw [frontierCoeff_succ_eq_supported]
  norm_num only [outer, zero_15_13_158] <;> simp

end AspisV7CompactFrontierDeltaCertificate
