[package]
name = "aspis-v8-comparison-registry-sbf"
version = "0.0.0"
edition = "2021"
publish = false
[workspace]
[lib]
crate-type = ["cdylib", "lib"]
path = "lib.rs"
[features]
default = ["custom-heap"]
custom-heap = []
custom-panic = []
[dependencies]
aspis-registry = { path = "../../../../../programs/aspis-registry", default-features = false, features = ["no-entrypoint"] }
solana-program = "=2.3.0"
[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
overflow-checks = true
