#!/usr/bin/env python3
"""Generate the sparse, factorized V7 compact-frontier delta certificate.

The V7 cap is 203, six below V6's cap 209.  The historical monolithic V7
certificate assumed that the V6 tail module exported a full recurrence table.
The current V6 certificate deliberately exports only its exact 753-cell sparse
dependency closure, so that assumption is both false and expensive to discover
inside Lean.

This generator treats the frozen V6 symbol inventory as a checked interface:

* scan the generated V6 sources and require exact agreement with the V6
  generator's dependency closure;
* stop recurrence traversal whenever an extant V6 certificate is reached;
* generate the remaining V7 cells with the same proved sparse-support
  recurrence used by V6;
* split declarations by depth and bounded recurrence workload; and
* emit a manifest listing every reused V6 symbol and every local V7 symbol.

The generator remains untrusted.  Lean kernel-checks every generated theorem.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from pathlib import Path

import generate_v6_compact_frontier_tail as v6


DEPTH = 18
SELECTED = 16
DELTA_LOW = 204
DELTA_HIGH = 209
EXPECTED_DELTA = int(
    "6915291501979218758486550434503151696943423928716542558271246420848672768"
)

MODULE_PREFIX = "AspisFormal.V7CompactFrontierDeltaCertificate"
NAMESPACE = "AspisV7CompactFrontierDeltaCertificate"
V6_NAMESPACE = "AspisV6CompactFrontierTailCertificate"
GENERATOR = "tools/generate_v7_compact_frontier_delta.py"
GENERATED_HEADER = f"/-! Generated by `{GENERATOR}`; do not edit."

CERTIFICATE_RE = re.compile(r"(?<![A-Za-z0-9_.])certificate_(\d+)_(\d+)_(\d+)")
V6_REFERENCE_RE = re.compile(
    rf"{V6_NAMESPACE}\.certificate_(\d+)_(\d+)_(\d+)"
)
SUPPORT_RE = re.compile(r"(?<![A-Za-z0-9_.])support_(\d+)_(\d+)")
V6_SUPPORT_REFERENCE_RE = re.compile(
    rf"{V6_NAMESPACE}\.support_(\d+)_(\d+)"
)
DECLARATION_RE = re.compile(
    r"^theorem certificate_(\d+)_(\d+)_(\d+)\s*:", re.MULTILINE
)
SUPPORT_DECLARATION_RE = re.compile(
    r"^theorem support_(\d+)_(\d+)\s*:", re.MULTILINE
)


State = tuple[int, int, int]
SupportState = tuple[int, int]


def state_name(state: State) -> str:
    depth, selected, frontier = state
    return f"certificate_{depth}_{selected}_{frontier}"


def state_from_match(match: re.Match[str]) -> State:
    return tuple(int(value) for value in match.groups())  # type: ignore[return-value]


def states_sha256(states: set[State]) -> str:
    surface = "".join(f"{state_name(state)}\n" for state in sorted(states))
    return hashlib.sha256(surface.encode("utf-8")).hexdigest()


def support_name(state: SupportState) -> str:
    depth, selected = state
    return f"support_{depth}_{selected}"


def support_states_sha256(states: set[SupportState]) -> str:
    surface = "".join(f"{support_name(state)}\n" for state in sorted(states))
    return hashlib.sha256(surface.encode("utf-8")).hexdigest()


def scan_v6_inventory(output: Path) -> tuple[set[State], dict[str, object]]:
    generated_dir = output.parent / "V6CompactFrontierTailCertificate"
    manifest_path = generated_dir / "manifest.json"
    if not manifest_path.is_file():
        raise SystemExit(f"missing V6 sparse manifest: {manifest_path}")

    actual: set[State] = set()
    for source in sorted(generated_dir.glob("*.lean")):
        text = source.read_text(encoding="utf-8")
        actual.update(state_from_match(match) for match in DECLARATION_RE.finditer(text))

    expected = v6.dependency_closure()
    missing = sorted(expected - actual)
    unexpected = sorted(actual - expected)
    if missing or unexpected:
        details: list[str] = []
        if missing:
            details.append(
                "missing V6 symbols: "
                + ", ".join(state_name(state) for state in missing[:16])
            )
        if unexpected:
            details.append(
                "unexpected V6 symbols: "
                + ", ".join(state_name(state) for state in unexpected[:16])
            )
        raise SystemExit("V6 sparse symbol inventory mismatch:\n" + "\n".join(details))

    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("ordinary_recurrence_cells") != len(expected):
        raise SystemExit("V6 manifest recurrence-cell count does not match source symbols")
    return actual, manifest


def scan_v6_support_inventory(output: Path) -> tuple[set[SupportState], Path]:
    support_path = output.parent / "V6CompactFrontierTailCertificate" / "Support.lean"
    if not support_path.is_file():
        raise SystemExit(f"missing V6 sparse support source: {support_path}")
    actual = {
        (int(match.group(1)), int(match.group(2)))
        for match in SUPPORT_DECLARATION_RE.finditer(
            support_path.read_text(encoding="utf-8")
        )
    }
    expected = {
        (depth, selected)
        for depth in range(DEPTH + 1)
        for selected in range(1, SELECTED + 1)
    }
    if actual != expected:
        missing = sorted(expected - actual)
        unexpected = sorted(actual - expected)
        raise SystemExit(
            "V6 sparse support inventory mismatch: "
            f"missing={','.join(support_name(state) for state in missing[:16])}; "
            f"unexpected={','.join(support_name(state) for state in unexpected[:16])}"
        )
    return actual, support_path


def delta_symbol_graph(v6_symbols: set[State]) -> tuple[set[State], set[State]]:
    needed: set[State] = {
        (DEPTH, SELECTED, frontier)
        for frontier in range(DELTA_LOW, DELTA_HIGH + 1)
    }
    pending = list(needed)
    while pending:
        state = pending.pop()
        if state in v6_symbols:
            continue
        for dependency in v6.dependencies(*state):
            if dependency not in needed:
                needed.add(dependency)
                pending.append(dependency)

    local = needed - v6_symbols
    external = needed & v6_symbols
    if len(local) != 412 or len(external) != 652:
        raise SystemExit(
            "unexpected V7 sparse closure shape: "
            f"local={len(local)}, external={len(external)}"
        )
    for state in local:
        unresolved = v6.dependencies(*state) - local - external
        if unresolved:
            raise SystemExit(
                f"unresolved dependencies for {state_name(state)}: "
                + ", ".join(state_name(value) for value in sorted(unresolved))
            )
    return local, external


def depth_states(states: set[State], depth: int) -> list[tuple[int, int]]:
    return sorted(
        (selected, frontier)
        for state_depth, selected, frontier in states
        if state_depth == depth
    )


def depth_name(depth: int) -> str:
    return f"Depth{depth:02d}"


def chunk_name(depth: int, chunk: int) -> str:
    return f"{depth_name(depth)}Chunk{chunk:03d}"


def qualify_v6_references(
    source: str, local: set[State], v6_symbols: set[State]
) -> str:
    def replace(match: re.Match[str]) -> str:
        state = state_from_match(match)
        if state in local:
            return match.group(0)
        if state in v6_symbols:
            return f"{V6_NAMESPACE}.{match.group(0)}"
        raise SystemExit(
            "generated proof referenced an unproved recurrence cell: "
            + state_name(state)
        )

    return CERTIFICATE_RE.sub(replace, source)


def qualify_v6_support_references(
    source: str, v6_support_symbols: set[SupportState]
) -> str:
    def replace(match: re.Match[str]) -> str:
        state = (int(match.group(1)), int(match.group(2)))
        if state not in v6_support_symbols:
            raise SystemExit(
                "generated proof referenced an unproved support theorem: "
                + support_name(state)
            )
        return f"{V6_NAMESPACE}.{match.group(0)}"

    return SUPPORT_RE.sub(replace, source)


def generate_chunk(
    depth: int,
    chunk: int,
    start_index: int,
    chunk_cost: int,
    states: list[tuple[int, int]],
    tables: list[dict[int, dict[int, int]]],
    local: set[State],
    v6_symbols: set[State],
    v6_support_symbols: set[SupportState],
) -> str:
    old_cap = v6.CAP
    try:
        v6.CAP = DELTA_LOW - 1
        source = v6.generate_chunk(
            depth, chunk, start_index, chunk_cost, states, tables
        )
    finally:
        v6.CAP = old_cap

    lines = source.splitlines()
    if depth == 0:
        raise SystemExit("V7 delta closure unexpectedly contains a depth-zero cell")
    expected_import = (
        "import AspisFormal.V6CompactFrontierTailCertificate."
        f"{depth_name(depth - 1)}"
    )
    if not lines or lines[0] != expected_import:
        raise SystemExit(
            f"unexpected inherited chunk import at depth {depth}: "
            + (lines[0] if lines else "<empty>")
        )
    lines[0] = f"import {MODULE_PREFIX}.{depth_name(depth - 1)}"
    source = "\n".join(lines) + "\n"
    source = source.replace(
        "tools/generate_v6_compact_frontier_tail.py", GENERATOR
    )
    source = source.replace(V6_NAMESPACE, NAMESPACE)
    source = qualify_v6_references(source, local, v6_symbols)
    source = qualify_v6_support_references(source, v6_support_symbols)
    return source


def generate_depth_aggregator(depth: int, chunk_count: int) -> str:
    imports = [
        *(f"import {MODULE_PREFIX}.{chunk_name(depth, chunk)}" for chunk in range(chunk_count)),
        f"import AspisFormal.V6CompactFrontierTailCertificate.{depth_name(depth)}",
    ]
    if depth > 0 and chunk_count == 0:
        imports.insert(0, f"import {MODULE_PREFIX}.{depth_name(depth - 1)}")
    return "\n".join(
        [
            *imports,
            "",
            GENERATED_HEADER,
            "This depth module re-exports exactly its local delta cells and the",
            "checked sparse V6 cells at the same depth. -/",
            "",
            "set_option autoImplicit false",
            "",
            f"namespace {NAMESPACE}",
            "",
            f"end {NAMESPACE}",
            "",
        ]
    )


def generate_delta_sum(tables: list[dict[int, dict[int, int]]]) -> str:
    expected = sum(
        tables[DEPTH].get(SELECTED, {}).get(frontier, 0) * (1 << frontier)
        for frontier in range(DELTA_LOW, DELTA_HIGH + 1)
    )
    if expected != EXPECTED_DELTA:
        raise SystemExit(f"unexpected compact delta: {expected}")
    weighted = [
        f"weighted_certificate_{DEPTH}_{SELECTED}_{frontier}"
        for frontier in range(DELTA_LOW, DELTA_HIGH + 1)
    ]
    return "\n".join(
        [
            f"import {MODULE_PREFIX}.{depth_name(DEPTH)}",
            "",
            GENERATED_HEADER,
            "The final sum expands only six already-kernel-checked weighted cells. -/",
            "",
            "set_option autoImplicit false",
            "",
            f"namespace {NAMESPACE}",
            "",
            "open AspisV6CompactFrontierRecurrence",
            "",
            "/-- Exact schedules admitted by cap 209 but rejected by cap 203. -/",
            "def compactDelta : Nat :=",
            f"  ∑ frontier ∈ Finset.Icc {DELTA_LOW} {DELTA_HIGH},",
            f"    concreteFrontierCount {DEPTH} {SELECTED} frontier",
            "",
            "def expectedCompactDelta : Nat :=",
            f"  {expected}",
            "",
            "theorem compactDelta_eq_expected :",
            "    compactDelta = expectedCompactDelta := by",
            "  unfold compactDelta expectedCompactDelta",
            "  norm_num only [Finset.sum_Icc_succ_top,",
            *(f"    {name}," for name in weighted[:-1]),
            f"    {weighted[-1]}",
            "  ]",
            "  rw [Finset.Icc_eq_empty_of_lt (by omega), Finset.sum_empty]",
            "",
            "#print axioms compactDelta_eq_expected",
            "",
            f"end {NAMESPACE}",
            "",
        ]
    )


def generate_wrapper() -> str:
    return "\n".join(
        [
            f"import {MODULE_PREFIX}.DeltaSum",
            "",
            GENERATED_HEADER,
            "The historical public module re-exports the factorized delta sum. -/",
            "",
        ]
    )


def symbol_sets_from_contents(contents: list[str]) -> tuple[set[State], set[State]]:
    local: set[State] = set()
    external: set[State] = set()
    for content in contents:
        local.update(state_from_match(match) for match in DECLARATION_RE.finditer(content))
        external.update(
            state_from_match(match) for match in V6_REFERENCE_RE.finditer(content)
        )
    return local, external


def support_symbols_from_contents(contents: list[str]) -> set[SupportState]:
    external: set[SupportState] = set()
    for content in contents:
        external.update(
            (int(match.group(1)), int(match.group(2)))
            for match in V6_SUPPORT_REFERENCE_RE.finditer(content)
        )
    return external


def generated_files(output: Path) -> dict[Path, str]:
    v6_symbols, v6_manifest = scan_v6_inventory(output)
    v6_support_symbols, v6_support_path = scan_v6_support_inventory(output)
    local, external = delta_symbol_graph(v6_symbols)
    tables = v6.coefficient_tables()
    generated_dir = output.with_suffix("")
    files: dict[Path, str] = {}
    depth_manifest: list[dict[str, int]] = []

    for depth in range(DEPTH + 1):
        states = depth_states(local, depth)
        chunks = v6.partition_states(states) if states else []
        for chunk, (start_index, chunk_states, chunk_cost) in enumerate(chunks):
            files[generated_dir / f"{chunk_name(depth, chunk)}.lean"] = generate_chunk(
                depth,
                chunk,
                start_index,
                chunk_cost,
                chunk_states,
                tables,
                local,
                v6_symbols,
                v6_support_symbols,
            )
        files[generated_dir / f"{depth_name(depth)}.lean"] = (
            generate_depth_aggregator(depth, len(chunks))
        )
        depth_manifest.append(
            {
                "depth": depth,
                "local_cells": len(states),
                "external_v6_cells": sum(state[0] == depth for state in external),
                "chunks": len(chunks),
                "max_chunk_cells": max(
                    (len(chunk_states) for _, chunk_states, _ in chunks), default=0
                ),
                "max_chunk_cost": max(
                    (chunk_cost for _, _, chunk_cost in chunks), default=0
                ),
            }
        )

    files[generated_dir / "DeltaSum.lean"] = generate_delta_sum(tables)
    files[output] = generate_wrapper()

    lean_contents = [content for path, content in files.items() if path.suffix == ".lean"]
    actual_local, actual_external = symbol_sets_from_contents(lean_contents)
    if actual_local != local:
        raise SystemExit("generated V7 local symbol surface does not match closure")
    if actual_external != external:
        missing = external - actual_external
        unexpected = actual_external - external
        raise SystemExit(
            "generated V6 reference surface mismatch: "
            f"missing={len(missing)}, unexpected={len(unexpected)}"
        )
    referenced_support = support_symbols_from_contents(lean_contents)
    if not referenced_support or not referenced_support <= v6_support_symbols:
        raise SystemExit("generated V6 support reference surface is invalid")

    lean_hashes = {
        str(path.relative_to(output.parent)): hashlib.sha256(
            content.encode("utf-8")
        ).hexdigest()
        for path, content in sorted(files.items(), key=lambda item: str(item[0]))
    }
    v6_manifest_path = output.parent / "V6CompactFrontierTailCertificate" / "manifest.json"
    manifest = {
        "schema": "aspis-v7-compact-frontier-delta-sparse-v1",
        "generator": GENERATOR,
        "delta_low": DELTA_LOW,
        "delta_high": DELTA_HIGH,
        "expected_compact_delta": EXPECTED_DELTA,
        "v6_manifest_sha256": hashlib.sha256(v6_manifest_path.read_bytes()).hexdigest(),
        "v6_canonical_theorem_surface_sha256": v6_manifest.get(
            "canonical_theorem_surface_sha256"
        ),
        "v6_extant_symbol_count": len(v6_symbols),
        "v6_extant_symbols_sha256": states_sha256(v6_symbols),
        "v6_referenced_symbol_count": len(external),
        "v6_referenced_symbols_sha256": states_sha256(external),
        "v6_referenced_symbols": [state_name(state) for state in sorted(external)],
        "v6_support_source_sha256": hashlib.sha256(
            v6_support_path.read_bytes()
        ).hexdigest(),
        "v6_support_symbol_count": len(v6_support_symbols),
        "v6_support_symbols_sha256": support_states_sha256(v6_support_symbols),
        "v6_referenced_support_symbol_count": len(referenced_support),
        "v6_referenced_support_symbols_sha256": support_states_sha256(
            referenced_support
        ),
        "v6_referenced_support_symbols": [
            support_name(state) for state in sorted(referenced_support)
        ],
        "v7_local_symbol_count": len(local),
        "v7_local_symbols_sha256": states_sha256(local),
        "v7_local_symbols": [state_name(state) for state in sorted(local)],
        "depths": depth_manifest,
        "lean_sha256": lean_hashes,
    }
    files[generated_dir / "manifest.json"] = (
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    return files


def existing_generated_files(output: Path) -> set[Path]:
    generated_dir = output.with_suffix("")
    if not generated_dir.exists():
        return set()
    return {
        path
        for path in generated_dir.iterdir()
        if path.is_file() and (path.suffix == ".lean" or path.name == "manifest.json")
    }


def check_symbols(output: Path) -> None:
    expected = generated_files(output)
    manifest_path = output.with_suffix("") / "manifest.json"
    if not manifest_path.is_file():
        raise SystemExit(f"missing V7 sparse symbol manifest: {manifest_path}")
    if manifest_path.read_text(encoding="utf-8") != expected[manifest_path]:
        raise SystemExit("V7 sparse symbol manifest is changed or stale")

    actual_sources = [
        path.read_text(encoding="utf-8")
        for path in sorted(existing_generated_files(output))
        if path.suffix == ".lean"
    ]
    actual_local, actual_external = symbol_sets_from_contents(actual_sources)
    expected_local, expected_external = symbol_sets_from_contents(
        [content for path, content in expected.items() if path.suffix == ".lean"]
    )
    if actual_local != expected_local or actual_external != expected_external:
        raise SystemExit("V7 generated source symbols do not match the frozen manifest")
    actual_support = support_symbols_from_contents(actual_sources)
    expected_support = support_symbols_from_contents(
        [content for path, content in expected.items() if path.suffix == ".lean"]
    )
    if actual_support != expected_support:
        raise SystemExit("V7 generated support symbols do not match the frozen manifest")
    print(
        "V7 sparse symbol manifest: PASS "
        f"({len(actual_local)} local, {len(actual_external)} reused V6 cells, "
        f"{len(actual_support)} reused support theorems)"
    )


def check(output: Path) -> None:
    expected = generated_files(output)
    expected_paths = set(expected)
    actual_paths = existing_generated_files(output)
    if output.exists():
        actual_paths.add(output)
    problems: list[str] = []
    for path in sorted(expected_paths - actual_paths):
        problems.append(f"missing: {path}")
    for path in sorted(actual_paths - expected_paths):
        problems.append(f"unexpected stale generated file: {path}")
    for path in sorted(expected_paths & actual_paths):
        if path.read_text(encoding="utf-8") != expected[path]:
            problems.append(f"changed or stale: {path}")
    if problems:
        raise SystemExit("generated V7 delta check failed:\n" + "\n".join(problems))
    check_symbols(output)
    print(
        f"V7 split delta certificate: PASS ({len(expected) - 1} generated parts)"
    )


def generate(output: Path) -> None:
    expected = generated_files(output)
    generated_dir = output.with_suffix("")
    generated_dir.mkdir(parents=True, exist_ok=True)
    obsolete = existing_generated_files(output) - set(expected)
    for path in sorted(obsolete):
        path.unlink()
    for path, content in sorted(expected.items(), key=lambda item: str(item[0])):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    check(output)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--check-symbols", action="store_true")
    args = parser.parse_args()
    if args.check and args.check_symbols:
        parser.error("choose at most one of --check and --check-symbols")
    if args.check:
        check(args.output)
    elif args.check_symbols:
        check_symbols(args.output)
    else:
        generate(args.output)


if __name__ == "__main__":
    main()
