import AspisFormal.K1.V7Tag73GammaRestoredK14CausalSource

/-!
# Pointwise fibre reduction for restored-gamma K1.4

This leaf reduces the source-facing K1.4 event inclusion to the three literal
facts that the production trace must establish at the selected restored
gamma child:

* the routed duplex tape successfully decodes;
* the authenticated width-29 word is the word fixed by the non-gamma
  residual; and
* the child's decoded gamma is the value of that routed tape.

The counterfactual response provider, exact sample round-trip, retained
failure witness, and width-29 target membership are constructed here.  Thus
none of those objects remains a source premise.
-/

set_option autoImplicit false
set_option maxRecDepth 1000000
set_option maxHeartbeats 5000000
set_option linter.constructorNameAsVariable false

namespace AspisK1.V7Tag73GammaRestoredK14FibreAlignment

open AspisK1.V7FsAokExperiment
open AspisK1.V7Tag73AdaptiveLazyOracle
open AspisK1.V7Tag73CausalGammaPrefixCoordinates
open AspisK1.V7Tag73CausalRestoredFamily
open AspisK1.V7Tag73ExactClientKnowledgeComposition
open AspisK1.V7Tag73ExactCompilerResources
open AspisK1.V7Tag73ExactFixedK12MerkleClassifier
open AspisK1.V7Tag73ExactFixedK13K14FailureReduction
open AspisK1.V7Tag73ExactRestoredGammaFullRouting
open AspisK1.V7Tag73ExactRestoredOperationalK13Classifier
open AspisK1.V7Tag73ExactRestoredOperationalStages
open AspisK1.V7Tag73ExactSourceAcceptanceModel
open AspisK1.V7Tag73GammaRestoredK14CausalSource
open AspisK1.V7Tag73GammaRestoredK14Scope
open AspisK1.V7Tag73K14FamilyFailureMembership
open AspisK1.V7Tag73RestoredDerivedK13View
open AspisK1.V7Tag73RestoredGammaFibreK14Membership
open AspisK1.V7Tag73RestoredGammaFibreK14Provider
open AspisK1.V7Tag73RestoredGammaFibreK14Target
open AspisK1.V7Tag73RestoredPointCompatibleK14
open AspisK1.V7Tag73SuccessfulSamplerConditioningBridge
open AspisK1.V7Tag73TranscriptSchedule
open AspisK1.V7Tag73VariablePrefixGammaFactorization
open AspisK1.V7Tag73VariablePrefixGammaFlatRouting
open AspisK1.V7Tag73VariablePrefixGammaSampler
open AspisK1.V7Tag73VariablePrefixK14Probability
open AspisPool.AlgorithmicCircleDecoderV7
open AspisPool.V7CoherentTraceExtraction
open AspisPool.V7ExtractedLaneWords
open AspisV5ComponentCQM31TowerExact
open AspisV6PublishedTheoremInterfaces
open AspisV6Width29CorrelatedAgreement

noncomputable section

/-- The exact source facts that remain after fixing the restored-gamma
coordinate equivalence.  These are value equalities, not a probability bound
or a conclusion-shaped finite-set membership premise. -/
structure ExactTag73GammaRestoredK14FibreAlignment
    {HiddenTape TapeIdentity Observation Statement Payload Witness : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat)
    (configuration : ExactPlainRomWitnessConfiguration HiddenTape TapeIdentity
      Observation Statement Tag73K12ParsedProof Payload Witness parameters)
    (projection : AcceptedTapeProjection Statement Tag73K12ParsedProof Payload)
    (fixedInstance : PublicInstance Statement)
    (decoder : ExactDecoderInstantiation QM31Exact)
    (clean : Set (ExactCompilerSample HiddenTape parameters)) where
  words : HiddenTape → ExactCompilerGammaPrefixResidual parameters →
    AspisPool.V7MerkleQueryExtractor.ExtractedWords
  defaultResponse : InitialMessage QM31Exact
  defaultDisclosedFinal : FinalMessage QM31Exact
  defaultSchedule : ExactSchedule
  defaultSelected : ExactCandidatePair
  exactAt : ∀ (hidden : HiddenTape)
      (answers : FreshAnswerTape Digest256
        (exactCompilerTargetCaps parameters).length)
      (_cleanMember : (hidden, answers) ∈ clean)
      (input : ExactK12OperationalInput transitionFuel configuration projection
        fixedInstance (hidden, answers))
      (k13 : ExactGammaRestoredOperationalK13Certificate decoder input)
      (_failure : Width29DecompositionFailure decoder
        k13.certificate.classified.k12.words
        (restoredOperationalK13View k13.certificate.data).gamma
        (restoredOperationalK13View k13.certificate.data).disclosedFinal
        (restoredOperationalK13View k13.certificate.data).schedule),
    let coordinates := exactCompilerRestoredGammaCoordinates transitionFuel
      configuration hidden answers
    ∃ success : GammaPrefixSucceeds coordinates.2,
      let factored := successfulGammaPrefixFactorization
        (⟨coordinates.2, success⟩ : SuccessfulGammaPrefixTape)
      k13.certificate.classified.k12.words = words hidden coordinates.1 ∧
        (restoredOperationalK13View k13.certificate.data).gamma = factored.2.1

/-- Exact fibre equalities construct the complete deterministic causal source.
In particular, the provider is generated by running the literal compiler over
the whole nonzero-gamma fibre; it is not supplied by the caller. -/
noncomputable def ExactTag73GammaRestoredK14FibreAlignment.toCausalSource
    {HiddenTape TapeIdentity Observation Statement Payload Witness : Type}
    {parameters : ExactCompilerResourceParameters}
    {transitionFuel : Nat}
    {configuration : ExactPlainRomWitnessConfiguration HiddenTape TapeIdentity
      Observation Statement Tag73K12ParsedProof Payload Witness parameters}
    {projection : AcceptedTapeProjection Statement Tag73K12ParsedProof Payload}
    {fixedInstance : PublicInstance Statement}
    {decoder : ExactDecoderInstantiation QM31Exact}
    {clean : Set (ExactCompilerSample HiddenTape parameters)}
    (alignment : ExactTag73GammaRestoredK14FibreAlignment transitionFuel
      configuration projection fixedInstance decoder clean) :
    ExactTag73GammaRestoredK14CausalSource transitionFuel configuration
      projection fixedInstance decoder clean where
  words := alignment.words
  defaultResponse := alignment.defaultResponse
  defaultDisclosedFinal := alignment.defaultDisclosedFinal
  defaultSchedule := alignment.defaultSchedule
  defaultSelected := alignment.defaultSelected
  alignedAt := by
    intro hidden answers cleanMember input k13 failure
    obtain ⟨success, wordsExact, gammaExact⟩ :=
      alignment.exactAt hidden answers cleanMember input k13 failure
    let coordinates := exactCompilerRestoredGammaCoordinates transitionFuel
      configuration hidden answers
    let flat : SuccessfulGammaPrefixTape := ⟨coordinates.2, success⟩
    let factored := successfulGammaPrefixFactorization flat
    have roundtrip :
        exactRestoredGammaFibreSample transitionFuel configuration hidden
            coordinates.1
            (successfulRestoredGammaTape factored.1 factored.2) =
          (hidden, answers) := by
      exact exact_restored_gamma_fibre_sample_roundtrip transitionFuel
        configuration hidden answers success
    let FibreData := fun sample : ExactCompilerSample HiddenTape parameters ↦
      Σ input : ExactK12OperationalInput transitionFuel configuration
          projection fixedInstance sample,
        { k13 : ExactRestoredOperationalK13Certificate decoder input //
          k13.classified.k12.words = alignment.words hidden coordinates.1 ∧
            (restoredOperationalK13View k13.data).gamma = factored.2.1 ∧
            Width29DecompositionFailure decoder k13.classified.k12.words
              (restoredOperationalK13View k13.data).gamma
              (restoredOperationalK13View k13.data).disclosedFinal
              (restoredOperationalK13View k13.data).schedule }
    let actualData : FibreData (hidden, answers) :=
      ⟨input, ⟨k13.certificate, wordsExact, gammaExact, failure⟩⟩
    let fibreData : FibreData
        (exactRestoredGammaFibreSample transitionFuel configuration hidden
          coordinates.1
          (successfulRestoredGammaTape factored.1 factored.2)) :=
      roundtrip.symm ▸ actualData
    let witness : RestoredGammaFibreK14FailureWitness transitionFuel
        configuration projection fixedInstance decoder
          (alignment.words hidden coordinates.1) hidden coordinates.1
            factored.1 factored.2.1 := by
      exact restoredGammaFibreK14FailureWitnessOfActual factored.2.2
        fibreData.1 fibreData.2.1 fibreData.2.2.1 fibreData.2.2.2.1
          fibreData.2.2.2.2
    apply mem_preimage_dependent_k14_of_factored
      (exactCompilerRestoredGammaCoordinates transitionFuel configuration
        hidden) answers
      (fun residual ↦ variablePrefixK14FailureGammaTarget
        (exactGammaRestoredK14CausalProvider transitionFuel configuration
          projection fixedInstance decoder alignment.words
            alignment.defaultResponse alignment.defaultDisclosedFinal
              alignment.defaultSchedule alignment.defaultSelected hidden
                residual))
      success
    change factored.2.1 ∈ variablePrefixK14FailureGammaTarget
      (fun _ ↦ restoredGammaFibreCompactK14Provider transitionFuel
        configuration projection fixedInstance decoder
          (alignment.words hidden coordinates.1) hidden coordinates.1
            alignment.defaultResponse alignment.defaultDisclosedFinal
              alignment.defaultSchedule alignment.defaultSelected factored.1)
      factored.1
    let target := restoredGammaFibreK14FailureTarget witness
    let Realized := RestoredGammaFibreK14TargetRealized transitionFuel
      configuration projection fixedInstance decoder
        (alignment.words hidden coordinates.1) hidden coordinates.1 factored.1
          factored.2.1
    have targetRealized : Realized target := ⟨⟨witness, rfl⟩⟩
    have existsTarget : ∃ selected : RestoredGammaFibreK14TargetWitness
        decoder (alignment.words hidden coordinates.1) factored.2.1,
      Realized selected := ⟨target, targetRealized⟩
    let selectedTarget := Classical.choose existsTarget
    have branchExact :
        (restoredGammaFibreCompactK14Provider transitionFuel configuration
          projection fixedInstance decoder
            (alignment.words hidden coordinates.1) hidden coordinates.1
              alignment.defaultResponse alignment.defaultDisclosedFinal
                alignment.defaultSchedule alignment.defaultSelected
                  factored.1).branch factored.2.1 =
            some selectedTarget.branch := by
      unfold restoredGammaFibreCompactK14Provider
      dsimp only
      rw [dif_pos existsTarget]
    rcases selectedTarget with ⟨nonzero, branch, selectedFailure, chosenExact⟩
    have selected := k13_family_selected_of_branch
      (restoredGammaFibreCompactK14Provider transitionFuel configuration
        projection fixedInstance decoder (alignment.words hidden coordinates.1)
          hidden coordinates.1 alignment.defaultResponse
            alignment.defaultDisclosedFinal alignment.defaultSchedule
              alignment.defaultSelected factored.1)
      factored.2.1 branch branchExact
    let family := restoredSelectedChainFamilyOfK13Provider
      (restoredGammaFibreCompactK14Provider transitionFuel configuration
        projection fixedInstance decoder (alignment.words hidden coordinates.1)
          hidden coordinates.1 alignment.defaultResponse
            alignment.defaultDisclosedFinal alignment.defaultSchedule
              alignment.defaultSelected factored.1)
    have available : family.available factored.2.1 := by
      simpa only [family] using selected.1
    have selectedExact : family.selected factored.2.1 =
        Classical.choose selectedFailure := by
      simpa only [family] using selected.2.trans chosenExact
    let chosen := Classical.choose selectedFailure
    have chosenFacts := Classical.choose_spec selectedFailure
    have responseAt : family.response factored.2.1 = chosen.1 := by
      calc
        family.response factored.2.1 =
            (family.selected factored.2.1).1 :=
          family.responseAt factored.2.1 available
        _ = chosen.1 := by
          simpa only [chosen] using congrArg Prod.fst selectedExact
    have fixedMember : factored.2.1 ∈
        width29GoodChallenges decoder.initialEncoder
          AspisV6PublishedTheoremInterfaces.initialAgreementThreshold
          (extractedWidth29InitialWords
            (alignment.words hidden coordinates.1))
          (width29BadStrategy decoder.initialEncoder
            AspisV6PublishedTheoremInterfaces.initialAgreementThreshold
            (extractedWidth29InitialWords
              (alignment.words hidden coordinates.1))
            (selectedCandidateStrategy decoder
              (extractedWidth29InitialWords
                (alignment.words hidden coordinates.1)) chosen)) := by
      rw [mem_width29BadStrategy_good_iff]
      refine ⟨nonzero, ?_, chosenFacts.2⟩
      exact selected_chain_yields_valid_width29_response decoder
        (alignment.words hidden coordinates.1) factored.2.1
        branch.disclosedFinal branch.schedule chosen chosenFacts.1
    rw [mem_width29BadStrategy_good_iff] at fixedMember
    unfold variablePrefixK14FailureGammaTarget
    rw [mem_width29BadStrategy_good_iff]
    have supportEq := restoredWidth29Strategy_support_eq_selected decoder
      (extractedWidth29InitialWords (alignment.words hidden coordinates.1))
      chosen family.response factored.2.1 responseAt
    have restoredValid : Width29ValidResponse decoder.initialEncoder
        AspisV6PublishedTheoremInterfaces.initialAgreementThreshold
        (extractedWidth29InitialWords (alignment.words hidden coordinates.1))
        (restoredWidth29Strategy decoder
          (extractedWidth29InitialWords (alignment.words hidden coordinates.1))
          family.response) factored.2.1 := by
      constructor
      · rw [supportEq]
        exact fixedMember.2.1.1
      · intro index member
        rw [supportEq] at member
        have fixedAgreement := fixedMember.2.1.2 index member
        rw [restoredWidth29Strategy_candidate, responseAt]
        rw [selectedCandidateStrategy_candidate] at fixedAgreement
        exact fixedAgreement
    have restoredNoMatching : ¬ HasMatchingWidth29Decomposition
        decoder.initialEncoder
        (extractedWidth29InitialWords (alignment.words hidden coordinates.1))
        (restoredWidth29Strategy decoder
          (extractedWidth29InitialWords (alignment.words hidden coordinates.1))
          family.response) factored.2.1 := by
      intro restoredMatching
      apply fixedMember.2.2
      rcases restoredMatching with ⟨components, shared, onCurve⟩
      refine ⟨components, ?_, ?_⟩
      · rw [← supportEq]
        exact shared
      · unfold Width29CandidateOnCurve at onCurve ⊢
        rw [restoredWidth29Strategy_candidate, responseAt] at onCurve
        rw [selectedCandidateStrategy_candidate]
        exact onCurve
    exact ⟨fixedMember.1, restoredValid, restoredNoMatching⟩

#print axioms ExactTag73GammaRestoredK14FibreAlignment
#print axioms ExactTag73GammaRestoredK14FibreAlignment.toCausalSource

end
end AspisK1.V7Tag73GammaRestoredK14FibreAlignment
