import AspisFormal.K1.V7Tag73VariablePrefixGammaSampler

/-!
# Exact duplex coordinates for the variable-prefix gamma sampler

The returned gamma depends on squeeze outputs, while the next squeeze input
depends on the paired advance answer.  This file packages both answers in one
fixed twelve-block counterfactual tape and executes that tape without an
oracle.  Its input trace is therefore fixed by the pre-gamma machine state
and the complete tape before the returned gamma coordinate is inspected.

`GammaDuplexAnswers` is an equality predicate for an actual hash oracle.  It
proves that the counterfactual execution is the literal production
`squeezeBlocks` execution on every consumed prefix.  Unread coordinates are
never queried by the prefix theorem.
-/

set_option autoImplicit false

namespace AspisK1.V7Tag73VariablePrefixGammaCoordinates

open AspisK1.V7Tag73TranscriptSchedule
open AspisK1.V7Tag73VariablePrefixGammaSampler
open AspisK1.V7Tag73SamplerDecoder
open AspisK1.V7Tag73IncrementalSamplerControl
open AspisK1.V7Tag73SemanticTranscriptBridge

noncomputable section

abbrev GammaDuplexBlock := Digest256 × Digest256

/-- The output and advance halves of the total tape paired chronologically. -/
def gammaDuplexBlocks (tape : TotalGammaDuplexTape) :
    List GammaDuplexBlock :=
  List.ofFn fun index : Fin 12 => (tape.1 index, tape.2 index)

@[simp] theorem gammaDuplexBlocks_length (tape : TotalGammaDuplexTape) :
    (gammaDuplexBlocks tape).length = 12 := by
  simp [gammaDuplexBlocks]

@[simp] theorem gammaDuplexBlocks_outputs (tape : TotalGammaDuplexTape) :
    (gammaDuplexBlocks tape).map Prod.fst = gammaOutputBlocks tape := by
  simp [gammaDuplexBlocks, gammaOutputBlocks]

/-- One oracle-free duplex transition using a supplied output/advance pair.
Both literal production queries are retained in the semantic history. -/
def applyGammaDuplexBlock
    (state : MachineState) (block : GammaDuplexBlock) : MachineState :=
  { digest := block.2
    oracleHistory := state.oracleHistory ++
      [{ input := squeezeOutputInput state, output := block.1 },
       { input := squeezeAdvanceInput state, output := block.2 }] }

/-- Oracle-free execution of a chronological duplex-block list. -/
def runGammaDuplexBlocks :
    List GammaDuplexBlock → MachineState → MachineState
  | [], state => state
  | block :: rest, state =>
      runGammaDuplexBlocks rest (applyGammaDuplexBlock state block)

/-- Literal sequence of output/advance inputs generated by the supplied
counterfactual tape. -/
def gammaDuplexInputTrace :
    MachineState → List GammaDuplexBlock → List ByteString
  | _, [] => []
  | state, block :: rest =>
      squeezeOutputInput state :: squeezeAdvanceInput state ::
        gammaDuplexInputTrace (applyGammaDuplexBlock state block) rest

@[simp] theorem gammaDuplexInputTrace_length
    (state : MachineState) (blocks : List GammaDuplexBlock) :
    (gammaDuplexInputTrace state blocks).length = 2 * blocks.length := by
  induction blocks generalizing state with
  | nil => rfl
  | cons block rest ih =>
      simp [gammaDuplexInputTrace, ih]
      omega

/-- Exact recursive assertion that an actual oracle supplies the fixed tape
answers at the literal states reached by those same answers. -/
def GammaDuplexAnswers (oracle : HashOracle) :
    MachineState → List GammaDuplexBlock → Prop
  | _, [] => True
  | state, block :: rest =>
      oracle.answer (squeezeOutputInput state) = block.1 ∧
      oracle.answer (squeezeAdvanceInput state) = block.2 ∧
      GammaDuplexAnswers oracle (applyGammaDuplexBlock state block) rest

/-- Exact production equality for any fixed answered block list. -/
theorem squeezeBlocks_eq_runGammaDuplexBlocks
    (oracle : HashOracle) (state : MachineState)
    (blocks : List GammaDuplexBlock)
    (answers : GammaDuplexAnswers oracle state blocks) :
    squeezeBlocks oracle blocks.length state =
      (blocks.map Prod.fst, runGammaDuplexBlocks blocks state) := by
  induction blocks generalizing state with
  | nil => rfl
  | cons block rest ih =>
      rcases answers with ⟨outputExact, advanceExact, tailAnswers⟩
      have tail := ih (applyGammaDuplexBlock state block) tailAnswers
      simp only [List.length_cons, squeezeBlocks, squeezeBlock]
      rw [outputExact, advanceExact]
      simp only [applyGammaDuplexBlock, runGammaDuplexBlocks] at tail ⊢
      rw [tail]
      rfl

/-- A full answer trace implies the same literal equalities on every prefix;
the suffix is neither inspected nor required to satisfy anything. -/
theorem gammaDuplexAnswers_take
    (oracle : HashOracle) (state : MachineState)
    (blocks : List GammaDuplexBlock)
    (answers : GammaDuplexAnswers oracle state blocks)
    (count : Nat) :
    GammaDuplexAnswers oracle state (blocks.take count) := by
  induction blocks generalizing state count with
  | nil => simp [GammaDuplexAnswers]
  | cons block rest ih =>
      cases count with
      | zero => simp [GammaDuplexAnswers]
      | succ count =>
          rcases answers with ⟨outputExact, advanceExact, tailAnswers⟩
          exact ⟨outputExact, advanceExact,
            ih (applyGammaDuplexBlock state block) tailAnswers count⟩

/-- The full twelve-coordinate equality exposes the exact output list used
by the offline stopping decoder and the exact state after all twelve ghost
coordinates. -/
theorem squeezeBlocks_eq_totalGammaDuplexTape
    (oracle : HashOracle) (state : MachineState)
    (tape : TotalGammaDuplexTape)
    (answers : GammaDuplexAnswers oracle state (gammaDuplexBlocks tape)) :
    squeezeBlocks oracle 12 state =
      (gammaOutputBlocks tape,
        runGammaDuplexBlocks (gammaDuplexBlocks tape) state) := by
  simpa using squeezeBlocks_eq_runGammaDuplexBlocks oracle state
    (gammaDuplexBlocks tape) answers

/-- The production sampler and oracle-free counterfactual tape agree at the
actual stopping count.  The final state is computed from only the consumed
prefix, so unread suffix streams are observationally irrelevant. -/
theorem answeredGammaTape_matches_sampleChallenge
    (oracle : HashOracle) (state : MachineState)
    (tape : TotalGammaDuplexTape) (decoded : OrdinaryPrefixDecode)
    (run : runGammaPrefix tape = some decoded)
    (answers : GammaDuplexAnswers oracle state (gammaDuplexBlocks tape)) :
    ∃ count,
      0 < count ∧ count ≤ 12 ∧
      sampleChallenge oracle .gamma state =
        some (decoded.value,
          runGammaDuplexBlocks ((gammaDuplexBlocks tape).take count) state) := by
  have fullRun := squeezeBlocks_eq_totalGammaDuplexTape oracle state tape
    answers
  obtain ⟨count, finalState, positive, within, sampled, consumedRun⟩ :=
    runGammaPrefix_matches_sampleChallenge oracle state tape decoded run
      (congrArg Prod.fst fullRun)
  have prefixAnswers := gammaDuplexAnswers_take oracle state
    (gammaDuplexBlocks tape) answers count
  have ghostRun := squeezeBlocks_eq_runGammaDuplexBlocks oracle state
    ((gammaDuplexBlocks tape).take count) prefixAnswers
  have prefixLength : ((gammaDuplexBlocks tape).take count).length = count := by
    rw [List.length_take_of_le]
    simpa using within
  have outputExact :
      ((gammaDuplexBlocks tape).take count).map Prod.fst =
        (gammaOutputBlocks tape).take count := by
    rw [List.map_take, gammaDuplexBlocks_outputs]
  have finalExact :
      finalState =
        runGammaDuplexBlocks ((gammaDuplexBlocks tape).take count) state := by
    rw [prefixLength, outputExact] at ghostRun
    exact congrArg Prod.snd (consumedRun.symm.trans ghostRun)
  exact ⟨count, positive, within, by simpa [finalExact] using sampled⟩

/-- The complete target-input list is fixed by the pre-gamma state and the
total nuisance tape and has exactly twenty-four possible query coordinates.
Actual execution consumes a prefix of this list. -/
def gammaSamplerTargetInputs
    (state : MachineState) (tape : TotalGammaDuplexTape) : List ByteString :=
  gammaDuplexInputTrace state (gammaDuplexBlocks tape)

@[simp] theorem gammaSamplerTargetInputs_length
    (state : MachineState) (tape : TotalGammaDuplexTape) :
    (gammaSamplerTargetInputs state tape).length = 24 := by
  simp [gammaSamplerTargetInputs]

#print axioms gammaDuplexBlocks_outputs
#print axioms gammaDuplexInputTrace_length
#print axioms squeezeBlocks_eq_runGammaDuplexBlocks
#print axioms gammaDuplexAnswers_take
#print axioms squeezeBlocks_eq_totalGammaDuplexTape
#print axioms answeredGammaTape_matches_sampleChallenge
#print axioms gammaSamplerTargetInputs_length

end

end AspisK1.V7Tag73VariablePrefixGammaCoordinates
