import AspisFormal.K1.V7Tag73ExactSourceAcceptanceModel
import AspisFormal.K1.V7Tag73ExactCompilerTargetClean

/-!
# The concrete clean-source event for the exact Tag-73 compiler

The deployed-source event and the adaptive scheduler target event live on the
same literal `(hiddenTape, masterTape)` sample.  This module fixes the event
that will be offered to the K1.2--K1.5 state-restoration theorem:

* the actual initial-only Tag-73 scheduler returned a strict checked source
  refinement; and
* the actual result-carrying scheduler target tree did not hit.

This is not a caller-selected `world` or trace-cover predicate.  Membership is
an executable source fact together with the complement of the already bounded
causal target event.  The principal theorem below constructs the exact
ROM-free root execution and canonical complete verifier path, and proves that
the same master tape is target-clean for the actual full cursor.  A later leaf
extends this root certificate with every operational child generated by the
concrete restoration client.
-/

set_option autoImplicit false

namespace AspisK1.V7Tag73ExactLegalSameTapeEvent

open AspisK1.V7Tag73RawSameTapeSource
open AspisK1.V7Tag73TranscriptSchedule
open AspisK1.V7Tag73DeterministicRefinement
open AspisK1.V7Tag73FutureFreeFullControl
open AspisK1.V7Tag73RawFutureFreeDriver
open AspisK1.V7Tag73SchedulerNativePlainRomExperiment
open AspisK1.V7Tag73ConcreteRestorationClient
open AspisK1.V7Tag73ExactCompilerResources
open AspisK1.V7Tag73ExactPlainRomRun
open AspisK1.V7Tag73ExactSourceAcceptanceModel
open AspisK1.V7Tag73ExactCompilerTargetClean
open AspisK1.V7Tag73CoupledReplayAlignment
open AspisK1.V7Tag73CanonicalFutureFreeFuel
open AspisK1.V7Tag73CheckedRefinementFullFutureFreePath
open AspisK1.V7Tag73CheckedPathActualRunAlignment
open AspisK1.V7Tag73FutureFreeCheckedRefinementBisimulation
open AspisK1.V7Tag73SecureCircleMap
open AspisK1.V7Tag73Q16LedgerCertificate

noncomputable section

/-! ## One fixed, operational event -/

/-- The clean source event is a literal set difference on the one exact joint
experiment.  In particular, neither operand is supplied by a theorem caller. -/
def exactPlainRomLegalSameTapeEvent
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat)
    (configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters)
    (projection : AcceptedTapeProjection Statement Proof Payload) :
    Set (ExactCompilerSample HiddenTape parameters) :=
  exactSourceRefinementEvent transitionFuel configuration projection \
    exactPlainRomTargetEvent transitionFuel configuration

theorem mem_exact_plain_rom_legal_same_tape_event_iff
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat)
    (configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters)
    (projection : AcceptedTapeProjection Statement Proof Payload)
    (sample : ExactCompilerSample HiddenTape parameters) :
    sample ∈ exactPlainRomLegalSameTapeEvent transitionFuel configuration
        projection ↔
      sample ∈ exactSourceRefinementEvent transitionFuel configuration
          projection ∧
        sample ∉ exactPlainRomTargetEvent transitionFuel configuration := by
  rfl

/-- Every source-accepted sample is either in the concrete clean event or in
the single causal target event.  The significance of the clean branch is the
operational construction theorem below, not this elementary partition. -/
theorem exact_source_event_subset_legal_union_target
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat)
    (configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters)
    (projection : AcceptedTapeProjection Statement Proof Payload) :
    exactSourceRefinementEvent transitionFuel configuration projection ⊆
      exactPlainRomLegalSameTapeEvent transitionFuel configuration projection ∪
        exactPlainRomTargetEvent transitionFuel configuration := by
  intro sample accepted
  by_cases hit : sample ∈ exactPlainRomTargetEvent transitionFuel configuration
  · exact Or.inr hit
  · exact Or.inl ⟨accepted, hit⟩

/-! ## Constructed root certificate -/

/-- Proof-only data recovered from a clean source sample.  Every runtime,
tape, raw trace, execution and canonical path is an output of the actual root
interpreter and strict checked refinement.  `targetClean` refers to the
literal result-carrying cursor used by `runExactPlainRom`; it is not an
independent cleanliness assumption. -/
structure ExactCleanSourceRootProjection
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat)
    (configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters)
    (projection : AcceptedTapeProjection Statement Proof Payload)
    (sample : ExactCompilerSample HiddenTape parameters) where
  runtime : SchedulerNativePlainRomRootRuntime TapeIdentity Statement Proof
    Payload
  clientRun : ConcreteRestorationClientRun Statement Proof Payload PUnit
  tape : DeployedFixedTape
  raw : InteractiveRawTrace
  rootCompleted :
    (runExactPlainRomRoot transitionFuel configuration sample).terminal =
      .returned (.completed runtime clientRun)
  projectedTape : projection runtime.adversaryValue = some tape
  rawMessagesExact :
    fixedTapeRawMessages tape = runtime.adversaryValue.rawMessages
  environmentExact :
    fixedTapeFutureFreeEnvironment tape = configuration.machine.environment
  strictRefinement :
    checkedRefine (fixedTableOfOracleState runtime.verifierFinalOracle)
      exactDeterministicDecoders tape = some raw
  projected : ExactProjectedRootExecution configuration.machine sample.1
    runtime
  canonical : CanonicalCappedCheckedFutureFreePath
    projected.execution.finalTable tape
  actualPathAlignment : CheckedPathActualRunAlignment projected.execution tape
    canonical.construction.complete
  targetClean : ExactCompilerTargetClean parameters transitionFuel
    (exactPlainRomCursor configuration sample.1) sample.2

/-- The canonical checked path's first-cap-203 certificate lives on the
literal scheduler root after actual-run alignment. -/
def ExactCleanSourceRootProjection.selectedQ16Ledger
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    {transitionFuel : Nat}
    {configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters}
    {projection : AcceptedTapeProjection Statement Proof Payload}
    {sample : ExactCompilerSample HiddenTape parameters}
    (root : ExactCleanSourceRootProjection transitionFuel configuration
      projection sample) :
    SelectedQ16LedgerCertificate configuration.machine.environment
      root.runtime.verifierFinalState.current := by
  have certificate := root.canonical.construction.selectedQ16
  have finalStateExact : root.canonical.construction.complete.final =
      root.runtime.verifierFinalState :=
    root.actualPathAlignment.finalStateExact.symm.trans
      root.projected.finalStateExact
  rw [root.environmentExact, finalStateExact] at certificate
  exact certificate

/-- The literal gamma decoded by the canonical checked tape is retained in
the actual scheduler root after exact final-state alignment. -/
theorem ExactCleanSourceRootProjection.gammaRecordExact
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    {transitionFuel : Nat}
    {configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters}
    {projection : AcceptedTapeProjection Statement Proof Payload}
    {sample : ExactCompilerSample HiddenTape parameters}
    (root : ExactCleanSourceRootProjection transitionFuel configuration
      projection sample) :
    DecodedChallenge.mk .gamma
      (root.tape.messages.challengeValue .gamma) ∈
      root.runtime.verifierFinalState.current.decodedChallenges := by
  have member := root.canonical.construction.gammaRecordExact
  have finalStateExact : root.canonical.construction.complete.final =
      root.runtime.verifierFinalState :=
    root.actualPathAlignment.finalStateExact.symm.trans
      root.projected.finalStateExact
  rw [finalStateExact] at member
  exact member

/-- The same source alignment retains the literal alpha-zero bytes. -/
theorem ExactCleanSourceRootProjection.alphaZeroRecordExact
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    {transitionFuel : Nat}
    {configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters}
    {projection : AcceptedTapeProjection Statement Proof Payload}
    {sample : ExactCompilerSample HiddenTape parameters}
    (root : ExactCleanSourceRootProjection transitionFuel configuration
      projection sample) :
    DecodedChallenge.mk (ChallengeId.alpha 0)
      (root.tape.messages.challengeValue (ChallengeId.alpha 0)) ∈
      root.runtime.verifierFinalState.current.decodedChallenges := by
  have member := root.canonical.construction.alphaZeroRecordExact
  have finalStateExact : root.canonical.construction.complete.final =
      root.runtime.verifierFinalState :=
    root.actualPathAlignment.finalStateExact.symm.trans
      root.projected.finalStateExact
  rw [finalStateExact] at member
  exact member

/-- Membership in the concrete clean-source event proves that an exact
ROM-free root certificate is inhabited.  `Nonempty` is essential here: the
source event is proposition-valued, so Lean may eliminate its existential
witnesses into another proposition without an illicit large elimination. -/
theorem legal_same_tape_event_has_exact_clean_root
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat) (positive : 0 < transitionFuel)
    (configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters)
    (projection : AcceptedTapeProjection Statement Proof Payload)
    (driverCoversProtocol :
      tag73CanonicalDriverFuelCap ≤ configuration.machine.driverFuel)
    (sample : ExactCompilerSample HiddenTape parameters)
    (member : sample ∈ exactPlainRomLegalSameTapeEvent transitionFuel
      configuration projection) :
    Nonempty (ExactCleanSourceRootProjection transitionFuel configuration
      projection sample) := by
  rcases member with ⟨sourceMember, targetMiss⟩
  obtain ⟨runtime, clientRun, tape, raw, rootCompleted, projectedTape,
      rawMessagesExact, environmentExact, strictRefinement, projected,
      canonical, actualPathAlignment⟩ :=
    exact_source_refinement_event_aligns_actual_root transitionFuel positive
      configuration projection driverCoversProtocol sample sourceMember
  refine ⟨
    { runtime := runtime
      clientRun := clientRun
      tape := tape
      raw := raw
      rootCompleted := rootCompleted
      projectedTape := projectedTape
      rawMessagesExact := rawMessagesExact
      environmentExact := environmentExact
      strictRefinement := strictRefinement
      projected := projected
      canonical := canonical
      actualPathAlignment := actualPathAlignment
      targetClean := targetMiss }⟩

/-- Canonical proof-only certificate selected from the inhabited operational
projection.  This uses only Lean's standard `Classical.choice`; every field of
the selected certificate is proved by
`legal_same_tape_event_has_exact_clean_root`. -/
noncomputable def legal_same_tape_event_constructs_exact_clean_root
    {HiddenTape TapeIdentity Observation Statement Proof Payload Result : Type}
    {parameters : ExactCompilerResourceParameters}
    (transitionFuel : Nat) (positive : 0 < transitionFuel)
    (configuration : ExactPlainRomConfiguration HiddenTape TapeIdentity
      Observation Statement Proof Payload Result parameters)
    (projection : AcceptedTapeProjection Statement Proof Payload)
    (driverCoversProtocol :
      tag73CanonicalDriverFuelCap ≤ configuration.machine.driverFuel)
    (sample : ExactCompilerSample HiddenTape parameters)
    (member : sample ∈ exactPlainRomLegalSameTapeEvent transitionFuel
      configuration projection) :
    ExactCleanSourceRootProjection transitionFuel configuration projection
      sample :=
  Classical.choice
    (legal_same_tape_event_has_exact_clean_root transitionFuel positive
      configuration projection driverCoversProtocol sample member)

#print axioms mem_exact_plain_rom_legal_same_tape_event_iff
#print axioms exact_source_event_subset_legal_union_target
#print axioms legal_same_tape_event_has_exact_clean_root
#print axioms legal_same_tape_event_constructs_exact_clean_root
#print axioms ExactCleanSourceRootProjection.selectedQ16Ledger
#print axioms ExactCleanSourceRootProjection.gammaRecordExact
#print axioms ExactCleanSourceRootProjection.alphaZeroRecordExact

end

end AspisK1.V7Tag73ExactLegalSameTapeEvent
