import AspisFormal.K1.V7Tag73SchedulerTraceFactorization
import AspisFormal.K1.V7Tag73CompletedRootProjection

/-!
# Static safety over actual projected scheduler traces

This is the trace-retaining counterpart of
`SchedulerNativeCursorAllProjectedReturned`.  Machine and fork constructors
prepend the exact records generated by the executable scheduler.  Therefore a
client induction can establish properties of the final result together with
its real chronological trace, without accepting a trace decomposition from a
caller.
-/

set_option autoImplicit false

namespace AspisK1.V7Tag73SchedulerProjectedTraceSafety

open AspisK1.V7FsAokExperiment
open AspisK1.V7Tag73TranscriptSchedule
open AspisK1.V7Tag73AdaptiveLazyOracle
open AspisK1.V7Tag73OperationalOracleExposure
open AspisK1.V7Tag73OperationalCausalInjection
open AspisK1.V7Tag73AtomicPairReplay
open AspisK1.V7Tag73AtomicForkUniformScheduler
open AspisK1.V7Tag73SchedulerNativeResult
open AspisK1.V7Tag73ProjectedMachinePrefix
open AspisK1.V7Tag73SchedulerMachineFactorization
open AspisK1.V7Tag73CompletedRootProjection
open AspisK1.V7Tag73SchedulerTraceFactorization

noncomputable section

universe u

def paddingRecords : List Digest256 → List UnifiedExposureRecord :=
  List.map UnifiedExposureRecord.padding

/-- Every successful terminal reachable below `cursor` satisfies `P` on its
literal future trace.  The constructors compose chronology themselves. -/
inductive SchedulerNativeCursorAllProjectedTracedReturned
    {globalOracleCalls : Nat} {Result : Type u} :
    (Result → List UnifiedExposureRecord → Prop) →
      SchedulerNativeCursor globalOracleCalls Result → Prop where
  | returned {P : Result → List UnifiedExposureRecord → Prop}
      (result : Result)
      (holds : ∀ answers, P result (paddingRecords answers)) :
      SchedulerNativeCursorAllProjectedTracedReturned P (.returned result)
  | failed {P : Result → List UnifiedExposureRecord → Prop}
      (reason : SchedulerNativeFailure) :
      SchedulerNativeCursorAllProjectedTracedReturned P (.failed reason)
  | machine {P : Result → List UnifiedExposureRecord → Prop}
      {MachineResult : Type u}
      (limits : OracleLimits)
      (limitBound : limits.totalCalls ≤ globalOracleCalls)
      (actor : QueryActor) (state : OracleState)
      (program : OracleMachine MachineResult) (fuel : Nat)
      (coherent : HistoryTotalCoherent state)
      (onReturned : (result : MachineResult) → (state : OracleState) →
        HistoryTotalCoherent state →
          SchedulerNativeCursor globalOracleCalls Result)
      (safe : ∀ (available : List Digest256)
        (returned : ProjectedMachinePrefixReturned limits actor fuel state
          program available),
        SchedulerNativeCursorAllProjectedTracedReturned
          (fun result tailTrace =>
            P result
              (projectedMachineFreshRecords actor returned.freshQueries ++
                tailTrace))
          (onReturned returned.result returned.finalState
            returned.finalCoherent)) :
      SchedulerNativeCursorAllProjectedTracedReturned P
        (.machine limits limitBound actor state program fuel coherent
          onReturned)
  | forkPair {P : Result → List UnifiedExposureRecord → Prop}
      (frozenHistory : List QueryRecord)
      (pairRoom : frozenHistory.length + 2 ≤ globalOracleCalls)
      (outputInput advanceInput : ShaInput)
      (template : AtomicPairReplayConfiguration)
      (next : AtomicPairReplayConfiguration →
        SchedulerNativeCursor globalOracleCalls Result)
      (safe : ∀ scheduled : ScheduledForkCoins,
        scheduled.frozenHistory = frozenHistory →
        scheduled.outputInput = outputInput →
        scheduled.advanceInput = advanceInput →
        scheduled.template = template →
        SchedulerNativeCursorAllProjectedTracedReturned
          (fun result tailTrace =>
            P result
              ([.forkOutput frozenHistory outputInput advanceInput template
                    scheduled.forkOutput,
                  .forkAdvance scheduled] ++ tailTrace))
          (next scheduled.configuration)) :
      SchedulerNativeCursorAllProjectedTracedReturned P
        (.forkPair frozenHistory pairRoom outputInput advanceInput template next)
  | forkAdvance {P : Result → List UnifiedExposureRecord → Prop}
      (frozenHistory : List QueryRecord)
      (pairRoom : frozenHistory.length + 2 ≤ globalOracleCalls)
      (outputInput advanceInput : ShaInput)
      (template : AtomicPairReplayConfiguration)
      (forkOutput : Digest256)
      (next : AtomicPairReplayConfiguration →
        SchedulerNativeCursor globalOracleCalls Result)
      (safe : ∀ scheduled : ScheduledForkCoins,
        scheduled.frozenHistory = frozenHistory →
        scheduled.outputInput = outputInput →
        scheduled.advanceInput = advanceInput →
        scheduled.template = template →
        scheduled.forkOutput = forkOutput →
        SchedulerNativeCursorAllProjectedTracedReturned
          (fun result tailTrace =>
            P result (.forkAdvance scheduled :: tailTrace))
          (next scheduled.configuration)) :
      SchedulerNativeCursorAllProjectedTracedReturned P
        (.forkAdvance frozenHistory pairRoom outputInput advanceInput template
          forkOutput next)

theorem run_scheduler_native_list_run_returned_exact
    {globalOracleCalls : Nat} {Result : Type u}
    (transitionFuel : Nat) (positive : 0 < transitionFuel)
    (result : Result) : ∀ currentTransitionFuel,
    0 < currentTransitionFuel → ∀ answers,
      runSchedulerNativeListRunFrom transitionFuel currentTransitionFuel
          (.returned result : SchedulerNativeCursor globalOracleCalls Result)
          answers =
        { terminal := .returned result
          trace := paddingRecords answers } := by
  intro currentTransitionFuel currentPositive answers
  induction answers generalizing currentTransitionFuel with
  | nil =>
      cases currentTransitionFuel with
      | zero => omega
      | succ current => rfl
  | cons answer rest ih =>
      cases currentTransitionFuel with
      | zero => omega
      | succ current =>
          simp only [runSchedulerNativeListRunFrom,
            seekSchedulerNativeExposure, paddingRecords, List.map_cons]
          rw [ih transitionFuel positive]
          rfl

/-- A successful terminal cannot start with zero normalization fuel: the
executable scheduler records `transitionLimit` before reading any live node. -/
theorem returned_list_terminal_implies_current_positive
    {globalOracleCalls : Nat} {Result : Type u}
    (transitionFuel : Nat) (positive : 0 < transitionFuel)
    (currentTransitionFuel : Nat)
    (cursor : SchedulerNativeCursor globalOracleCalls Result)
    (answers : List Digest256) (result : Result)
    (completed :
      runSchedulerNativeListTerminalFrom transitionFuel currentTransitionFuel
        cursor answers = .returned result) :
    0 < currentTransitionFuel := by
  cases currentTransitionFuel with
  | succ current => exact Nat.succ_pos _
  | zero =>
      cases answers with
      | nil =>
          simp [runSchedulerNativeListTerminalFrom, terminalAtExposureEnd,
            seekSchedulerNativeExposure] at completed
      | cons answer rest =>
          simp only [runSchedulerNativeListTerminalFrom,
            seekSchedulerNativeExposure] at completed
          rw [run_scheduler_native_list_failed_of_positive transitionFuel
            positive .transitionLimit rest] at completed
          cases completed

/-- A completed trace-retaining list run can return only a result/trace pair
certified by the static projected-trace continuation tree. -/
theorem run_scheduler_native_list_run_respects_projected_traced_returned
    {globalOracleCalls : Nat} {Result : Type u}
    (P : Result → List UnifiedExposureRecord → Prop)
    (transitionFuel : Nat) (positive : 0 < transitionFuel) :
    ∀ (cursor : SchedulerNativeCursor globalOracleCalls Result),
      SchedulerNativeCursorAllProjectedTracedReturned P cursor →
      ∀ currentTransitionFuel, 0 < currentTransitionFuel →
      ∀ answers result,
        (runSchedulerNativeListRunFrom transitionFuel currentTransitionFuel
          cursor answers).terminal = .returned result →
        P result
          (runSchedulerNativeListRunFrom transitionFuel currentTransitionFuel
            cursor answers).trace := by
  intro cursor safe
  induction safe with
  | returned returnedResult holds =>
      intro current currentPositive answers result completed
      rw [run_scheduler_native_list_run_returned_exact transitionFuel positive
        returnedResult current currentPositive answers] at completed ⊢
      simp only [SchedulerNativeRun.terminal, SchedulerNativeRun.trace,
        SchedulerNativeTerminal.returned.injEq] at completed ⊢
      subst result
      exact holds answers
  | failed reason =>
      intro current currentPositive answers result completed
      cases current with
      | zero => omega
      | succ current =>
          cases answers with
          | nil => simp [runSchedulerNativeListRunFrom, terminalAtExposureEnd,
              seekSchedulerNativeExposure] at completed
          | cons answer rest =>
              simp only [runSchedulerNativeListRunFrom,
                seekSchedulerNativeExposure] at completed
              have failed := run_scheduler_native_list_failed_of_positive
                (globalOracleCalls := globalOracleCalls) (Result := Result)
                transitionFuel positive reason rest
              rw [← run_scheduler_native_list_run_terminal] at failed
              rw [failed] at completed
              cases completed
  | @machine _P MachineResult limits limitBound actor state program fuel
      coherent onReturned safe ih =>
      intro current currentPositive answers result completed
      have terminalCompleted :
          runSchedulerNativeListTerminalFrom transitionFuel current
              (.machine limits limitBound actor state program fuel coherent
                onReturned) answers = .returned result := by
        rw [← run_scheduler_native_list_run_terminal]
        exact completed
      rw [run_scheduler_native_list_machine_factorization transitionFuel limits
        limitBound actor state program fuel coherent onReturned positive current
        answers] at terminalCompleted
      obtain ⟨returned, _executed, tailCompleted⟩ :=
        terminal_after_projected_machine_prefix_returned_elim
          transitionFuel positive current limits limitBound actor state program
          fuel coherent onReturned answers result terminalCompleted
      have currentPositive' : 0 < current := currentPositive
      have factor := run_scheduler_native_list_run_from_projected_prefix
        transitionFuel positive current currentPositive' limits limitBound actor
        state program fuel coherent onReturned answers returned
      rw [factor] at completed ⊢
      have nextPositive := returned_list_terminal_implies_current_positive
        transitionFuel positive
        (machinePrefixContinuationTransitionFuel transitionFuel
          (current - 1) returned.freshQueries)
        (onReturned returned.result returned.finalState returned.finalCoherent)
        returned.remaining result tailCompleted
      exact ih answers returned _ nextPositive returned.remaining result (by
        simpa using completed)
  | forkPair frozenHistory pairRoom outputInput advanceInput template next safe
      ih =>
      intro current currentPositive answers result completed
      cases current with
      | zero => omega
      | succ current =>
          cases answers with
          | nil =>
              simp [runSchedulerNativeListRunFrom, terminalAtExposureEnd,
                seekSchedulerNativeExposure] at completed
          | cons forkOutput rest =>
              cases rest with
              | nil =>
                  cases transitionFuel with
                  | zero => omega
                  | succ reset =>
                      simp [runSchedulerNativeListRunFrom,
                        terminalAtExposureEnd, seekSchedulerNativeExposure] at completed
              | cons forkAdvance tail =>
                  cases transitionFuel with
                  | zero => omega
                  | succ reset =>
                      let scheduled : ScheduledForkCoins :=
                        { frozenHistory := frozenHistory
                          outputInput := outputInput
                          advanceInput := advanceInput
                          template := template
                          forkOutput := forkOutput
                          forkAdvance := forkAdvance }
                      simp only [runSchedulerNativeListRunFrom,
                        seekSchedulerNativeExposure] at completed ⊢
                      exact ih scheduled rfl rfl rfl rfl (reset + 1)
                        (Nat.succ_pos _) tail result
                          (by simpa [scheduled] using completed)
  | forkAdvance frozenHistory pairRoom outputInput advanceInput template
      forkOutput next safe ih =>
      intro current currentPositive answers result completed
      cases current with
      | zero => omega
      | succ current =>
          cases answers with
          | nil =>
              simp [runSchedulerNativeListRunFrom, terminalAtExposureEnd,
                seekSchedulerNativeExposure] at completed
          | cons forkAdvance tail =>
              let scheduled : ScheduledForkCoins :=
                { frozenHistory := frozenHistory
                  outputInput := outputInput
                  advanceInput := advanceInput
                  template := template
                  forkOutput := forkOutput
                  forkAdvance := forkAdvance }
              simp only [runSchedulerNativeListRunFrom,
                seekSchedulerNativeExposure] at completed ⊢
              exact ih scheduled rfl rfl rfl rfl rfl transitionFuel positive
                tail result (by simpa [scheduled] using completed)

/-- Fixed dependent-tape form used by the exact probability experiment. -/
theorem run_scheduler_native_respects_projected_traced_returned
    {globalOracleCalls remaining : Nat} {Result : Type u}
    (P : Result → List UnifiedExposureRecord → Prop)
    (transitionFuel : Nat) (positive : 0 < transitionFuel)
    (cursor : SchedulerNativeCursor globalOracleCalls Result)
    (safe : SchedulerNativeCursorAllProjectedTracedReturned P cursor)
    (tape : FreshAnswerTape Digest256 remaining) (result : Result)
    (completed :
      (runSchedulerNative transitionFuel remaining cursor tape).terminal =
        .returned result) :
    P result (runSchedulerNative transitionFuel remaining cursor tape).trace := by
  rw [run_scheduler_native_eq_list_run] at completed ⊢
  exact run_scheduler_native_list_run_respects_projected_traced_returned P
    transitionFuel positive cursor safe transitionFuel positive
      (freshAnswerTapeToList tape) result completed

#print axioms run_scheduler_native_list_run_returned_exact
#print axioms returned_list_terminal_implies_current_positive
#print axioms run_scheduler_native_list_run_respects_projected_traced_returned
#print axioms run_scheduler_native_respects_projected_traced_returned

end

end AspisK1.V7Tag73SchedulerProjectedTraceSafety
