import AspisFormal.V5FiatShamirAdaptiveQueryBudget
import AspisFormal.V5TranscriptConnection

/-!
# Round-by-round FRI soundness and saved-prefix grinding

The existing V5 FRI theorem counts four *suffix-conditioned* bad fibres on
one complete, uniformly sampled four-challenge tuple.  That count is correct,
but it is not yet a round-by-round Fiat--Shamir theorem.  In particular, its
round-zero, round-one, and round-two fibres may use challenges sampled later
in the transcript when choosing the backwards decoder candidate.

A prover which can restore a saved transcript state tries nonces at one
specific checkpoint.  The bad set charged to the next fresh challenge must
therefore be fixed by that checkpoint and the preceding oracle history; it
cannot use the challenge currently being sampled or a later suffix.  This
file makes that timing condition explicit.

There are three independent results below.

* `PrefixConditionedBadSets` is the sufficient forward interface.  Its four
  sets depend only on the transcript prefix available before that round.
* `ReleasedPrefixRestorationPlan` permits arbitrary adaptive restoration to
  saved prefixes and gives the exact raw `queries * cap / |K|` bound at each
  round in an ideal fresh-oracle experiment.
* `suffix_round0_cap_does_not_imply_prefix_round0_cap` is a finite
  counterexample: a suffix-conditioned round-zero fibre of size one need not
  be coverable by any size-one set fixed before the first challenge.

The final section separately models the fold work predicate.  Conditional on
having a valid submitted nonce, the raw challenge bound is `cap / |K|`.
Under the additional idealization that the work digest and challenge are
independent fresh values, one arbitrary nonce trial hits both work and the bad
challenge with probability `cap / (2^difficulty * |K|)`.  These are different
experiments and are never identified here.

No claim in this file connects SHA-256, the Rust transcript, nonce reuse,
rejection sampling, or the deployed verifier to either ideal experiment.
-/

namespace AspisV5FriRoundByRoundSoundness

open AspisV5FriAdaptiveUnmatched
open AspisV5ComponentCConcreteFoldLinearity
open AspisV5FriConcreteEncoderCommutation
open AspisV5FriFixedFamilyExperiment
open AspisV5FriPublishedOutputEncoderDecoding
open AspisV5FriReleasedAdaptiveExtraction
open AspisV5FriReleasedLineGeometry
open AspisV5FiatShamirAdaptiveQueryBudget
open AspisV5NonceWorkAuthentication
open AspisV5TranscriptConnection

variable {K : Type*} [Fintype K] [DecidableEq K]

/-! ## Bad sets fixed at the four forward transcript checkpoints -/

/-- Four bad-challenge sets with the timing required by a sequential
Fiat--Shamir proof.

The round-zero set is fixed before any fold challenge.  The round-one set may
use only `z0`; round two may use only `(z0,z1)`; and round three may use only
`(z0,z1,z2)`. -/
structure PrefixConditionedBadSets
    (K : Type*) [Fintype K] [DecidableEq K]
    (cap : Fin 4 -> Nat) where
  round0 : Finset K
  round1 : K -> Finset K
  round2 : K -> K -> Finset K
  round3 : K -> K -> K -> Finset K
  round0_card_le : round0.card <= cap 0
  round1_card_le : forall z0, (round1 z0).card <= cap 1
  round2_card_le : forall z0 z1, (round2 z0 z1).card <= cap 2
  round3_card_le : forall z0 z1 z2, (round3 z0 z1 z2).card <= cap 3

/-- A complete challenge path crosses one of the bad sets that was already
fixed at the corresponding forward checkpoint. -/
def PrefixConditionedBadSets.Occurs
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap)
    (z0 z1 z2 z3 : K) : Prop :=
  z0 ∈ bad.round0 \/
  z1 ∈ bad.round1 z0 \/
  z2 ∈ bad.round2 z0 z1 \/
  z3 ∈ bad.round3 z0 z1 z2

/-- Forget the forward timing and view prefix-conditioned sets as the more
general suffix-conditioned interface. -/
noncomputable def PrefixConditionedBadSets.toSuffixConditioned
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap) :
    SuffixConditionedBadSets K cap where
  round0 _z1 _z2 _z3 := bad.round0
  round1 z0 _z2 _z3 := bad.round1 z0
  round2 z0 z1 _z3 := bad.round2 z0 z1
  round3 z0 z1 z2 := bad.round3 z0 z1 z2
  round0_card_le := by
    intro _z1 _z2 _z3
    exact bad.round0_card_le
  round1_card_le := by
    intro z0 _z2 _z3
    exact bad.round1_card_le z0
  round2_card_le := by
    intro z0 z1 _z3
    exact bad.round2_card_le z0 z1
  round3_card_le := bad.round3_card_le

@[simp] theorem PrefixConditionedBadSets.toSuffixConditioned_occurs_iff
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap)
    (z0 z1 z2 z3 : K) :
    bad.toSuffixConditioned.Occurs z0 z1 z2 z3 <->
      bad.Occurs z0 z1 z2 z3 := by
  rfl

/-- The complete finite event generated by the four forward checkpoints. -/
noncomputable def prefixBadChallengeTuples
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap) :
    Finset (FourChallenges K) :=
  allBadChallengeTuples bad.toSuffixConditioned

@[simp] theorem mem_prefixBadChallengeTuples_iff
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap)
    (z0 z1 z2 z3 : K) :
    (((z0, z1), z2), z3) ∈ prefixBadChallengeTuples bad <->
      bad.Occurs z0 z1 z2 z3 := by
  simp [prefixBadChallengeTuples]

/-- Prefix timing is stronger than the old suffix timing, so the existing
four-fibre count applies immediately once the forward sets have been built. -/
theorem prefixBadChallengeTuples_card_le
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap) :
    (prefixBadChallengeTuples bad).card <=
      Fintype.card K ^ 3 * (cap 0 + cap 1 + cap 2 + cap 3) := by
  exact allBadChallengeTuples_card_le bad.toSuffixConditioned

/-- Exact one-path probability under four independent uniform challenges. -/
noncomputable def prefixUniformBadProbability
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap) : Rat :=
  (prefixBadChallengeTuples bad).card / Fintype.card K ^ 4

theorem prefixUniformBadProbability_le
    [Nonempty K]
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap) :
    prefixUniformBadProbability bad <=
      (cap 0 + cap 1 + cap 2 + cap 3 : Rat) / Fintype.card K := by
  change uniformBadChallengeProbability bad.toSuffixConditioned <=
    (cap 0 + cap 1 + cap 2 + cap 3 : Rat) / Fintype.card K
  exact uniformBadChallengeProbability_le bad.toSuffixConditioned

/-! ## The exact extra premise required by the released backwards count -/

section ReleasedForwardBridge

variable [Field K] [Algebra (ZMod AspisCircleGroupOrder.P) K] [NeZero (2 : K)]

/-- The missing mathematical timing interface for using the existing
backwards-decoder event in a round-by-round Fiat--Shamir proof.

It supplies forward, prefix-conditioned bad sets with the same released caps
and proves that every tuple charged by the suffix-conditioned backwards
argument crosses one of those forward sets.  The existing global counting
theorem does not construct this structure. -/
structure ReleasedPrefixDoomDecomposition
    (base : FixedSchedule (ZMod AspisCircleGroupOrder.P) K)
    (family : CausalTranscriptFamily K)
    (hfinal : FinalXMatchesReleasedDomain base)
    (htables : InverseTablesMatch base releasedEvaluationPoints)
    (hpublished : PublishedOrdinaryPolynomialCurveDecoding (K := K)) where
  bad : PrefixConditionedBadSets K releasedChallengeCap
  suffixEvent_is_caught_at_forward_checkpoint :
    fixedFamilyBadChallengeTuples base family hfinal htables hpublished ⊆
      prefixBadChallengeTuples bad

/-- Once the missing decomposition is supplied, every counted backwards-FRI
failure has a witness at a bad set fixed before that round's challenge. -/
theorem fixedFamilyBad_has_forward_checkpoint
    (base : FixedSchedule (ZMod AspisCircleGroupOrder.P) K)
    (family : CausalTranscriptFamily K)
    (hfinal : FinalXMatchesReleasedDomain base)
    (htables : InverseTablesMatch base releasedEvaluationPoints)
    (hpublished : PublishedOrdinaryPolynomialCurveDecoding (K := K))
    (bridge : ReleasedPrefixDoomDecomposition base family hfinal htables hpublished)
    (z0 z1 z2 z3 : K)
    (hbad : FixedFamilyBadChallengeOccurs base family hfinal htables hpublished
      z0 z1 z2 z3) :
    bridge.bad.Occurs z0 z1 z2 z3 := by
  have hmem : (((z0, z1), z2), z3) ∈
      fixedFamilyBadChallengeTuples base family hfinal htables hpublished :=
    (mem_fixedFamilyBadChallengeTuples_iff base family hfinal htables
      hpublished z0 z1 z2 z3).2 hbad
  exact (mem_prefixBadChallengeTuples_iff bridge.bad z0 z1 z2 z3).1
    (bridge.suffixEvent_is_caught_at_forward_checkpoint hmem)

end ReleasedForwardBridge

/-! ## Saved-prefix restoration in the ideal fresh-challenge experiment -/

/-- A transcript checkpoint immediately before one of the four fold
challenges.  Its constructor stores exactly the challenges already sampled at
that point. -/
inductive PrefixCheckpoint (K : Type*) where
  | beforeRound0
  | beforeRound1 (z0 : K)
  | beforeRound2 (z0 z1 : K)
  | beforeRound3 (z0 z1 z2 : K)

def PrefixCheckpoint.round : PrefixCheckpoint K -> Fin 4
  | .beforeRound0 => 0
  | .beforeRound1 _ => 1
  | .beforeRound2 _ _ => 2
  | .beforeRound3 _ _ _ => 3

def PrefixConditionedBadSets.atCheckpoint
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap) :
    PrefixCheckpoint K -> Finset K
  | .beforeRound0 => bad.round0
  | .beforeRound1 z0 => bad.round1 z0
  | .beforeRound2 z0 z1 => bad.round2 z0 z1
  | .beforeRound3 z0 z1 z2 => bad.round3 z0 z1 z2

theorem PrefixConditionedBadSets.atCheckpoint_card_le
    {cap : Fin 4 -> Nat} (bad : PrefixConditionedBadSets K cap)
    (checkpoint : PrefixCheckpoint K) :
    (bad.atCheckpoint checkpoint).card <= cap checkpoint.round := by
  cases checkpoint with
  | beforeRound0 => exact bad.round0_card_le
  | beforeRound1 z0 => exact bad.round1_card_le z0
  | beforeRound2 z0 z1 => exact bad.round2_card_le z0 z1
  | beforeRound3 z0 z1 z2 => exact bad.round3_card_le z0 z1 z2

/-- An ideal state-restoration adversary at one fixed FRI round.  Before each
fresh oracle answer it may choose any saved checkpoint of that round as an
arbitrary function of all earlier answers.  The current fresh answer is not
available to `checkpointAt`. -/
structure ReleasedPrefixRestorationPlan
    (bad : PrefixConditionedBadSets K releasedChallengeCap)
    (round : Fin 4) where
  checkpointAt : List K -> PrefixCheckpoint K
  checkpoint_round : forall history, (checkpointAt history).round = round

noncomputable def ReleasedPrefixRestorationPlan.toFreshOraclePlan
    {bad : PrefixConditionedBadSets K releasedChallengeCap} {round : Fin 4}
    (plan : ReleasedPrefixRestorationPlan bad round) :
    AdaptiveFreshOraclePlan K where
  badAt history := bad.atCheckpoint (plan.checkpointAt history)

/-- Raw failure probability for one challenge sampled after valid work.  This
quantity contains no work divisor. -/
noncomputable def releasedRoundRawChallengeBound (round : Fin 4) : Rat :=
  (releasedChallengeCap round : Rat) / Fintype.card K

theorem releasedRoundRawChallengeBound_nonnegative (round : Fin 4) :
    (0 : Rat) <= releasedRoundRawChallengeBound (K := K) round := by
  unfold releasedRoundRawChallengeBound
  positivity

theorem restorationPlan_everyFreshBadSetBounded
    [Nonempty K]
    {bad : PrefixConditionedBadSets K releasedChallengeCap} {round : Fin 4}
    (plan : ReleasedPrefixRestorationPlan bad round) :
    EveryFreshBadSetBounded plan.toFreshOraclePlan
      (releasedRoundRawChallengeBound (K := K) round) := by
  intro history
  unfold ReleasedPrefixRestorationPlan.toFreshOraclePlan
  unfold releasedRoundRawChallengeBound
  apply div_le_div_of_nonneg_right
  · exact_mod_cast (bad.atCheckpoint_card_le (plan.checkpointAt history)).trans_eq
      (congrArg releasedChallengeCap (plan.checkpoint_round history))
  · positivity

/-- **Ideal saved-prefix query bound for one released round.**  Arbitrary
restoration and adaptive choice among saved checkpoints are covered.  Each
fresh challenge query costs its raw `cap / |K|`; proof-of-work has not been
used in this theorem. -/
theorem restorationFailureProbability_le_freshQueries_mul_raw
    [Nonempty K]
    {bad : PrefixConditionedBadSets K releasedChallengeCap} {round : Fin 4}
    (plan : ReleasedPrefixRestorationPlan bad round)
    (freshChallenges : Nat) :
    adaptiveFailureProbabilityFromStart plan.toFreshOraclePlan freshChallenges <=
      (freshChallenges : Rat) *
        releasedRoundRawChallengeBound (K := K) round := by
  exact adaptiveFailureProbabilityFromStart_le_attempts_mul _ _
    (releasedRoundRawChallengeBound_nonnegative round)
    (restorationPlan_everyFreshBadSetBounded plan) freshChallenges

/-! ## Work-qualified nonce trials are a separate experiment -/

/-- The released fold-work difficulty at the same four transcript
checkpoints. -/
def releasedFoldWorkBits (round : Fin 4) : Nat :=
  WorkKind.difficulty (.fold round)

theorem releasedFoldWorkBits_exact :
    releasedFoldWorkBits 0 = 34 /\
      releasedFoldWorkBits 1 = 33 /\
      releasedFoldWorkBits 2 = 30 /\
      releasedFoldWorkBits 3 = 25 := by
  decide

/-- Ideal output of one arbitrary nonce trial: the first coordinate is the
`difficulty`-bit work tag and the second is the fold challenge.  This product
model itself is a cryptographic assumption about distinct random-oracle
calls; it is not asserted about SHA-256 here. -/
abbrev WorkChallengeAnswer (K : Type*) (round : Fin 4) :=
  Fin (2 ^ releasedFoldWorkBits round) × K

/-- A nonce trial succeeds only when the work tag is zero and the challenge
falls in the checkpoint's already-fixed bad set. -/
noncomputable def workQualifiedBadAnswers
    (round : Fin 4) (bad : Finset K) :
    Finset (WorkChallengeAnswer K round) :=
  ({0} : Finset (Fin (2 ^ releasedFoldWorkBits round))) ×ˢ bad

@[simp] theorem workQualifiedBadAnswers_card
    (round : Fin 4) (bad : Finset K) :
    (workQualifiedBadAnswers round bad).card = bad.card := by
  simp [workQualifiedBadAnswers]

@[simp] theorem mem_workQualifiedBadAnswers_iff
    (round : Fin 4) (bad : Finset K)
    (answer : WorkChallengeAnswer K round) :
    answer ∈ workQualifiedBadAnswers round bad <->
      answer.1 = 0 /\ answer.2 ∈ bad := by
  rcases answer with ⟨workTag, challenge⟩
  simp [workQualifiedBadAnswers, eq_comm, and_comm]

/-- An ideal adaptive nonce-search plan at one round.  It may restore any
saved prefix of that round after every previous nonce result. -/
structure ReleasedPrefixNonceTrialPlan
    (bad : PrefixConditionedBadSets K releasedChallengeCap)
    (round : Fin 4) where
  checkpointAt : List (WorkChallengeAnswer K round) -> PrefixCheckpoint K
  checkpoint_round : forall history, (checkpointAt history).round = round

noncomputable def ReleasedPrefixNonceTrialPlan.toFreshOraclePlan
    {bad : PrefixConditionedBadSets K releasedChallengeCap} {round : Fin 4}
    (plan : ReleasedPrefixNonceTrialPlan bad round) :
    AdaptiveFreshOraclePlan (WorkChallengeAnswer K round) where
  badAt history := workQualifiedBadAnswers round
    (bad.atCheckpoint (plan.checkpointAt history))

/-- Per arbitrary nonce trial, not per valid submitted proof. -/
noncomputable def releasedRoundPerNonceTrialBound (round : Fin 4) : Rat :=
  (releasedChallengeCap round : Rat) /
    ((2 ^ releasedFoldWorkBits round : Nat) * Fintype.card K)

theorem releasedRoundPerNonceTrialBound_nonnegative (round : Fin 4) :
    (0 : Rat) <= releasedRoundPerNonceTrialBound (K := K) round := by
  unfold releasedRoundPerNonceTrialBound
  positivity

theorem nonceTrialPlan_everyFreshBadSetBounded
    [Nonempty K]
    {bad : PrefixConditionedBadSets K releasedChallengeCap} {round : Fin 4}
    (plan : ReleasedPrefixNonceTrialPlan bad round) :
    EveryFreshBadSetBounded plan.toFreshOraclePlan
      (releasedRoundPerNonceTrialBound (K := K) round) := by
  intro history
  change
    ((workQualifiedBadAnswers round
      (bad.atCheckpoint (plan.checkpointAt history))).card : Rat) /
        Fintype.card (WorkChallengeAnswer K round) <=
      releasedRoundPerNonceTrialBound (K := K) round
  rw [workQualifiedBadAnswers_card]
  rw [show Fintype.card (WorkChallengeAnswer K round) =
      (2 ^ releasedFoldWorkBits round : Nat) * Fintype.card K by
    simp [WorkChallengeAnswer]]
  unfold releasedRoundPerNonceTrialBound
  push_cast
  apply div_le_div_of_nonneg_right
  · exact_mod_cast (bad.atCheckpoint_card_le (plan.checkpointAt history)).trans_eq
      (congrArg releasedChallengeCap (plan.checkpoint_round history))
  · positivity

/-- **Ideal work-qualified hash-query bound.**  This is where the numerical
`2^-difficulty` factor belongs: success per arbitrary nonce trial, under the
explicit product-oracle idealization above.  It is not the raw probability
conditioned on submitting a valid proof. -/
theorem nonceTrialFailureProbability_le_hashQueries_mul
    [Nonempty K]
    {bad : PrefixConditionedBadSets K releasedChallengeCap} {round : Fin 4}
    (plan : ReleasedPrefixNonceTrialPlan bad round)
    (nonceTrials : Nat) :
    adaptiveFailureProbabilityFromStart plan.toFreshOraclePlan nonceTrials <=
      (nonceTrials : Rat) *
        releasedRoundPerNonceTrialBound (K := K) round := by
  exact adaptiveFailureProbabilityFromStart_le_attempts_mul _ _
    (releasedRoundPerNonceTrialBound_nonnegative round)
    (nonceTrialPlan_everyFreshBadSetBounded plan) nonceTrials

/-! ## Exact production order of each fold checkpoint -/

/-- The source-shaped schedule checks fold work, absorbs that nonce, samples
the fold challenge, and only then absorbs the next layer root. -/
theorem exact_fold_checkpoint_order (round : Fin 4) :
    relationRoundSchedule round =
      oodSampleSchedule round 0 ++
      oodSampleSchedule round 1 ++
      [.absorb (.relationSumcheck round),
        .verifyWork (.fold round),
        .absorb (.foldNonce round),
        .squeeze (.foldChallenge round)] ++
      (laterLayer round).toList.map (fun layer => .absorb (.circleRoot layer)) := by
  rfl

/-! ## A finite non-implication counterexample -/

/-- Only round zero has a nonzero cap in the counterexample. -/
def equalityExampleCap (round : Fin 4) : Nat :=
  if round = 0 then 1 else 0

/-- A legal suffix-conditioned family whose round-zero bad set is the
singleton containing the later challenge `z1`. -/
noncomputable def suffixEqualityExample :
    SuffixConditionedBadSets Bool equalityExampleCap where
  round0 z1 _z2 _z3 := {z1}
  round1 _z0 _z2 _z3 := ∅
  round2 _z0 _z1 _z3 := ∅
  round3 _z0 _z1 _z2 := ∅
  round0_card_le := by
    intro z1 z2 z3
    simp [equalityExampleCap]
  round1_card_le := by
    intro z0 z2 z3
    simp [equalityExampleCap]
  round2_card_le := by
    intro z0 z1 z3
    simp [equalityExampleCap]
  round3_card_le := by
    intro z0 z1 z2
    simp [equalityExampleCap]

@[simp] theorem suffixEqualityExample_occurs_iff
    (z0 z1 z2 z3 : Bool) :
    suffixEqualityExample.Occurs z0 z1 z2 z3 <-> z0 = z1 := by
  simp [suffixEqualityExample, SuffixConditionedBadSets.Occurs]

/-- The suffix-conditioned round-zero cap does **not** imply a round-zero bad
set fixed before `z0` is sampled.  Covering every possible later suffix needs
both Boolean values, exceeding the legal size-one cap.

This is the exact logical obstruction in the current V5 argument: its early
fibres may select a backwards candidate using later challenges. -/
theorem suffix_round0_cap_does_not_imply_prefix_round0_cap :
    ¬ ∃ prefixBad : Finset Bool,
      prefixBad.card <= equalityExampleCap 0 /\
      ∀ z0 z1 z2 z3,
        z0 ∈ suffixEqualityExample.round0 z1 z2 z3 -> z0 ∈ prefixBad := by
  rintro ⟨prefixBad, hcard, hcover⟩
  have hfalse : false ∈ prefixBad :=
    hcover false false false false (by simp [suffixEqualityExample])
  have htrue : true ∈ prefixBad :=
    hcover true true false false (by simp [suffixEqualityExample])
  have huniv : prefixBad = Finset.univ := by
    ext value
    cases value <;> simp [hfalse, htrue]
  rw [huniv] at hcard
  norm_num [equalityExampleCap] at hcard

/-- Stronger global form of the counterexample.  Even though every suffix
fibre satisfies its stated cap, there is no complete prefix-conditioned
family with the same four caps which covers the suffix event.  Thus a
round-by-round decomposition is a real additional theorem, not a change of
notation around `SuffixConditionedBadSets`. -/
theorem suffix_caps_do_not_imply_forward_decomposition :
    ¬ ∃ forward : PrefixConditionedBadSets Bool equalityExampleCap,
      ∀ z0 z1 z2 z3,
        suffixEqualityExample.Occurs z0 z1 z2 z3 ->
          forward.Occurs z0 z1 z2 z3 := by
  intro hexists
  apply suffix_round0_cap_does_not_imply_prefix_round0_cap
  rcases hexists with ⟨forward, hcover⟩
  refine ⟨forward.round0, forward.round0_card_le, ?_⟩
  intro z0 z1 z2 z3 hround0
  have hcovered := hcover z0 z1 z2 z3 (Or.inl hround0)
  rcases hcovered with h0 | h1 | h2 | h3
  · exact h0
  · have hcard1 : (forward.round1 z0).card = 0 := by
      apply Nat.eq_zero_of_le_zero
      simpa [equalityExampleCap] using forward.round1_card_le z0
    have hempty1 : forward.round1 z0 = ∅ := Finset.card_eq_zero.mp hcard1
    simp [hempty1] at h1
  · have hcard2 : (forward.round2 z0 z1).card = 0 := by
      apply Nat.eq_zero_of_le_zero
      simpa [equalityExampleCap] using forward.round2_card_le z0 z1
    have hempty2 : forward.round2 z0 z1 = ∅ := Finset.card_eq_zero.mp hcard2
    simp [hempty2] at h2
  · have hcard3 : (forward.round3 z0 z1 z2).card = 0 := by
      apply Nat.eq_zero_of_le_zero
      simpa [equalityExampleCap] using forward.round3_card_le z0 z1 z2
    have hempty3 : forward.round3 z0 z1 z2 = ∅ := Finset.card_eq_zero.mp hcard3
    simp [hempty3] at h3

/-! ## Audit -/

#print axioms prefixBadChallengeTuples_card_le
#print axioms prefixUniformBadProbability_le
#print axioms fixedFamilyBad_has_forward_checkpoint
#print axioms restorationFailureProbability_le_freshQueries_mul_raw
#print axioms nonceTrialFailureProbability_le_hashQueries_mul
#print axioms exact_fold_checkpoint_order
#print axioms suffix_round0_cap_does_not_imply_prefix_round0_cap
#print axioms suffix_caps_do_not_imply_forward_decomposition

end AspisV5FriRoundByRoundSoundness
