import AspisFormal.V5Tag67RelationListInclusion

/-!
# Honest decomposition of a false Tag-67 acceptance

`V5Tag67RelationListInclusion` proves the custom relation step: if one fixed
candidate is false, its four relation checks accept, and its folded final
coefficients match the published final polynomial, then the twelve relation
challenges lie in that candidate's counted repair event.

This file places that result inside the larger argument without pretending
that the still-missing implications have already been proved.  For one fixed
family of candidates, a false accepted execution has exactly three possible
outcomes:

* falsity has not yet been shown to make every possible relation candidate
  false;
* raw acceptance has not yet been connected to the shared relation checks,
  or accepted FRI/Merkle data has not yet been shown to extract a matching
  candidate; or
* a matching false candidate exists, in which case the proved relation
  theorem puts the challenges in the bounded repair event.

The first two outcomes are defined directly as failures of those explicit
implications.  They do not mention the repair event, so the decomposition is
not a renamed assumption of its conclusion.

The final theorem keeps the probabilities of the first two outcomes visible.
Only the third term is bounded here, by `32 * 240 / |K|`.  Thus this file does
not claim an end-to-end Tag-67 soundness bound.
-/

namespace AspisV5Tag67FalseAcceptanceDecomposition

open AspisV5FriRelationCandidateBridge
open AspisV5RelationSumcheckSoundness
open AspisV5Tag67RelationListInclusion

variable {K : Type*} [Field K]

/-! ## One transcript and a fixed coherent candidate family -/

/-- A fixed candidate family for one Tag-67 relation transcript.

Only `initialValues` varies with the candidate.  The verifier's initial
weights and claim, every round message, and the published final polynomial
are shared.  All later candidate layers are generated by the exact folds in
`AcceptedCandidateExecution`; they cannot be selected independently in later
rounds. -/
structure CoherentCandidateFamily (K Candidate : Type*) where
  initialValues : Candidate → Fin 1024 → K
  initialWeights : Fin 1024 → K
  initialClaim : K
  round0 : RelationRoundMessages K Unit 256
  round1 : RelationRoundMessages K (RelationRoundChallenges K) 64
  round2 : RelationRoundMessages K
    (RelationRoundChallenges K × RelationRoundChallenges K) 16
  round3 : RelationRoundMessages K
    ((RelationRoundChallenges K × RelationRoundChallenges K) ×
      RelationRoundChallenges K) 4
  publishedFinal : TwelveRelationChallenges K → Fin 4 → K

/-- View one member of a coherent family as the concrete execution expected
by the relation-inclusion theorem. -/
def CoherentCandidateFamily.execution
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (candidate : Candidate) : AcceptedCandidateExecution K where
  initialValues := family.initialValues candidate
  initialWeights := family.initialWeights
  initialClaim := family.initialClaim
  round0 := family.round0
  round1 := family.round1
  round2 := family.round2
  round3 := family.round3
  publishedFinal := family.publishedFinal

/-! ## The three implications that still need proof from the full protocol -/

/-- A raw execution is accepted and the asserted public statement is false.

The two predicates are deliberately parameters.  Connecting the deployed
Tag-67 callback to `accepts`, and defining/proving the full spend semantics in
`semanticallyFalse`, are separate implementation and cryptographic tasks. -/
def AcceptedFalseExecution
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (challenges : TwelveRelationChallenges K) : Prop :=
  accepts challenges ∧ semanticallyFalse challenges

/-- Every member of the fixed family disagrees with an initial or OOD claim.

The universal quantifier is essential.  FRI is free to return any matching
candidate in its list, so the earlier semantic argument must make that
candidate false without knowing in advance which member FRI will select. -/
def AllCandidatesFalse
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (challenges : TwelveRelationChallenges K) : Prop :=
  ∀ candidate,
    (family.execution candidate).FalseForCandidate challenges

/-- Raw Tag-67 relation acceptance must imply these checks for the shared
transcript.  This is kept separate from both semantic falsity and FRI list
extraction. -/
def AllCandidateRelationChecksAccept
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (challenges : TwelveRelationChallenges K) : Prop :=
  ∀ candidate,
    (family.execution candidate).RelationAccepts challenges

/-- Accepted FRI/Merkle data must provide at least one fixed family member
whose folds reach the final polynomial published by the transcript.

This statement intentionally says nothing about whether that candidate is
false.  Falsity is supplied independently by `AllCandidatesFalse`. -/
def HasMatchingCandidate
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (challenges : TwelveRelationChallenges K) : Prop :=
  ∃ candidate, (family.execution candidate).FinalMatches challenges

/-- The callback-to-relation-check implication expected from the complete
implementation proof. -/
def RawRelationAcceptanceImplication
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts : TwelveRelationChallenges K → Prop) : Prop :=
  ∀ challenges, accepts challenges →
    AllCandidateRelationChecksAccept family challenges

/-- The earlier semantic implication expected from the complete proof.  It is
named here so that its exact missing conclusion is inspectable. -/
def EarlierSemanticImplication
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop) : Prop :=
  ∀ challenges,
    AcceptedFalseExecution accepts semanticallyFalse challenges →
      AllCandidatesFalse family challenges

/-- The FRI extraction-and-match implication expected from the complete
proof.  It produces a matching candidate only; it does not assume that the
same candidate is false. -/
def FriExtractionAndMatchImplication
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop) : Prop :=
  ∀ challenges,
    AcceptedFalseExecution accepts semanticallyFalse challenges →
      HasMatchingCandidate family challenges

/-- A concrete counterexample to the earlier semantic implication. -/
def EarlierSemanticFailure
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (challenges : TwelveRelationChallenges K) : Prop :=
  AcceptedFalseExecution accepts semanticallyFalse challenges ∧
    ¬ AllCandidatesFalse family challenges

/-- A concrete counterexample to the raw-acceptance-to-relation-check
implication. -/
def RawRelationAcceptanceFailure
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (challenges : TwelveRelationChallenges K) : Prop :=
  AcceptedFalseExecution accepts semanticallyFalse challenges ∧
    ¬ AllCandidateRelationChecksAccept family challenges

/-- A concrete counterexample to FRI candidate extraction and final matching. -/
def FriCandidateMatchFailure
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (challenges : TwelveRelationChallenges K) : Prop :=
  AcceptedFalseExecution accepts semanticallyFalse challenges ∧
    ¬ HasMatchingCandidate family challenges

/-- The combined middle failure used by the three-way decomposition.

Its two alternatives remain visible: either raw acceptance was not connected
to the shared relation checks, or accepted FRI/Merkle data did not produce a
candidate matching the final polynomial.  `AllCandidatesFalse` is already
available in this branch, so neither alternative assumes that FRI selects a
particular false candidate. -/
def FriExtractionOrMatchFailure
    {Candidate : Type*} (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (challenges : TwelveRelationChallenges K) : Prop :=
  AcceptedFalseExecution accepts semanticallyFalse challenges ∧
  AllCandidatesFalse family challenges ∧
    (¬ AllCandidateRelationChecksAccept family challenges ∨
      ¬ HasMatchingCandidate family challenges)

/-! ## Deterministic decomposition -/

section FiniteField

variable [Fintype K] [DecidableEq K]

/-- Every accepted false execution is either a counterexample to one of the
two still-missing implications or is covered by the proved relation event.

The proof invokes `accepted_false_mem_repairEvent` only after an actual
candidate with all three required properties has been obtained. -/
theorem accepted_false_execution_decomposition
    {Candidate : Type*} [Fintype Candidate] [DecidableEq Candidate]
    (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (challenges : TwelveRelationChallenges K)
    (hfour : (4 : K) ≠ 0)
    (hacceptedFalse :
      AcceptedFalseExecution accepts semanticallyFalse challenges) :
    EarlierSemanticFailure family accepts semanticallyFalse challenges ∨
    FriExtractionOrMatchFailure family accepts semanticallyFalse challenges ∨
      challenges ∈ boundedCandidateRepairEvent
        (fun candidate => (family.execution candidate).adaptiveData) := by
  classical
  by_cases hallFalse : AllCandidatesFalse family challenges
  · by_cases hallAccepts : AllCandidateRelationChecksAccept family challenges
    · by_cases hmatching : HasMatchingCandidate family challenges
      · right
        right
        rcases hmatching with ⟨candidate, hfinal⟩
        have haccepts := hallAccepts candidate
        have hcandidateFalse := hallFalse candidate
        have hrepair :=
          (family.execution candidate).accepted_false_mem_repairEvent
            challenges hfour haccepts hfinal hcandidateFalse
        unfold boundedCandidateRepairEvent
        rw [Finset.mem_biUnion]
        exact ⟨candidate, Finset.mem_univ candidate, hrepair⟩
      · exact Or.inr (Or.inl
          ⟨hacceptedFalse, hallFalse, Or.inr hmatching⟩)
    · exact Or.inr (Or.inl
        ⟨hacceptedFalse, hallFalse, Or.inl hallAccepts⟩)
  · exact Or.inl ⟨hacceptedFalse, hallFalse⟩

/-! ## Finite events and the cap-240 endpoint -/

/-- Finite event selected by a predicate on the twelve ideal relation
challenges. -/
noncomputable def predicateEvent
    (predicate : TwelveRelationChallenges K → Prop) :
    Finset (TwelveRelationChallenges K) := by
  classical
  exact Finset.univ.filter predicate

/-- Exact uniform mass of a predicate on the twelve ideal relation
challenges. -/
noncomputable def uniformPredicateProbability
    (predicate : TwelveRelationChallenges K → Prop) : ℚ :=
  (predicateEvent predicate).card /
    Fintype.card (TwelveRelationChallenges K)

/-- Finite-event form of the deterministic decomposition.  It is written as
pointwise membership so no choice of a decidable equality is hidden in the
statement. -/
theorem acceptedFalseEvent_subset_explicitFailures_union_repair
    {Candidate : Type*} [Fintype Candidate] [DecidableEq Candidate]
    (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (hfour : (4 : K) ≠ 0) :
    ∀ {challenges},
      challenges ∈ predicateEvent
          (AcceptedFalseExecution accepts semanticallyFalse) →
        challenges ∈ predicateEvent
            (EarlierSemanticFailure family accepts semanticallyFalse) ∨
        challenges ∈ predicateEvent
            (FriExtractionOrMatchFailure family accepts semanticallyFalse) ∨
        challenges ∈ boundedCandidateRepairEvent
          (fun candidate => (family.execution candidate).adaptiveData) := by
  classical
  intro challenges hmem
  have hacceptedFalse :
      AcceptedFalseExecution accepts semanticallyFalse challenges := by
    simpa [predicateEvent] using hmem
  rcases accepted_false_execution_decomposition family accepts
      semanticallyFalse challenges hfour hacceptedFalse with
    heariler | hfri | hrepair
  · exact Or.inl (by simpa [predicateEvent] using heariler)
  · exact Or.inr (Or.inl (by simpa [predicateEvent] using hfri))
  · exact Or.inr (Or.inr hrepair)

/-- Uniform probability form before either missing failure probability has
been bounded. -/
theorem uniform_accepted_false_probability_le_explicit_failures_plus_repair
    {Candidate : Type*} [Fintype Candidate] [DecidableEq Candidate]
    (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (hfour : (4 : K) ≠ 0) :
    uniformPredicateProbability
        (AcceptedFalseExecution accepts semanticallyFalse) ≤
      uniformPredicateProbability
          (EarlierSemanticFailure family accepts semanticallyFalse) +
      uniformPredicateProbability
          (FriExtractionOrMatchFailure family accepts semanticallyFalse) +
      uniformBoundedCandidateRepairProbability
        (fun candidate => (family.execution candidate).adaptiveData) := by
  classical
  let acceptedEvent :=
    predicateEvent (AcceptedFalseExecution accepts semanticallyFalse)
  let earlierEvent := predicateEvent
    (EarlierSemanticFailure family accepts semanticallyFalse)
  let friEvent := predicateEvent
    (FriExtractionOrMatchFailure family accepts semanticallyFalse)
  let repairEvent := boundedCandidateRepairEvent
    (fun candidate => (family.execution candidate).adaptiveData)
  have hsubset : acceptedEvent ⊆ (earlierEvent ∪ friEvent) ∪ repairEvent := by
    intro challenges hmem
    have hcases := acceptedFalseEvent_subset_explicitFailures_union_repair
      family accepts semanticallyFalse hfour
      (show challenges ∈ predicateEvent
        (AcceptedFalseExecution accepts semanticallyFalse) by
          simpa [acceptedEvent] using hmem)
    rcases hcases with hearlier | hfri | hrepair
    · exact Finset.mem_union_left _
        (Finset.mem_union_left _ (by simpa [earlierEvent] using hearlier))
    · exact Finset.mem_union_left _
        (Finset.mem_union_right _ (by simpa [friEvent] using hfri))
    · exact Finset.mem_union_right _ (by simpa [repairEvent] using hrepair)
  have hcardSubset : acceptedEvent.card ≤
      ((earlierEvent ∪ friEvent) ∪ repairEvent).card :=
    Finset.card_le_card hsubset
  have hcardUnion : ((earlierEvent ∪ friEvent) ∪ repairEvent).card ≤
      earlierEvent.card + friEvent.card + repairEvent.card := by
    calc
      ((earlierEvent ∪ friEvent) ∪ repairEvent).card ≤
          (earlierEvent ∪ friEvent).card + repairEvent.card :=
        Finset.card_union_le _ _
      _ ≤ (earlierEvent.card + friEvent.card) + repairEvent.card :=
        Nat.add_le_add_right (Finset.card_union_le _ _) _
  have hcard : acceptedEvent.card ≤
      earlierEvent.card + friEvent.card + repairEvent.card :=
    hcardSubset.trans hcardUnion
  have hcardQ : (acceptedEvent.card : ℚ) ≤
      earlierEvent.card + friEvent.card + repairEvent.card := by
    exact_mod_cast hcard
  have hdenominator : (0 : ℚ) ≤
      Fintype.card (TwelveRelationChallenges K) := by positivity
  have hdiv := div_le_div_of_nonneg_right hcardQ hdenominator
  simpa only [uniformPredicateProbability,
    uniformBoundedCandidateRepairProbability, acceptedEvent, earlierEvent,
    friEvent, repairEvent, add_div] using hdiv

/-- A coherent family of at most 240 candidates has relation-repair mass at
most `32 * 240 / |K|`.

This specializes `uniformBoundedCandidateRepairProbability_le`; the cap is
not treated as a proof of FRI extraction or of candidate matching. -/
theorem coherent_candidate_repair_probability_le_240
    {Candidate : Type*} [Fintype Candidate] [DecidableEq Candidate]
    (family : CoherentCandidateFamily K Candidate)
    (hcard : Fintype.card Candidate ≤ 240) :
    uniformBoundedCandidateRepairProbability
        (fun candidate => (family.execution candidate).adaptiveData) ≤
      (32 * 240 : ℚ) / Fintype.card K := by
  have hbase := uniformBoundedCandidateRepairProbability_le
    (fun candidate => (family.execution candidate).adaptiveData)
  have hnumerator : (32 * Fintype.card Candidate : ℚ) ≤ 32 * 240 := by
    exact_mod_cast Nat.mul_le_mul_left 32 hcard
  have hdenominator : (0 : ℚ) ≤ Fintype.card K := by positivity
  exact hbase.trans (div_le_div_of_nonneg_right hnumerator hdenominator)

/-- Honest cap-240 endpoint for this decomposition.

The result is deliberately a sum with two visible, unbounded terms.  A full
Tag-67 theorem must separately bound `EarlierSemanticFailure` and
`FriExtractionOrMatchFailure` (and then connect ideal challenges to the
deployed transcript). -/
theorem uniform_accepted_false_probability_le_missing_terms_plus_240
    {Candidate : Type*} [Fintype Candidate] [DecidableEq Candidate]
    (family : CoherentCandidateFamily K Candidate)
    (accepts semanticallyFalse : TwelveRelationChallenges K → Prop)
    (hfour : (4 : K) ≠ 0)
    (hcard : Fintype.card Candidate ≤ 240) :
    uniformPredicateProbability
        (AcceptedFalseExecution accepts semanticallyFalse) ≤
      uniformPredicateProbability
          (EarlierSemanticFailure family accepts semanticallyFalse) +
      uniformPredicateProbability
          (FriExtractionOrMatchFailure family accepts semanticallyFalse) +
      (32 * 240 : ℚ) / Fintype.card K := by
  calc
    uniformPredicateProbability
        (AcceptedFalseExecution accepts semanticallyFalse) ≤
      uniformPredicateProbability
          (EarlierSemanticFailure family accepts semanticallyFalse) +
      uniformPredicateProbability
          (FriExtractionOrMatchFailure family accepts semanticallyFalse) +
      uniformBoundedCandidateRepairProbability
        (fun candidate => (family.execution candidate).adaptiveData) :=
      uniform_accepted_false_probability_le_explicit_failures_plus_repair
        family accepts semanticallyFalse hfour
    _ ≤
      uniformPredicateProbability
          (EarlierSemanticFailure family accepts semanticallyFalse) +
      uniformPredicateProbability
          (FriExtractionOrMatchFailure family accepts semanticallyFalse) +
      (32 * 240 : ℚ) / Fintype.card K := by
      linarith [coherent_candidate_repair_probability_le_240 family hcard]

#print axioms accepted_false_execution_decomposition
#print axioms acceptedFalseEvent_subset_explicitFailures_union_repair
#print axioms uniform_accepted_false_probability_le_explicit_failures_plus_repair
#print axioms coherent_candidate_repair_probability_le_240
#print axioms uniform_accepted_false_probability_le_missing_terms_plus_240

end FiniteField

end AspisV5Tag67FalseAcceptanceDecomposition
