import AspisV8R19.R481NativeQM31Cell
#check BitVec.getLsbD_ushiftRight
#check BitVec.getLsbD_shiftRight
#check BitVec.getLsbD_shiftLeft
#check BitVec.getLsbD_ushiftLeft
#check BitVec.ushiftLeft
#check BitVec.toNat_ushiftLeft
#check BitVec.toNat_ushiftRight
#check BitVec.getLsbD_ofNat
#check BitVec.getLsbD_append
#check BitVec.getLsbD_and
#check BitVec.getLsbD_or
#check BitVec.getLsbD_extractLsb'
#check BitVec.getLsbD_zeroExtend
#check BitVec.eq_of_getLsbD_eq
#check Nat.testBit_mul_two_pow
#check Nat.testBit_shiftLeft
#check Nat.testBit_eq
